type Row = { slug: string; title: string; subject: string; audience: string; checks: string[]; warning: string };

const rawRows: [string, string, string, string, string[], string][] = [
  ['outsourcing-accounts-receivable-follow-up-philippines', 'Outsourcing accounts receivable follow-up to the Philippines', 'accounts receivable follow-up', 'finance managers', ['open the approved aging view', 'match each reminder to the account record', 'route disputes to the owner'], 'Never negotiate a balance, waive a fee, or promise a payment date.'],
  ['outsourcing-purchase-order-processing-philippines', 'Outsourcing purchase order processing to the Philippines', 'purchase order processing', 'operations managers', ['read the approved request', 'check supplier and item fields', 'route mismatches before entry'], 'Never change quantities, prices, suppliers, or approval status.'],
  ['philippines-outsourcing-stock-reconciliation', 'Philippines outsourcing stock reconciliation guide', 'inventory reconciliation', 'ecommerce and operations teams', ['compare the two approved records', 'isolate the unmatched items', 'document the proposed correction'], 'Never adjust stock, cost, or availability without owner approval.'],
  ['philippines-outsourcing-service-booking-coordination', 'Philippines outsourcing service booking coordination checklist', 'appointment scheduling', 'service businesses', ['read the approved booking request', 'check the live availability rules', 'send the confirmed details'], 'Never make a clinical, legal, or priority decision for the customer.'],
  ['outsourcing-sales-operations-support-philippines', 'Outsourcing sales operations support to the Philippines', 'sales operations support', 'sales leaders', ['maintain the approved pipeline view', 'check required opportunity fields', 'surface stale or conflicting records'], 'Never change forecast commitments, deal terms, or customer promises.'],
  ['philippines-outsourcing-customer-implementation-admin', 'Philippines outsourcing customer implementation administration', 'customer onboarding support', 'customer success teams', ['check the signed handoff', 'prepare the approved welcome steps', 'record missing information'], 'Never accept contractual changes or certify compliance.'],
  ['outsourcing-social-media-moderation-philippines', 'Outsourcing social media moderation to the Philippines', 'social media moderation', 'marketing and community teams', ['apply the written moderation categories', 'capture the post and reason', 'route safety or legal concerns'], 'Never improvise a policy, debate a user, or remove an account outside the rule.'],
  ['philippines-outsourcing-competitor-research-support', 'Philippines outsourcing competitor research support', 'market research support', 'founders and marketing teams', ['define the approved question', 'capture source and date for each finding', 'separate fact from interpretation'], 'Never present a small sample as market truth or use restricted information.'],
  ['outsourcing-content-brief-preparation-philippines', 'Outsourcing content brief preparation to the Philippines', 'content brief preparation', 'marketing managers', ['collect the approved audience and goal', 'map claims to named sources', 'flag gaps for the editor'], 'Never invent evidence, publish copy, or make an unapproved claim.'],
  ['philippines-outsourcing-newsletter-operations', 'Philippines outsourcing newsletter operations guide', 'email campaign operations', 'marketing operations teams', ['load the approved audience', 'check links and suppression rules', 'route the final send for approval'], 'Never change consent status, audience rules, or send a campaign.'],
  ['outsourcing-logistics-coordination-philippines', 'Outsourcing logistics coordination to the Philippines', 'logistics coordination', 'operations teams', ['collect the carrier updates', 'compare them with the order record', 'escalate a missed handoff'], 'Never change a customs declaration, shipping promise, or customer remedy.'],
  ['philippines-outsourcing-quality-documentation', 'Philippines outsourcing quality documentation support', 'quality documentation', 'quality and operations managers', ['use the current controlled template', 'attach the required evidence', 'flag missing approvals'], 'Never backdate evidence, approve a deviation, or alter a controlled record.'],
  ['outsourcing-legal-intake-administration-philippines', 'Outsourcing legal intake administration to the Philippines', 'legal intake administration', 'professional services teams', ['capture the approved intake fields', 'check for duplicate matters', 'route urgency and conflicts'], 'Never give legal advice, assess a claim, or decide whether representation is accepted.'],
  ['philippines-outsourcing-insurance-claims-administration', 'Philippines outsourcing insurance claims administration', 'claims administration', 'insurance operations teams', ['index the supplied claim documents', 'check required fields', 'route incomplete or sensitive cases'], 'Never determine coverage, liability, settlement, or a claimant outcome.'],
  ['outsourcing-medical-office-administration-philippines', 'Outsourcing medical office administration to the Philippines', 'medical office administration', 'healthcare practices', ['use the approved scheduling script', 'verify administrative fields', 'route clinical questions'], 'Never interpret symptoms, disclose records, or make a clinical decision.'],
  ['philippines-outsourcing-property-management-admin', 'Philippines outsourcing property management administration', 'property management administration', 'property managers', ['log the approved maintenance request', 'check the property and vendor fields', 'route urgent conditions'], 'Never authorize repairs, change a lease term, or promise a tenant remedy.'],
  ['outsourcing-ecommerce-customer-support-philippines', 'Outsourcing ecommerce customer support to the Philippines', 'ecommerce customer support', 'online retailers', ['classify the request', 'use the approved response', 'route refunds and exceptions'], 'Never issue a refund, alter an order, or promise an outcome outside the policy.'],
  ['philippines-outsourcing-ledger-preparation', 'Philippines outsourcing ledger preparation guide', 'bookkeeping preparation', 'small business owners', ['collect the approved source records', 'match transactions to the rule set', 'list unresolved items'], 'Never file, approve, classify an uncertain transaction, or give tax advice.'],
  ['outsourcing-hr-records-administration-philippines', 'Outsourcing HR records administration to the Philippines', 'HR records administration', 'people operations teams', ['update the approved employee field', 'check the supporting document', 'log access and exceptions'], 'Never make an employment decision, expose a personnel record, or change compensation.'],
  ['philippines-outsourcing-learning-coordination', 'Philippines outsourcing learning coordination checklist', 'training coordination', 'people and operations teams', ['maintain the approved attendee list', 'check completion evidence', 'route attendance gaps'], 'Never certify competency, change required training, or make a safety determination.'],
  ['outsourcing-data-entry-quality-control-philippines', 'Outsourcing data-entry quality control to the Philippines', 'data-entry quality control', 'data and operations managers', ['sample the agreed records', 'compare fields to the source', 'classify each error by cause'], 'Never silently correct a source record or change the validation rule.'],
  ['philippines-outsourcing-appointment-reminder-calls', 'Philippines outsourcing appointment reminder calls', 'appointment reminder calls', 'service teams', ['use the approved call list', 'confirm only permitted details', 'record the response status'], 'Never disclose sensitive details, reschedule outside the script, or handle an emergency.'],
];
const rows: Row[] = rawRows.map(([slug, title, subject, audience, checks, warning]) => ({ slug, title, subject, audience, checks, warning }));

const details = (row: Row, index: number) => ({
  updated: '2026-08-11',
  keyword: row.title.toLowerCase(),
  marker: `daily-blog-batch-2026-08-11-${String(index + 1).padStart(2, '0')}`,
  takeaway: `${row.subject[0].toUpperCase()}${row.subject.slice(1)} works as an outsourced lane when ${row.audience} define the source, finish rule, and decision owner before access is granted. The Filipino specialist should complete repeatable checks and leave a usable record for the internal owner.`,
  comparison: [
    { weak: `Please help with ${row.subject}.`, strong: `Complete the named ${row.subject} queue, record the result, and stop at the written exception boundary.` },
    { weak: 'We will know quality when we see it.', strong: 'Review the source, required fields, action, note, and escalation for the first agreed sample.' },
    { weak: 'Give the role access to the system.', strong: 'Use a named account with only the permissions required for the approved queue.' },
  ],
  sections: [
    { heading: `Define the ${row.subject} lane`, body: [`Write down which records enter the lane, where they come from, how often they arrive, and what a complete item looks like. Give the specialist examples that show both a normal case and an incomplete case.`, `Keep adjacent work out of the first brief. A narrow queue lets ${row.audience} measure accuracy without confusing speed with a correct result.`] },
    { heading: 'Describe the normal handoff', body: [`A practical sequence is: ${row.checks[0]}, then ${row.checks[1]}, then ${row.checks[2]}. Put the source of truth beside each step and name the field or record that proves completion.`, 'For an open item, record the identifier, work already completed, missing input, and person who owns the next answer.'] },
    { heading: 'Keep judgment with the owner', body: [`The role needs a clear stop rule. ${row.warning}`, 'A stop rule is useful only when the internal owner and expected response window are named. Otherwise routine work becomes a queue of unanswered questions.'] },
    { heading: 'Set up a fair first review', body: ['Review the first batch against the same checklist for every item. Separate source problems, unclear rules, access problems, and execution mistakes so coaching fixes the right cause.', 'Once the lane is stable, use a documented sample and revisit it when risk, volume, or the source changes.'] },
    { heading: 'Plan the first month', body: [`Days 1–3: collect examples and write the finish rule. Days 4–8: run a work sample. Days 9–14: practice with safe records. Days 15–21: open one small live lane. Days 22–30: review misses and repair the guide.`, 'Add another responsibility only after the first lane has a reliable owner, bounded access, and an escalation path that works in practice.'] },
  ],
  workflow: [
    { step: 'Days 1–3', title: 'Map the source', body: `Document the queue, examples, access, finish rule, and stop rules for ${row.subject}.` },
    { step: 'Days 4–8', title: 'Test three cases', body: 'Use a normal case, an incomplete case, and an exception case with the same review fields.' },
    { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or masked historical work and review every result before live access.' },
    { step: 'Days 15–21', title: 'Open one lane', body: 'Keep live volume small and make the named owner available for blocked cases.' },
    { step: 'Days 22–30', title: 'Repair the guide', body: 'Group misses by cause, update the source or instructions, and confirm the change with a new sample.' },
  ],
  script: [`Which exact ${row.subject} cases belong in the first queue?`, 'What evidence proves a normal item is complete?', `Which decisions stay with ${row.audience}, and who answers an exception?`, 'Which named accounts are needed, and when will access be removed?'],
  sourcesNumbered: true,
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Reference for organizing security risk, access, response, and recovery practices.' }],
  faqs: [
    { question: `What should be outsourced first in ${row.subject}?`, answer: 'Start with recurring work that has examples, a visible finish, limited access, and a named reviewer. Keep judgment and approvals with the appropriate owner.' },
    { question: 'How should the first batch be reviewed?', answer: 'Use the same source, field, action, note, and escalation checks for every item, then record the cause of each miss.' },
    { question: 'When should the specialist stop?', answer: row.warning },
  ],
  relatedLinks: [{ label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' }, { label: 'Use the quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' }, { label: 'See back-office operations support', href: '/services/back-office-operations' }],
});

export const blogBatch2026_08_11Posts = rows.map((row) => ({ slug: row.slug, title: row.title, excerpt: `A practical ${row.subject} guide for setting a clear queue, limited access, and an owner for exceptions.`, minutes: 10 }));
export const blogBatch2026_08_11Details = Object.fromEntries(rows.map((row, index) => [row.slug, details(row, index)]));
