const updated = '2026-08-31';
const image = '/images/operations-meeting.jpg';
const sources = [{ label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { label: 'AAPOR Transparency Initiative', href: 'https://aapor.org/standards-and-ethics/transparency-initiative/' }];
const related = [{ label: 'Research index', href: '/research' }, { label: 'Philippines outsourcing guides', href: '/blog' }];
type Study = { slug: string; title: string; excerpt: string; question: string; method: string; unit: string; classes: string; metrics: string; test: string; limit: string; conclusion: string };

const studies: Study[] = [
  { slug: 'handoff-latency-research', title: 'How to measure handoff latency in Philippines outsourcing', excerpt: 'A bounded method for measuring where outsourced work waits between preparation, review, decision, and return.', question: 'Where does a case wait when work moves between a Philippines-based specialist and an internal decision owner?', method: 'For four weeks, retain intake, first review, hold, escalation, owner response, return, and closure times. Stratify by case class and shift; report medians and upper percentiles, not only an average.', unit: 'one case with one stable identifier. A message count is not a case count, and a reopened case keeps its first chronology', classes: 'active preparation, customer wait, system wait, internal-owner wait, scheduled shift wait, and correction', metrics: 'state duration, transition frequency, reopened cases, packet returns, and missing timestamps', test: 'Trace a case that crosses a shift and waits for a specialized owner. Confirm that the chronology distinguishes correct waiting from unattended work.', limit: 'System logs may be incomplete, asynchronous channels blur active time, and four weeks may miss seasonal demand.', conclusion: 'Use latency to repair states and ownership, not to impose one universal speed target.' },
  { slug: 'escalation-threshold-consistency', title: 'Testing escalation-threshold consistency in Philippines outsourcing', excerpt: 'A sampling design for checking whether the same evidence reaches the same escalation path across reviewers and shifts.', question: 'Do reviewers apply a written escalation threshold consistently when the same evidence appears?', method: 'Build a blinded set of ordinary, near-threshold, clearly escalated, incomplete, and conflicting cases. Reviewers classify independently with the active procedure before calibration.', unit: 'one blinded case paired with the rule version, classification, requested evidence, stop decision, and reason', classes: 'correct stop, permitted continuation, false negative, false positive, unresolved, and rule ambiguity', metrics: 'raw agreement by case class, missed consequential stops, owner corrections, and held-out performance', test: 'After clarifying ambiguous wording, use new cases. Improvement only on discussed examples may reflect memorization rather than an operational rule.', limit: 'Small samples make agreement statistics unstable, reviewers may share training, and constructed cases cannot represent all future work.', conclusion: 'Scale only when consequential cases stop reliably and near-threshold disagreement has a reachable owner path.' },
  { slug: 'source-freshness-research', title: 'Measuring source freshness in Philippines outsourced operations', excerpt: 'Research on whether queue decisions rely on the current approved source rather than a plausible obsolete copy.', question: 'Can a Philippines-based queue identify the controlling source at the moment each case is prepared?', method: 'Inventory sources, assign owners and effective rules, then sample cases across a material change. Record source identifier, version, effective window, access path, and applied value.', unit: 'one case-source pair evaluated against the approved source that controlled the relevant case event', classes: 'current match, stale link, local copy, unclear effective date, conflicting field, inaccessible source, and action error', metrics: 'active-source match, untraceable use, retirement time, and corrections by failure class', test: 'Inspect a case opened before a change and completed after it, plus the bookmarks, templates, pinned messages, and automation used on the live work surface.', limit: 'Caches, offline exports, missing histories, and ambiguous effective events restrict certainty. This does not certify the substantive policy.', conclusion: 'Freshness exists when the team can reproduce which approved source controlled every sampled case.' },
  { slug: 'owner-response-capacity', title: 'Owner-response capacity for Philippines outsourcing queues', excerpt: 'A capacity study for the internal decisions that remain after operational preparation is outsourced.', question: 'Does the internal owner have reachable capacity to decide cases the outsourced queue must not resolve?', method: 'For one month, count decision requests by type, arrival window, effort band, required owner, response time, disposition, and rework caused by incomplete packets.', unit: 'one decision request with a stable case reference, named authority, arrival time, response, and final disposition', classes: 'routine review, policy, finance, security, privacy, people, legal, customer remedy, and unresolved ownership', metrics: 'arrival rate, backlog age, response distribution, unanswered requests, backup use, and evidence returns', test: 'Model owner absence and a volume surge. Verify the queue has a named backup or a holding response that makes no unauthorized promise.', limit: 'Decision effort varies, volumes may be small, and side-channel decisions may be missing from the record.', conclusion: 'Add outsourced volume only when retained decision capacity grows with the expected exception load.' },
  { slug: 'rework-cause-analysis', title: 'Rework-cause analysis for Philippines outsourcing', excerpt: 'A fair method for separating instruction, source, tool, handoff, and execution causes in corrected outsourced work.', question: 'What caused work to be corrected after a Philippines-based specialist prepared it?', method: 'Sample corrected and uncorrected cases from the same period and class. Reconstruct evidence available at the time, the active instruction, tool behavior, handoff, output, review, and disposition.', unit: 'one case evaluated at its original decision time rather than against facts or policy introduced later', classes: 'ambiguous instruction, missing source, conflict, tool constraint, access limit, late change, handoff omission, execution miss, owner reversal, and unresolved', metrics: 'correction rate with denominator, repeat causes, correction direction, time cost, and exposure in uncorrected work', test: 'Blind the first cause review where practical and permit multiple causes. Then test whether the chosen repair reduces the pattern on a held-out sample.', limit: 'Reviewer disagreement, incomplete histories, selective correction, and interacting causes prevent universal attribution.', conclusion: 'Rework becomes useful evidence when the organization shows what changed, what the worker could see, and which control failed.' },
];

const body = (s: Study) => [
  `Research question: ${s.question} Published August 31, 2026, this study treats the queue as a bounded operating system rather than making a general claim about workers or the Philippines.`,
  `Methodology: ${s.method} Predefine exclusions and preserve missing observations so a clean-looking result does not hide incomplete evidence.`,
  `The unit of analysis is ${s.unit}. Sampling should include ordinary, incomplete, conflicting, urgent, and boundary cases from the actual decision frame.`,
  `Classify observations as ${s.classes}. Keep observed facts separate from the reviewer’s causal interpretation, and retain the active rule version beside each score.`,
  `Measure ${s.metrics}. Show counts and denominators. A single average or percentage can conceal rare but consequential failures and differences in case mix.`,
  `Validation test: ${s.test} Record owner corrections without turning later outcomes into a hidden answer key for what was knowable earlier.`,
  'The outsourced role may gather timestamps, compare permitted sources, apply explicit categories, and prepare the evidence packet. Internal owners retain policy, legal, financial, employment, security, priority, and customer-remedy decisions. Silence or an approaching target never creates approval.',
  'Protect case data with named access, minimum necessary fields, and de-identification in aggregate reporting. Preserve chronology and corrections. Do not use operational research to rank individuals when the question concerns the rule, source, tool, handoff, or owner system.',
  `Limitations: ${s.limit} Repeat the review after a material change in policy, tool, ownership, queue, shift, or volume.`,
  `Conclusion: ${s.conclusion} The finding supports a scoped operating decision, not a guarantee about every future case.`
];

export const researchPosts2026_08_31 = studies.map(s => ({ slug: `philippines-outsourcing-${s.slug}`, title: s.title, excerpt: s.excerpt, updated, datePublished: updated, displayDate: 'August 31, 2026', image, imageAlt: 'Operations teammates reviewing documented evidence together', body: body(s), sources, related, cta: 'Bring one recurring queue, its source records, boundaries, and owner decisions to the staffing intake.' }));
