type Row = {
  slug: string; title: string; subject: string; audience: string;
  steps: [string, string, string]; stop: string; angle: string; date: '2026-08-13';
};

// Each source record intentionally owns its literal publication date. Do not move this
// field to a shared constant or derive it from a neighboring batch.
const rows: Row[] = [
  { slug: 'philippines-outsourcing-account-reconciliation-prep', title: 'Philippines outsourcing account reconciliation preparation', subject: 'account reconciliation preparation', audience: 'finance operations managers', steps: ['open the approved ledger extract', 'match the stated source records', 'list variances with evidence'], stop: 'Stop before posting an adjustment, selecting an accounting treatment, or closing a reconciliation.', angle: 'Preparation makes reconciliation review faster when every variance remains visible.', date: '2026-08-13' },
  { slug: 'outsourcing-customer-identity-verification-philippines', title: 'Outsourcing customer identity verification support to the Philippines', subject: 'customer identity verification support', audience: 'customer operations leaders', steps: ['open the approved verification request', 'compare the permitted fields', 'route an incomplete match'], stop: 'Stop before overriding a failed check, approving access, or disclosing protected information.', angle: 'A bounded verification queue protects customers by making exceptions explicit.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-product-catalog-admin', title: 'Philippines outsourcing product catalog administration', subject: 'product catalog administration', audience: 'ecommerce operations managers', steps: ['read the approved change ticket', 'update allowed catalog fields', 'record the source and result'], stop: 'Stop before changing a product claim, price, availability, or compliance attribute.', angle: 'Catalog administration is reliable when every public field has an accountable source.', date: '2026-08-13' },
  { slug: 'outsourcing-insurance-claim-intake-philippines', title: 'Outsourcing insurance claim intake to the Philippines', subject: 'insurance claim intake', audience: 'service operations teams', steps: ['capture the claimant and case reference', 'check the required intake fields', 'route missing evidence to the owner'], stop: 'Stop before assessing coverage, assigning liability, or promising a claim outcome.', angle: 'Intake support should organize evidence without turning collection into adjudication.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-purchase-order-admin', title: 'Philippines outsourcing purchase order administration', subject: 'purchase order administration', audience: 'procurement and finance teams', steps: ['check the approved requisition', 'prepare the allowed order fields', 'route mismatches for approval'], stop: 'Stop before selecting a supplier, changing terms, or authorizing a purchase.', angle: 'Purchase order support works when record accuracy is separated from buying authority.', date: '2026-08-13' },
  { slug: 'outsourcing-membership-renewal-admin-philippines', title: 'Outsourcing membership renewal administration to the Philippines', subject: 'membership renewal administration', audience: 'association operations leaders', steps: ['review the renewal list', 'check the approved member fields', 'prepare the owner follow-up queue'], stop: 'Stop before changing eligibility, granting an exception, or handling a disputed payment.', angle: 'Renewal administration keeps relationships orderly while policy decisions stay with the owner.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-case-file-indexing', title: 'Philippines outsourcing case file indexing', subject: 'case file indexing', audience: 'legal and operations teams', steps: ['open the named source document', 'apply the approved index fields', 'flag missing or conflicting metadata'], stop: 'Stop before interpreting a case, altering evidence, or deciding whether a file is complete.', angle: 'Indexing creates findable records without asking administrators to interpret sensitive matters.', date: '2026-08-13' },
  { slug: 'outsourcing-customer-address-updates-philippines', title: 'Outsourcing customer address updates to the Philippines', subject: 'customer address updates', audience: 'customer and order operations teams', steps: ['verify the authorized request', 'update the permitted address fields', 'record the confirmation path'], stop: 'Stop before changing an order in transit, bypassing identity checks, or exposing another customer record.', angle: 'Address support needs identity discipline because a small field change can affect delivery.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-recruiting-interview-coordination', title: 'Philippines outsourcing recruiting interview coordination', subject: 'recruiting interview coordination', audience: 'people operations teams', steps: ['read the approved candidate availability', 'offer the allowed interview windows', 'record confirmations and conflicts'], stop: 'Stop before evaluating a candidate, changing selection status, or making a hiring promise.', angle: 'Coordination removes calendar friction while selection remains a human decision.', date: '2026-08-13' },
  { slug: 'outsourcing-warranty-claim-administration-philippines', title: 'Outsourcing warranty claim administration to the Philippines', subject: 'warranty claim administration', audience: 'product support managers', steps: ['match the request to the product record', 'capture the required evidence', 'route an exception under the guide'], stop: 'Stop before deciding warranty coverage, promising replacement, or authorizing a remedy.', angle: 'Warranty administration is safest when evidence collection and remedy approval are separate.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-survey-response-coding', title: 'Philippines outsourcing survey response coding', subject: 'survey response coding', audience: 'research and customer experience teams', steps: ['apply the approved coding guide', 'retain the response reference', 'flag an ambiguous answer'], stop: 'Stop when the response signals a safety issue, legal claim, or category outside the guide.', angle: 'Consistent coding reveals patterns while preserving the difference between a label and a conclusion.', date: '2026-08-13' },
  { slug: 'outsourcing-service-report-preparation-philippines', title: 'Outsourcing service report preparation to the Philippines', subject: 'service report preparation', audience: 'service delivery managers', steps: ['collect the approved source reports', 'check the stated reporting period', 'list gaps before circulation'], stop: 'Stop before changing a metric, explaining an unexplained variance, or certifying performance.', angle: 'Report preparation earns trust by showing source, period, gap, and owner together.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-donation-record-admin', title: 'Philippines outsourcing donation record administration', subject: 'donation record administration', audience: 'nonprofit operations teams', steps: ['open the authorized donation record', 'update the permitted acknowledgment fields', 'route a restricted or unclear gift'], stop: 'Stop before changing donor intent, issuing a tax statement, or releasing restricted funds.', angle: 'Careful record work respects both donor instructions and finance ownership.', date: '2026-08-13' },
  { slug: 'outsourcing-distributor-order-coordination-philippines', title: 'Outsourcing distributor order coordination to the Philippines', subject: 'distributor order coordination', audience: 'sales and operations leaders', steps: ['compare the request with the approved account record', 'prepare the allowed order details', 'route inventory or terms exceptions'], stop: 'Stop before promising availability, changing commercial terms, or approving a credit.', angle: 'Coordination can shorten order cycles without transferring commercial authority.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-employee-record-maintenance', title: 'Philippines outsourcing employee record maintenance', subject: 'employee record maintenance', audience: 'people operations and HR teams', steps: ['open the approved change request', 'update only the named fields', 'record the reviewer and source'], stop: 'Stop before changing pay, status, eligibility, or releasing confidential employee information.', angle: 'Employee record maintenance needs narrow permissions and an auditable change source.', date: '2026-08-13' },
  { slug: 'outsourcing-utility-bill-data-entry-philippines', title: 'Outsourcing utility bill data entry to the Philippines', subject: 'utility bill data entry', audience: 'property and facilities teams', steps: ['open the supplied bill image', 'enter the stated account and period fields', 'flag unreadable or conflicting values'], stop: 'Stop before approving a bill, changing a vendor record, or authorizing payment.', angle: 'Entry support is useful when uncertain values are flagged instead of guessed.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-training-record-admin', title: 'Philippines outsourcing training record administration', subject: 'training record administration', audience: 'people and compliance teams', steps: ['open the approved attendance source', 'update the named completion fields', 'route missing evidence to the owner'], stop: 'Stop before declaring competence, waiving a requirement, or certifying compliance.', angle: 'Training records should prove what was recorded, not overstate what a person can do.', date: '2026-08-13' },
  { slug: 'outsourcing-property-maintenance-intake-philippines', title: 'Outsourcing property maintenance intake to the Philippines', subject: 'property maintenance intake', audience: 'property operations managers', steps: ['capture the location and reported issue', 'check the emergency-routing fields', 'send the request to the named queue'], stop: 'Stop before declaring an emergency safe, selecting a contractor, or promising a completion time.', angle: 'Good intake separates a complete report from the maintenance judgment that follows.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-merchant-document-collection', title: 'Philippines outsourcing merchant document collection', subject: 'merchant document collection', audience: 'marketplace and payments operations teams', steps: ['request the named merchant document', 'check presence and stated expiry', 'route an exception with the record link'], stop: 'Stop before approving a merchant, interpreting a compliance rule, or restricting an account.', angle: 'Collection creates a clean review queue while approval remains with the accountable team.', date: '2026-08-13' },
  { slug: 'outsourcing-customer-credit-note-preparation-philippines', title: 'Outsourcing customer credit note preparation to the Philippines', subject: 'customer credit note preparation', audience: 'finance and customer operations teams', steps: ['match the approved case to the account', 'prepare the permitted draft fields', 'route it to the named approver'], stop: 'Stop before issuing a credit, changing a balance, or deciding whether a complaint merits compensation.', angle: 'Draft preparation reduces administrative delay without moving financial judgment to the queue.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-wholesale-invoice-follow-up', title: 'Philippines outsourcing wholesale invoice follow-up preparation', subject: 'wholesale invoice follow-up preparation', audience: 'accounts receivable teams', steps: ['open the approved aging report', 'match the account and invoice references', 'prepare the owner review queue'], stop: 'Stop before promising a concession, changing a due date, or discussing a disputed balance as settled.', angle: 'A factual follow-up queue helps receivables owners act on the right account without improvising commercial terms.', date: '2026-08-13' },
  { slug: 'philippines-outsourcing-document-translation-coordination', title: 'Philippines outsourcing document translation coordination', subject: 'document translation coordination', audience: 'operations and legal support teams', steps: ['log the source and requested language', 'check the delivery brief and version', 'route sensitive or ambiguous text'], stop: 'Stop before certifying a translation, interpreting legal meaning, or editing the source record.', angle: 'Coordination keeps versions and owners clear when language work crosses teams.', date: '2026-08-13' },
];

const details = (row: Row, index: number) => ({
  updated: row.date,
  keyword: row.title.toLowerCase(),
  marker: `august-13-blog-replacement-${String(index + 1).padStart(2, '0')}`,
  takeaway: `${row.angle} A Filipino specialist can handle the repeatable checks when the source, finish rule, access, and escalation owner are written down before the queue opens.`,
  comparison: [
    { weak: `We need help with ${row.subject}.`, strong: `Complete the approved ${row.subject} queue, record each result, and stop at the written exception boundary.` },
    { weak: 'Quality means keeping up with the queue.', strong: 'Review the source, action, note, and escalation against the same sample of early work.' },
    { weak: 'Give the role access to the system.', strong: 'Use a named account with only the permissions needed for this lane; approval stays with the owner.' },
  ],
  sections: [
    { heading: `Choose the right ${row.subject} lane`, body: [`Name which records enter the queue, where they arrive, how often they arrive, and what a complete item looks like. Add one normal example and one incomplete example to the brief.`, `Keep neighboring responsibilities out of the first assignment. A narrow lane lets ${row.audience} review accuracy without confusing activity with a correct result.`] },
    { heading: 'Write the normal handoff', body: [`A practical path is: ${row.steps[0]}, then ${row.steps[1]}, then ${row.steps[2]}. Put the source of truth beside each step and name the field or record that proves completion.`, 'For blocked work, record the identifier, action already taken, missing information, and person who owns the next answer.'] },
    { heading: 'Separate administration from judgment', body: [`The specialist needs a clear stop rule. ${row.stop}`, 'A stop rule works only when the internal owner and response path are named. Otherwise normal work becomes a queue of unanswered questions.'] },
    { heading: 'Protect the record and the customer', body: ['Use named accounts, the lowest practical permission, and the approved system of record. Separate reading, drafting, sending, approving, exporting, deleting, and administration.', 'Use masked examples or a test space for training. Do not copy live personal information into an informal worksheet.'] },
    { heading: 'Review before expanding the role', body: ['Check the first batch against the same fields: correct source, complete action, accurate note, and proper escalation. Record the cause of a miss so the remedy fits the problem.', `Add another responsibility only when the ${row.subject} lane has a stable source, a repeatable review, and no unresolved ownership gap.`] },
  ],
  workflow: [
    { step: 'Days 1–3', title: 'Map the source', body: `Document examples, access, schedule, finish rule, and stop rules for ${row.subject}.` },
    { step: 'Days 4–8', title: 'Test three cases', body: 'Use a normal case, an incomplete case, and an exception case with the same review fields.' },
    { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or masked historical work and review every result before live access.' },
    { step: 'Days 15–21', title: 'Open one lane', body: 'Keep live volume small and make the named owner available for blocked cases.' },
    { step: 'Days 22–30', title: 'Repair the guide', body: 'Group misses by cause, update the instructions, and confirm the change with a new sample.' },
  ],
  script: [`Which exact ${row.subject} cases belong in the first queue?`, 'What evidence proves a normal item is complete?', `Which decisions stay with ${row.audience}, and who answers an exception?`, 'Which named accounts are needed, and when will access be removed?'],
  sourcesNumbered: true,
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Reference for organizing access, risk, response, and recovery practices around business work.' }],
  faqs: [
    { question: `What should be outsourced first in ${row.subject}?`, answer: 'Start with recurring work that has examples, a visible finish, limited access, and a named reviewer. Keep judgment and approvals with the appropriate owner.' },
    { question: 'How should the first batch be reviewed?', answer: 'Use the same source, field, action, note, and escalation checks for every item, then record the cause of each miss.' },
    { question: 'When should the specialist stop?', answer: row.stop },
  ],
  relatedLinks: [{ label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' }, { label: 'Use the quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' }, { label: 'See back-office operations support', href: '/services/back-office-operations' }],
});

export const blogBatch2026_08_13Posts = rows.map((row) => ({ slug: row.slug, title: row.title, excerpt: `A practical ${row.subject} guide for setting a clear queue, limited access, and an owner for exceptions.`, minutes: 10 }));
export const blogBatch2026_08_13Details = Object.fromEntries(rows.map((row, index) => [row.slug, details(row, index)]));
