const updated = '2026-09-01';
const image = '/images/operations-meeting.jpg';
const sources = [{ label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { label: 'AAPOR Transparency Initiative', href: 'https://aapor.org/standards-and-ethics/transparency-initiative/' }];
const related = [{ label: 'Research index', href: '/research' }, { label: 'Philippines outsourcing guides', href: '/blog' }];
type Study = { slug: string; title: string; excerpt: string; question: string; method: string; unit: string; classes: string; measures: string; validation: string; limitation: string; finding: string };

const studies: Study[] = [
  { slug: 'queue-arrival-variability-study', title: 'Studying queue-arrival variability in Philippines outsourced operations', excerpt: 'A practical design for distinguishing recurring demand patterns from one-off spikes before staffing a queue.', question: 'How much does work arrival vary by day, hour, case class, and source channel?', method: 'Retain eight weeks of arrival timestamps, stable case identifiers, source channels, and case classes. Predefine business hours and exclusions, then compare distributions by week rather than collapsing everything into one average.', unit: 'one newly opened case; replies and status changes do not create new arrivals', classes: 'scheduled, customer initiated, system generated, internal request, reopened, duplicate, and unclassified', measures: 'median and upper-percentile arrivals per interval, zero-arrival intervals, peak concentration, duplicate rate, and classification coverage', validation: 'Hold out the final two weeks and check whether the earlier pattern describes their range without adjusting assumptions after seeing the result.', limitation: 'Eight weeks may miss holidays, campaigns, outages, and seasonality, while timestamp quality can differ by channel.', finding: 'Use observed ranges and scenarios to plan coverage; do not convert a short history into a guaranteed workload.' },
  { slug: 'evidence-packet-completeness-study', title: 'Measuring evidence-packet completeness in Philippines outsourcing', excerpt: 'A sampling method for testing whether decision owners receive the facts they need without unnecessary sensitive data.', question: 'Do prepared escalation packets contain every required field and only the evidence needed for the decision?', method: 'Define required and prohibited fields by case class, then sample packets across workers, shifts, ordinary cases, and consequential exceptions. Score the first submitted version before owner corrections.', unit: 'one packet submitted for one named owner decision with a stable case reference', classes: 'complete, missing required evidence, unsupported claim, unnecessary sensitive data, stale source, conflicting source, and wrong owner', measures: 'first-submit completeness, missing-field frequency, prohibited-field exposure, owner return rate, and correction time', validation: 'Have a second reviewer independently score a blinded subset, reconcile rubric ambiguity, and test the revised rule on unseen packets.', limitation: 'Owner preferences may be mistaken for requirements, rare fields may be absent from the sample, and reviewers can share assumptions.', finding: 'A useful packet minimizes both missing decision evidence and unnecessary disclosure rather than maximizing attached material.' },
  { slug: 'procedure-change-adoption-study', title: 'Testing procedure-change adoption in Philippines outsourced teams', excerpt: 'Research for determining whether a changed instruction reached live work across shifts, tools, templates, and backups.', question: 'After an approved procedure change, when does each work surface consistently reflect the new rule?', method: 'Record the approval, effective event, distribution, acknowledgment, training check, template update, and first qualifying live cases. Sample before and after the change across shifts and backup coverage.', unit: 'one qualifying case paired with the procedure version available on its live work surface at the relevant time', classes: 'correct new rule, valid old rule before effective time, stale instruction, stale template, inaccessible source, ambiguous transition, and execution miss', measures: 'time to full surface update, qualifying-case adherence, stale exposure, correction direction, and version traceability', validation: 'Inspect a case that began before the effective event and ended afterward, plus a case handled by backup coverage.', limitation: 'Few qualifying cases can delay inference, cached content may be invisible, and effective-time wording may itself be ambiguous.', finding: 'Adoption is demonstrated by versioned live evidence, not by an announcement or acknowledgment alone.' },
  { slug: 'owner-hold-resolution-study', title: 'Owner-hold resolution research for Philippines outsourcing', excerpt: 'A study of whether escalated cases reach an authorized owner and return to the queue with a usable decision.', question: 'What happens after an outsourced specialist correctly places a case on an owner hold?', method: 'Follow owner holds for six weeks from creation through acknowledgment, decision, return, and closure. Preserve hold reason, evidence quality, owner role, backup use, and every reassignment.', unit: 'one hold requesting one consequential decision; split requests that require different authorities', classes: 'resolved by primary, resolved by backup, returned for evidence, reassigned, withdrawn, expired, duplicate, and unresolved', measures: 'acknowledgment and resolution distributions, aged unresolved holds, reassignment count, evidence returns, and reopen rate', validation: 'Trace high-risk and after-hours holds separately and verify sampled decisions came from roles with the required authority.', limitation: 'Side-channel decisions may be missing, decision complexity varies, and six weeks may not capture rare specialist-owner cases.', finding: 'A stop rule is operational only when its owner path returns timely, attributable decisions to the queue.' },
  { slug: 'sampling-drift-detection-study', title: 'Detecting quality-sampling drift in Philippines outsourced operations', excerpt: 'A method for checking whether a quality sample still represents the live queue after volume, mix, or routing changes.', question: 'Does the current review sample represent the cases and risks present in the live outsourced queue?', method: 'Compare the sampling frame with the full eligible population for six consecutive review cycles. Retain selection rules, exclusions, case class, risk tier, channel, shift, and reviewer.', unit: 'one eligible completed case, including cases excluded by the sampling process with an explicit reason', classes: 'sampled, randomly eligible but not selected, risk-targeted, unavailable, excluded by rule, and missing from frame', measures: 'coverage by class and risk, selection probability, unavailable rate, reviewer concentration, and error exposure outside the sample', validation: 'Draw an independent spot sample from the source population and compare its mix and findings with the routine review.', limitation: 'Source populations may be incomplete, targeted oversampling requires weighting, and rare risks yield unstable rates.', finding: 'Quality results remain interpretable only when selection rules and coverage move with the live queue.' },
];

const body = (s: Study) => [
  `Research question: ${s.question} Published September 1, 2026, this protocol examines a bounded operating process rather than making a general claim about people or locations.`,
  `Methodology: ${s.method} Preserve missing observations and document exclusions before reviewing outcomes.`,
  `The unit of analysis is ${s.unit}. Keep identifiers stable so messages, edits, and reopens do not silently inflate the denominator.`,
  `Classify observations as ${s.classes}. Store observed facts separately from later causal judgments and owner decisions.`,
  `Measure ${s.measures}. Report counts, denominators, and distributions; a lone average can conceal rare but consequential cases.`,
  `Validation: ${s.validation} Predefine what would count as support, uncertainty, and a reason to repeat the study.`,
  'A Philippines-based specialist may collect permitted records, apply documented categories, and prepare analysis. Internal owners retain policy, legal, financial, privacy, employment, security, and customer-remedy decisions.',
  'Use named access, minimum necessary data, and de-identified aggregates where practical. Preserve corrections and chronology, and do not repurpose process research as an unsupported ranking of individuals.',
  `Limitations: ${s.limitation} Repeat the study after material changes to the procedure, tool, routing, ownership, case mix, or coverage.`,
  `Conclusion: ${s.finding} The result supports a scoped management decision, not certainty about every future case.`,
];

export const researchPosts2026_09_01 = studies.map(s => ({ slug: `philippines-outsourcing-${s.slug}`, title: s.title, excerpt: s.excerpt, updated, datePublished: updated, displayDate: 'September 1, 2026', image, imageAlt: 'Operations teammates reviewing documented evidence together', body: body(s), sources, related, cta: 'Bring one recurring queue, its evidence, boundaries, and owner decisions to the staffing intake.' }));
