import type { ResearchPost } from './article-research-batch';

const image = '/images/operations-meeting.jpg';
const imageAlt = 'Operations team reviewing a work queue together';
const related = [{ label: 'Research index', href: '/research' }, { label: 'Back-office operations', href: '/services/back-office-operations' }, { label: 'Data management', href: '/services/data-management' }];
const cta = 'Bring the queue, source owners, access needs, and review boundary to a staffing intake.';

type Topic = {
  slug: string; title: string; excerpt: string; question: string; unit: string; lens: string;
  scenario: string; finding: string; limitation: string; sources: Array<{ label: string; href: string }>;
  datePublished?: '2026-08-17'; updated?: '2026-08-17';
};

const topics: Topic[] = [
  { slug: 'philippines-outsourcing-inbox-triage-evidence', title: 'Inbox-triage evidence in Philippines outsourcing', excerpt: 'Research on separating safe message classification from policy, money, and customer decisions in a Philippines-based support queue.', question: 'When can an outsourced inbox role classify and route messages without silently making the decision itself?', unit: 'messages received by channel and category during a named two-week period', lens: 'sender identity, intent, sensitivity, promised response, and the authoritative record', scenario: 'a normal request, an incomplete request, a duplicate, a threatening message, and a message containing unnecessary personal information', finding: 'classification quality is not the same as response quality: a well-routed message can still wait if the owner and response window are absent', limitation: 'a sampled inbox cannot establish the meaning of every message or determine a legal, safety, or customer remedy', sources: [{ label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { label: 'FTC: Protecting Personal Information', href: 'https://www.ftc.gov/business-guidance/privacy-security' }] },
  { slug: 'philippines-outsourcing-crm-deduplication-research', title: 'CRM deduplication research for Philippines outsourcing', excerpt: 'What evidence can show that outsourced CRM cleanup improves record usability without erasing legitimate customer history?', question: 'Which signals distinguish a true duplicate from two records that should remain separate?', unit: 'customer or prospect records in a fixed CRM snapshot, grouped by match confidence', lens: 'stable identifiers, source history, consent state, ownership, and the consequence of merging', scenario: 'exact matches, shared household details, changed domains, aliases, and two records with conflicting source dates', finding: 'a similarity score can prioritize review, but it cannot grant authority to merge records when history or consent differs', limitation: 'one snapshot misses later changes and cannot prove that a merged record will improve every downstream process', sources: [{ label: 'NIST Privacy Framework', href: 'https://www.nist.gov/privacy-framework' }, { label: 'ICO: Accuracy principle', href: 'https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/the-accuracy-principle/' }] },
  { slug: 'philippines-outsourcing-invoice-coding-boundaries', title: 'Invoice-coding boundaries in Philippines outsourcing', excerpt: 'Evidence-led research on preparing invoice classifications while keeping payment approval with the authorized finance owner.', question: 'What can an outsourced finance-operations role infer from an invoice, and what must remain an approval decision?', unit: 'invoices received in a defined accounting period, stratified by supplier and exception type', lens: 'purchase evidence, tax fields, coding confidence, duplicate risk, and approval authority', scenario: 'a routine invoice, a missing purchase reference, a duplicate number, a changed bank detail, and a disputed service', finding: 'coding consistency may reduce review effort, but it does not prove that the service was received or that payment is authorized', limitation: 'public accounting guidance cannot determine a particular company’s tax treatment, contract meaning, or fraud risk', sources: [{ label: 'NIST SP 800-53 Rev. 5', href: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' }, { label: 'ACFE: Occupational Fraud 2024', href: 'https://www.acfe.com/fraud-resources/report-to-the-nations' }] },
  { slug: 'philippines-outsourcing-candidate-scheduling-research', title: 'Candidate-scheduling evidence in Philippines outsourcing', excerpt: 'Research on measuring coordination quality when a Philippines-based recruitment role manages interviews without deciding who gets hired.', question: 'Which scheduling signals show reliable candidate coordination while keeping selection judgment with the hiring team?', unit: 'interviews arranged, moved, or cancelled in a defined recruitment cohort', lens: 'time-zone clarity, candidate consent, interviewer availability, status accuracy, and handoff completeness', scenario: 'a first booking, a reschedule across UTC+8, an accessibility request, a no-show, and an interviewer change', finding: 'calendar throughput is a weak proxy for candidate experience unless the record preserves consent, time zone, and the next owner', limitation: 'coordination data cannot establish fairness of selection, candidate quality, or employment-law compliance', sources: [{ label: 'EEOC: Select Issues in Recruitment and Hiring', href: 'https://www.eeoc.gov/laws/guidance/select-issues-assessing-adverse-impact-software-algorithms-and-artificial-intelligence-used' }, { label: 'IANA Time Zone Database', href: 'https://www.iana.org/time-zones' }] },
  { slug: 'philippines-outsourcing-ecommerce-order-exceptions', title: 'Ecommerce order-exception research in Philippines outsourcing', excerpt: 'How to study order exceptions without giving a Philippines-based operations role uncontrolled power over refunds, promises, or inventory.', question: 'Which order evidence supports safe routing, and where must an internal owner decide the remedy?', unit: 'orders placed during a stated period, separated into normal, blocked, returned, and disputed cohorts', lens: 'order state, inventory source, customer promise, payment evidence, and exception authority', scenario: 'an address correction, stock mismatch, late shipment, duplicate order, and return outside the usual window', finding: 'exception volume describes friction in the system, not the quality of the person handling the queue', limitation: 'a single sales period cannot predict seasonal demand or prove that a policy is appropriate', sources: [{ label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { label: 'FTC: Mail, Internet, or Telephone Order Merchandise Rule', href: 'https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule' }] },
  { slug: 'philippines-outsourcing-project-status-lineage', title: 'Project-status lineage in Philippines outsourcing', excerpt: 'A research model for keeping outsourced project coordination updates traceable to decisions, owners, and dated source evidence.', question: 'When does a project status update remain a useful observation rather than becoming an unsupported forecast?', unit: 'milestones and dependencies reported across a fixed project status cycle', lens: 'source timestamp, owner confirmation, dependency state, decision record, and uncertainty', scenario: 'a completed milestone, a late dependency, a blocked task, an optimistic estimate, and a status copied from a prior week', finding: 'a status color compresses information; it does not replace the dated evidence and owner decision behind the color', limitation: 'status records show reported conditions and may miss work that was never logged or escalated', sources: [{ label: 'PMI: Pulse of the Profession', href: 'https://www.pmi.org/learning/thought-leadership/pulse' }, { label: 'NIST Risk Management Framework', href: 'https://csrc.nist.gov/projects/risk-management/about-rmf' }] },
  { slug: 'philippines-outsourcing-spreadsheet-reconciliation', title: 'Spreadsheet-reconciliation evidence in Philippines outsourcing', excerpt: 'Research on reconciling operational spreadsheets while preserving source lineage and keeping adjustments with the data owner.', question: 'What does a reconciliation prove when two operational files disagree, and what does it leave unresolved?', unit: 'rows matched between two named extracts from the same reporting period', lens: 'extract time, key definition, unmatched rows, transformations, and adjustment approval', scenario: 'a clean match, a duplicate key, a late-arriving row, a changed label, and a value overwritten without a source note', finding: 'a reconciled total can hide incompatible populations unless the keys, exclusions, and transformations remain visible', limitation: 'a spreadsheet comparison cannot prove the completeness or correctness of either source system', sources: [{ label: 'NIST Data Integrity', href: 'https://csrc.nist.gov/publications/detail/sp/800-57-part-1/rev-5/final' }, { label: 'OECD Glossary of Statistical Terms', href: 'https://stats.oecd.org/glossary/' }] },
  { slug: 'philippines-outsourcing-accessibility-document-review', title: 'Accessibility-document review in Philippines outsourcing', excerpt: 'What a bounded outsourced document review can reveal about accessibility barriers without pretending to certify every user experience.', question: 'Which document-level signals are useful for triage, and which require specialist or user evaluation?', unit: 'documents or templates sampled by format, audience, and publication status', lens: 'heading structure, reading order, contrast, alternative text, language, and remediation ownership', scenario: 'a text document, a scanned PDF, a form, a slide deck, and a file with a decorative image described as essential', finding: 'automated or desk-based checks can identify candidates for remediation, but they do not establish accessibility for all users', limitation: 'a limited file sample cannot certify a library, product, legal duty, or individual accommodation', sources: [{ label: 'W3C Web Content Accessibility Guidelines 2.2', href: 'https://www.w3.org/TR/WCAG22/' }, { label: 'U.S. Section 508: Document Accessibility', href: 'https://www.section508.gov/create/documents/' }] },
  { slug: 'philippines-outsourcing-supplier-record-change', title: 'Supplier-record change research for Philippines outsourcing', excerpt: 'Evidence-led analysis of how an outsourced vendor-administration role can flag changes without approving bank, contract, or ownership decisions.', question: 'How can a supplier record change be detected and routed without treating a changed field as proof of fraud?', unit: 'supplier records changed during a defined review period, grouped by field and source', lens: 'change provenance, requester identity, effective date, duplicate indicators, and approval owner', scenario: 'a new contact, a bank-detail change, a legal-name change, a duplicate supplier, and a request from an unrecognized address', finding: 'change detection is valuable because it creates a review signal; it is not itself an investigation or a finding of wrongdoing', limitation: 'public registries and internal records may be incomplete, delayed, or based on different entity definitions', sources: [{ label: 'NIST SP 800-161 Rev. 1', href: 'https://csrc.nist.gov/pubs/sp/800/161/r1/upd1/final' }, { label: 'ACFE: Occupational Fraud 2024', href: 'https://www.acfe.com/fraud-resources/report-to-the-nations' }] },
  { slug: 'philippines-outsourcing-customer-survey-coding', title: 'Customer-survey coding in Philippines outsourcing', excerpt: 'Research on coding open-text survey responses while separating descriptive categories from claims about customer sentiment or causation.', question: 'What can a coded response set tell an operations owner, and when does interpretation outrun the sample?', unit: 'responses received through each named channel during a stated survey period', lens: 'question wording, duplicate responses, missingness, coding agreement, and sampling frame', scenario: 'a direct answer, a multi-topic answer, sarcasm, an empty response, and a comment containing personal information', finding: 'coding makes themes visible, but response counts are not automatically representative of the customer population', limitation: 'voluntary responses, translation, small cohorts, and changing survey questions constrain inference about sentiment or causes', sources: [{ label: 'AAPOR Transparency Initiative', href: 'https://aapor.org/standards-and-ethics/transparency-initiative/' }, { label: 'Pew Research Center: Writing Survey Questions', href: 'https://www.pewresearch.org/methods/u-s-survey-research/questionnaire-design/' }] },
];

function body(t: Topic): string[] {
  return [
    `Research question: ${t.question} This is a question about a bounded Philippines-based outsourcing role, not a claim that a country, provider, or worker produces one universal result. The relevant decision is whether a defined queue can be prepared for review with enough evidence for the internal owner to act. The unit is ${t.unit}. Naming the unit prevents a polished percentage from hiding the population it describes.`,
    `Evidence scope and method: examine a frozen source snapshot, a redacted or synthetic work sample, the written authority boundary, and a sample of later records where available. For this topic, inspect ${t.lens}. Separate observations from interpretations. Record the period, inclusion rules, exclusions, source version, reviewer, and unresolved cases. Public sources provide concepts or context; they do not certify a particular company or operational lane.`,
    `The first design question is what enters the queue. Write the event that creates work, the system that is authoritative, the fields that are required, and the time at which an item becomes overdue. If the source is incomplete, the safe result is a visible exception rather than a guessed value. This matters in ${t.title.toLowerCase()} because ${t.finding.toLowerCase()}. A role that cannot explain its source should not silently convert uncertainty into a completed record.`,
    `Use a bounded work sample containing ${t.scenario}. The purpose is not to test how quickly someone can produce a polished answer. Ask the reviewer to identify the source, state the action permitted, preserve the relevant evidence, and stop at the point where an owner must decide. A careful escalation is positive evidence when the facts do not support an answer. Live customer, payment, candidate, or security records are unnecessary for this test.`,
    `The role boundary should be written beside the measure. A Philippines-based operations specialist may classify, compare, prepare, update an approved field, or route an exception when the rule is clear. The internal owner retains policy changes, material approvals, legal interpretations, sensitive access changes, and decisions that depend on missing evidence. In this case, the boundary is especially important because ${t.lens} can inform a review without authorizing its conclusion.`,
    `Measure the work with a denominator and a reason code. Count the items reviewed, complete on first pass, returned for missing evidence, escalated, and corrected later. Report the cohort and period. Then distinguish a source defect from a rule defect, transcription error, access problem, owner delay, and genuine exception. A single completion percentage cannot show which cause should be repaired. If the queue changes, split the cohorts instead of comparing unlike work.`,
    `The external evidence should be used precisely. The cited material may describe privacy, security, research transparency, time, accessibility, supply-chain, or project-risk principles. It may use a different jurisdiction, population, definition, or period. Treat it as a reason to ask a better question, not as proof that a proposed control operated. Keep the source link, publication context, and claim it supports next to the research note so a later owner can challenge the interpretation.`,
    `A useful finding has a practical consequence and a boundary. Here, ${t.finding}. That conclusion supports a narrower staffing decision: define the queue, test the failure modes, protect the source, and name the person who resolves ambiguity. It does not establish individual capability, legal compliance, customer satisfaction, fraud, or a guaranteed business outcome. Avoid turning an operational signal into a judgment about a person or a population.`,
    `Continuity is part of evidence quality. A second authorized person should be able to identify the current source, open items, exceptions, owner, and safe fallback without receiving permanent broad access. Test one interruption using the same redacted packet. Record where the handoff loses context, which timestamp or version is missing, and who can restore the authoritative state. A queue that only works from one person’s memory is not yet a well-defined outsourcing candidate.`,
    `Interpret the result at the level of the queue, not the country label. A Philippines-based role may be well matched to a defined process, but public evidence about the Philippines workforce cannot predict this role's accuracy, judgment, schedule, or retention. Compare the proposed work sample, training evidence, review load, and escalation behavior with the actual task. If the evidence is mixed, preserve that mixed result instead of smoothing it into a provider score.`,
    `The owner should state what would change the conclusion. A new source, field, policy, channel, manager, or volume threshold can invalidate a prior baseline. Put those triggers beside the record and assign a person to review them. This matters when the visible output stays stable while the underlying population or authority changes. A stable number can conceal a changing process.`,
    `A useful handoff note is short but reconstructable. It identifies the item, source checked, action taken, rule applied, uncertainty remaining, next owner, and response deadline. It does not copy unnecessary personal information or claim that an exception is resolved when it has merely been routed. Review whether another authorized person could continue without asking the original operator to explain the record from memory.`,
    `The safest expansion is incremental. Begin with one queue and a review sample that the internal owner can actually inspect. Add a second category only after the first has a stable definition, source, access boundary, and exception path. When a new category needs different judgment or data, treat it as a new research question. Do not let a narrow success become an automatic license for broad work.`,
    `These findings support a buying and operating conversation. They are not a performance guarantee, legal opinion, audit report, or substitute for the company's own records. Keep the underlying source, date, unit, and reviewer with the decision. That gives the next manager a way to challenge the conclusion and improve the queue rather than inheriting an unsupported claim.`,
    `Review privacy and access at field level. Collect only what the task needs, mask identifiers where possible, and keep copies, exports, shared folders, and integrations within the owner’s map. Do not use free text as a substitute for a missing structured field if it creates unnecessary exposure. When the work touches regulated data, money, employment, safety, or legal rights, send the actual facts to the appropriate qualified adviser. The article is an evidence framework, not professional advice.`,
    `Limitations: ${t.limitation}. In addition, a small sample can be easier or harder than ordinary demand; public data can be stale; and a changed tool or policy can break a previously valid comparison. State the period, cohort, source version, and assumptions in every result. Repeat the review after a meaningful change rather than presenting a one-time observation as a permanent benchmark.`,
    `Conclusion: the evidence should answer whether this specific queue is defined well enough for a controlled staffing decision. Start with the source and the owner, test ${t.scenario.split(',')[0].toLowerCase()}, measure causes as well as output, and preserve cases that should stop. If the evidence remains ambiguous, narrow the role or improve the source before expanding it. That is a more defensible conclusion than a generic claim that outsourcing, speed, or volume is inherently better.`,
  ];
}

export const researchPosts2026_08_17: ResearchPost[] = topics.map((t, index) => ({ slug: t.slug, title: t.title, excerpt: t.excerpt, updated: ['2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17'][index], datePublished: ['2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17', '2026-08-17'][index], image, imageAlt, body: body(t), sources: t.sources, related, cta }));
