type Topic = { slug: string; title: string; excerpt: string; audience: string; deliverable: string; inputs: string; stop: string; exception: string; metrics: string };

const topics: Topic[] = [
  { slug: 'refund-request-preparation', title: 'Refund-request preparation for Philippines outsourcing', excerpt: 'Prepare refund requests for an authorized decision without letting speed override policy, evidence, or customer history.', audience: 'customer experience and finance operations leaders', deliverable: 'a decision packet with the order, request reason, policy version, prior remedies, evidence, amount, and approving owner', inputs: 'the customer message, order record, payment record, active refund policy, and earlier case history', stop: 'approving or issuing a refund, promising an outcome, or changing the policy', exception: 'the customer requests a refund after a partial credit was issued under an older policy', metrics: 'complete packets, owner returns, duplicate remedies, policy-version mismatches, and decision time' },
  { slug: 'crm-duplicate-review', title: 'CRM duplicate review for Philippines outsourced teams', excerpt: 'Review possible duplicate records while protecting attribution, activity history, consent, and record-owner decisions.', audience: 'revenue operations and sales administration managers', deliverable: 'a duplicate-review record identifying candidate records, matching fields, conflicts, activity history, owner, and recommended next step', inputs: 'the CRM records, source forms, account hierarchy, consent history, and approved matching rules', stop: 'merging or deleting records, changing ownership, or resolving disputed attribution', exception: 'two contacts share an email domain but belong to separate subsidiaries with active opportunities', metrics: 'confirmed duplicates, false candidates, history preserved, owner corrections, and unresolved conflicts' },
  { slug: 'purchase-order-match-queue', title: 'Purchase-order match queues for Philippines outsourcing', excerpt: 'Compare invoices, receipts, and purchase orders without transferring payment or accounting authority.', audience: 'accounts payable and procurement leaders', deliverable: 'a match packet showing line-level agreement, tolerances, missing evidence, exception reason, and decision owner', inputs: 'the approved purchase order, supplier invoice, receipt, contract terms, and tolerance rule', stop: 'approving payment, changing a purchase order, assigning tax treatment, or accepting an exception', exception: 'an invoice combines a received item with a freight charge absent from the purchase order', metrics: 'first-pass matches, exception causes, missing receipts, repeated supplier variance, and owner turnaround' },
  { slug: 'candidate-interview-scheduling', title: 'Candidate interview scheduling in Philippines outsourced operations', excerpt: 'Coordinate interviews with clear consent, availability, accessibility, and hiring-manager boundaries.', audience: 'talent acquisition and people operations teams', deliverable: 'a scheduling record with candidate consent, interviewer availability, time zone, format, accessibility needs, and confirmation status', inputs: 'the applicant record, approved interview stage, calendar availability, scheduling guidance, and candidate messages', stop: 'evaluating candidates, changing interview stages, asking prohibited questions, or promising employment terms', exception: 'a candidate requests an accommodation while the assigned interviewer is unavailable', metrics: 'confirmation time, reschedules by cause, time-zone errors, accessibility handoffs, and missing approvals' },
  { slug: 'subscription-termination-request-verification', title: 'Subscription-termination request verification for Philippines outsourcing', excerpt: 'Verify termination requests accurately while keeping retention offers, refunds, and account changes within authority.', audience: 'subscription and customer operations managers', deliverable: 'a verification record with confirmed account, request channel, effective-date request, stated reason, open balance, and authorized route', inputs: 'the customer request, account record, current termination terms, billing status, and approved response guide', stop: 'changing contractual terms, issuing credits, obstructing termination, or inventing a retention offer', exception: 'the request arrives one day before renewal but identity verification is incomplete', metrics: 'record completeness, effective-date corrections, verification holds, unauthorized offers, and reopen rate' },
  { slug: 'product-return-inspection-records', title: 'Product-return inspection records for Philippines outsourcing', excerpt: 'Turn warehouse observations into reviewable return evidence without deciding warranty, fault, or write-off.', audience: 'ecommerce, warehouse, and quality managers', deliverable: 'an inspection record with item identity, condition observations, photographs already in the approved system, package state, receipt time, and owner route', inputs: 'the return authorization, order, warehouse scan, approved condition vocabulary, and existing product records', stop: 'deciding fault, approving a refund, changing inventory value, or making a warranty determination', exception: 'the returned serial number differs from the authorization but the packaging matches the order', metrics: 'identity mismatches, complete observations, classification corrections, aged holds, and owner decisions' },
  { slug: 'executive-travel-change-log', title: 'Executive travel change logs for Philippines outsourced support', excerpt: 'Record itinerary changes and approvals without purchasing outside limits or exposing unnecessary personal data.', audience: 'executive administration and travel operations managers', deliverable: 'a change log with traveler confirmation, itinerary version, supplier terms, cost difference, approval state, and next deadline', inputs: 'the approved itinerary, traveler instruction, supplier terms, company travel policy, and booking record', stop: 'accepting a fare change above authority, altering identity data, choosing policy exceptions, or making an unapproved purchase', exception: 'a cancelled flight leaves one compliant option that exceeds the written approval limit', metrics: 'version accuracy, missed deadlines, approval holds, avoidable fees, and traveler corrections' },
  { slug: 'knowledge-base-retirement', title: 'Knowledge-base retirement controls for Philippines outsourcing', excerpt: 'Retire obsolete guidance without breaking links, losing decision history, or letting drafts masquerade as policy.', audience: 'support enablement and knowledge management leaders', deliverable: 'a retirement packet naming the article, replacement, affected links, owner approval, archive location, and effective time', inputs: 'the published article, content inventory, replacement guidance, link report, change request, and owner decision', stop: 'declaring policy obsolete, publishing replacement guidance, or deleting required records', exception: 'an old article remains linked from a live macro after its replacement has been approved', metrics: 'obsolete exposure, broken references, owner-approved retirements, rollback events, and search misses' },
  { slug: 'sales-quote-data-check', title: 'Sales-quote data checks for Philippines outsourcing', excerpt: 'Check quote inputs and approval evidence while keeping pricing, discount, and contractual decisions with named owners.', audience: 'sales operations and deal-desk managers', deliverable: 'a preflight record with customer identity, products, quantities, price source, discount request, terms, and approval state', inputs: 'the opportunity, approved price book, product configuration, discount matrix, tax inputs, and contract template', stop: 'setting price, approving a discount, changing legal terms, or sending an unapproved quote', exception: 'a renewal uses a legacy product code that is absent from the current price book', metrics: 'preflight completeness, price-source conflicts, approval returns, version errors, and quote corrections' },
  { slug: 'maintenance-request-triage', title: 'Maintenance-request triage for Philippines outsourced teams', excerpt: 'Route facilities requests by written safety and service rules without making technical or emergency judgments.', audience: 'facilities and workplace operations managers', deliverable: 'a triage record with location, requester, observed condition, access constraints, safety keywords, priority rule, and assigned owner', inputs: 'the request, site directory, active triage guide, vendor coverage, and prior work order', stop: 'diagnosing a hazard, authorizing spend, directing emergency response, or closing disputed work', exception: 'a routine leak report mentions an electrical odor after normal facilities coverage ends', metrics: 'correct routing, safety escalations, missing location data, duplicate work orders, and owner response' },
  { slug: 'campaign-list-suppression-check', title: 'Campaign-list suppression checks for Philippines outsourcing', excerpt: 'Check marketing lists against approved consent and suppression evidence before an authorized launch.', audience: 'marketing operations and privacy leaders', deliverable: 'a prelaunch evidence record with audience source, consent basis, suppression version, exclusions, conflicts, and release owner', inputs: 'the audience export, consent records, current suppression lists, campaign brief, and channel rules', stop: 'deciding legal basis, overriding a suppression, adding an unverified contact, or launching the campaign', exception: 'a recently unsubscribed contact appears in a cached audience generated before the request', metrics: 'suppression matches, source conflicts, stale exports, owner holds, and post-launch complaints' },
  { slug: 'weekly-capacity-forecast', title: 'Weekly capacity forecasts for Philippines outsourced operations', excerpt: 'Build a transparent workload forecast from known demand, coverage, and queue assumptions rather than false precision.', audience: 'delivery and workforce planning leaders', deliverable: 'a weekly forecast listing demand inputs, work classes, handling assumptions, coverage, constraints, scenarios, and owner decisions', inputs: 'recent queue history, staffing schedule, known events, service targets, backlog, and approved planning assumptions', stop: 'committing service levels, changing schedules, directing overtime, or presenting estimates as guaranteed outcomes', exception: 'a promotion may double demand but its launch date and audience remain unconfirmed', metrics: 'forecast error by class, assumption changes, uncovered intervals, backlog movement, and decision latency' },
];

const sections = (t: Topic) => [
  { heading: 'Specify the handoff', body: [`For ${t.audience}, the reviewable output is ${t.deliverable}. A narrow artifact lets a Philippines-based specialist prepare useful work while the accountable owner can inspect what happened.`, `Start with a small set of recent normal and exception cases. Mark every required field, acceptable source, due window, and completion state before opening the live queue.`] },
  { heading: 'Use controlling evidence', body: [`Anchor each record to ${t.inputs}. Store a source identifier and version or timestamp wherever the system permits.`, `When sources disagree, preserve both values and route the conflict. Do not silently select the value that makes the case easiest to close.`] },
  { heading: 'Write the authority boundary', body: [`The specialist may collect, compare, classify, draft, and route under the approved procedure. The role stops before ${t.stop}.`, `Put the stop rule beside the working template and name a primary and backup decision owner. An unanswered escalation remains a hold, not implied permission.`] },
  { heading: 'Rehearse an exception', body: [`Test this case before scaling: ${t.exception}. The correct response should preserve the evidence, apply a neutral hold reason, and ask the owner one specific question.`, `Record how the case is returned after a decision so the queue does not lose context or create a parallel side channel.`] },
  { heading: 'Review outcomes with denominators', body: [`Track ${t.metrics}. Report the number reviewed and the population it represents, then separate corrections caused by instructions, sources, tools, handoffs, and execution.`, `Speed is useful only beside evidence quality and boundary compliance. A correctly held case can take longer than an incorrectly closed one.`] },
  { heading: 'Launch the routine', body: [`In week one, document examples and score practice cases. In week two, run a limited live batch under full review. In week three, reduce review only for stable case types. In week four, inspect access, corrections, holds, and owner capacity.`, `Published September 1, 2026, this guide supports a controlled operating routine for OutsourcedCompany.com readers. It does not transfer policy or consequential decisions to the outsourced role.`] },
];

export const blogPosts2026_09_01 = topics.map((t, i) => ({ slug: `philippines-outsourcing-${t.slug}`, title: t.title, excerpt: t.excerpt, minutes: 10 + (i % 3) }));
export const blogDetails2026_09_01 = Object.fromEntries(topics.map(t => [`philippines-outsourcing-${t.slug}`, {
  updated: '2026-09-01', marker: 'daily-blog-2026-09-01', takeaway: `${t.excerpt} Use a named internal owner for decisions outside the written procedure.`,
  comparison: [{ weak: 'Handle the routine cases and use judgment on the rest.', strong: 'Follow the stated sources and stop rules; hold and route anything outside them.' }, { weak: 'Escalate if something looks wrong.', strong: 'Record the conflicting evidence, choose the named reason, and ask the assigned owner one question.' }],
  sections: sections(t), script: ['Which approved source controls this queue, and how is its version recorded?', `Where does the specialist stop before ${t.stop}?`, 'Who responds when the primary decision owner is unavailable?'],
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', note: 'Governance and control context.', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { name: 'Philippine National Privacy Commission: Data Privacy Act', note: 'Primary Philippine privacy resource.', url: 'https://privacy.gov.ph/data-privacy-act/' }],
  faqs: [{ question: 'Can the outsourced specialist resolve exceptions?', answer: `Only within an explicitly approved rule. The role stops before ${t.stop}.` }, { question: 'What should managers review first?', answer: `Review source traceability, boundary compliance, owner returns, and ${t.metrics}.` }],
} ]));
