type T={slug:string;title:string;audience:string;artifact:string;boundary:string;exception:string};
const topics:T[]=[
['refund-evidence-timeline','Trace a refund request without promising the outcome','customer experience leads','a timeline linking request, order, payment, policy, messages, status, and owner','approve money, promise timing, or close a dispute','support says approved but the processor has no transaction'],
['warehouse-shortage-packet','Turn a warehouse shortage into a reviewable packet','ecommerce managers','a packet joining order, scans, count, photos, carrier handoff, and owner','adjust stock, assign blame, issue credit, or settle a claim','the final scan and physical count disagree'],
['calendar-conflict-brief','Resolve executive calendar conflicts with a decision brief','executive support managers','a brief listing commitments, sources, participants, buffers, constraints, and options','cancel, disclose private context, or accept for the executive','a board call overlaps a customer meeting'],
['crm-consent-audit-queue','Build a CRM consent-audit queue that preserves provenance','revenue operations leaders','a queue linking contact, collection source, timestamp, purpose, suppression, and owner','infer consent, erase history, or launch outreach','an import has a campaign source but no original form'],
['supplier-bank-change-hold','Hold supplier bank-detail changes at the right boundary','accounts payable managers','a hold with vendor ID, request channel, known contact route, changed fields, and verifier','replace bank details, release funds, or bypass verification','an urgent request uses a familiar name from a new domain'],
['candidate-document-intake','Keep candidate document intake separate from hiring judgment','recruiting operations teams','a register of document, stage, receipt, access class, missing item, and retention rule','judge a candidate, infer protected facts, or change stage','an unsolicited medical document arrives early'],
['customer-onboarding-dependency-map','Map customer onboarding dependencies before launch','implementation managers','a map of deliverables, prerequisites, owners, dates, evidence, and fallback paths','commit a date, waive prerequisites, or change scope','configuration is done but source data is unapproved'],
['expense-report-precheck','Precheck expense reports without deciding reimbursement','finance operations leads','a checklist joining each line to receipt, currency, policy, approval, and discrepancy','approve reimbursement, change amounts, or waive evidence','a hotel folio mixes personal charges and currency conversion'],
['support-macro-change-record','Control support-macro changes with a reviewable record','support enablement managers','a record of current and proposed text, reason, source, queues, tests, and publisher','invent policy, approve legal wording, or publish','shorter text omits an exception for one customer segment'],
['subscription-entitlement-reconciliation','Reconcile subscription entitlements before customer contact','subscription operations teams','a reconciliation of contract, billing, access, amendments, effective dates, and variance','change access, amend terms, bill, or credit','an amendment expands seats while systems retain the old quantity'],
['field-service-photo-index','Index field-service evidence without turning photos into conclusions','service delivery managers','an index linking job, time, technician, location, photo, checklist, and reviewer','diagnose, certify completion, infer conduct, or disclose location','a photo predates dispatch while the note says arrival'],
['monthly-metric-change-log','Publish a metric change log before dashboard refresh','operations analytics managers','a log of definition, query, source, period, exclusions, backfill, and reviewer','redefine a KPI, hide a break, overwrite history, or publish','a migration changes status names midway through the month'],
].map(([slug,title,audience,artifact,boundary,exception])=>({slug,title,audience,artifact,boundary,exception}));
const sections=(t:T)=>[
 {heading:'Build a record another person can reopen',body:[`For ${t.audience}, prepare ${t.artifact}. Link every material field to a system event, approved document, or attributable message.`,`Test required fields and acceptable blanks on one ordinary record before live work.`]},
 {heading:'Turn the authority boundary into a queue state',body:[`The specialist may collect, compare, label, draft, and route. They stop before they ${t.boundary}.`,'Name the hold state, primary owner, backup, and return path. Silence leaves work held; it never grants authority.']},
 {heading:'Keep contradictions visible',body:[`Rehearse this case: ${t.exception}. Preserve both accounts, their identifiers, and timestamps; then ask the smallest question needed to continue.`,'Never replace the original after correction. The change history is part of the evidence.']},
 {heading:'Measure the eligible queue',body:['Retain the denominator and count complete items, source gaps, conflicts, wrong routes, owner returns, aged holds, corrections, and reopenings.','Read speed beside evidence quality and boundary compliance. A justified hold can be safer than a quick unsupported closure.']},
 {heading:'Release a narrow first batch',body:['Practice on historical items, then inspect every record in a limited live batch. Expand only after source, hold, return, and correction paths work.','Published September 8, 2026, this OutsourcedCompany.com guide is an operating pattern, not legal, financial, employment, privacy, or security advice.']},
];
export const blogPosts2026_09_08=topics.map((t,i)=>({slug:`philippines-outsourcing-${t.slug}`,title:t.title,excerpt:`A Philippines outsourcing routine for ${t.title.toLowerCase()}, with source evidence, authority limits, and owner review.`,minutes:9+(i%4)}));
export const blogDetails2026_09_08=Object.fromEntries(topics.map(t=>[`philippines-outsourcing-${t.slug}`,{updated:'2026-09-08',marker:`daily-blog-2026-09-08-${t.slug}`,takeaway:`Prepare ${t.artifact}. Keep consequential judgment with a named internal owner.`,comparison:[{weak:'Use common sense and finish the case.',strong:'Follow the named source, retain contradictions, and stop at the documented boundary.'},{weak:'Message someone if it seems unusual.',strong:'Use the defined hold and route one precise question with evidence.'}],sections:sections(t),script:['Which source governs, and how is its version proved?',`Where must the role stop before it can ${t.boundary}?`,'Who owns the hold, provides backup, and records the returned decision?'],sources:[{name:'NIST Cybersecurity Framework 2.0',note:'Primary governance and control framework.',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'},{name:'Philippine National Privacy Commission: Data Privacy Act',note:'Primary Philippine privacy resource.',url:'https://privacy.gov.ph/data-privacy-act/'}],faqs:[{question:'May the specialist decide the exception?',answer:`Only under an explicit current rule; otherwise stop before they ${t.boundary}.`},{question:'What should the owner inspect first?',answer:'Check the controlling source, identifiers, conflicts, hold reason, and correction history.'}]}]));
