type Topic = { slug: string; title: string; excerpt: string; audience: string; output: string; evidence: string; boundary: string; edge: string; measure: string };

const topics: Topic[] = [
  ['shared-inbox-ownership','Shared-inbox ownership','Turn a crowded inbox into an owned queue with response, escalation, and closure rules.','customer operations leaders','a queue map naming the owner, backup, due window, permitted response, and closure evidence','the original message, customer record, current response guide, and case history','promising a remedy, changing an account, or closing a disputed request','a customer adds a new billing question to an old thread while the owner is offline','unowned age, first-touch accuracy, reopen rate, and complete escalations'],
  ['meeting-action-register','Meeting-action registers','Convert meeting notes into traceable actions without inventing commitments.','project and executive operations managers','an action register with the decision, owner, due date, dependency, source time, and confirmation state','the approved agenda, recording or notes, decision log, and owner corrections','assigning an unwilling owner, changing scope, or interpreting silence as consent','two attendees remember a due date differently and no final confirmation was recorded','owner-confirmed actions, overdue reasons, corrections, and source gaps'],
  ['customer-data-correction-intake','Customer-data correction intake','Route correction requests while protecting identity, consent, and system-owner authority.','privacy and customer data teams','a packet recording the requester, verification state, disputed field, systems affected, and next owner','the customer request, identity procedure, system record, consent record, and retention rule','deciding identity, changing consent, deleting records, or declaring a privacy request complete','a requester changes an email address that is also the account login','complete intake, verification holds, affected systems, and corrections by cause'],
  ['supplier-onboarding-records','Supplier-onboarding records','Prepare supplier records with a clean separation between administration and approval.','procurement and finance operations teams','a readiness packet covering identity, documents, exceptions, and approving owner','the supplier submission, vendor standard, contract, tax form, and verified payment channel','approving a supplier, accepting terms, changing bank details, or deciding tax treatment','revised bank details arrive from a new email shortly before first payment','first-pass completeness, bank-change holds, duplicates, and owner-returned exceptions'],
  ['content-approval-queues','Content-approval queues','Keep drafts moving with visible claims, reviewers, and publication gates.','marketing and communications managers','an approval packet pairing material claims with sources, audience, reviewer, status, and slot','the brief, approved facts, brand guide, legal guidance, and channel requirements','inventing proof, approving regulated claims, or publishing without authorization','a late product change invalidates a claim after scheduling','review cycles, unsupported claims, post-approval changes, and missing authorization'],
  ['referral-lead-routing','Referral-lead routing','Route referrals quickly while preserving attribution, consent, and sales ownership.','revenue operations leaders','a referral record with source, consent, duplicate check, routing rule, owner, and next action','the referral form, partner record, CRM history, territory rule, and consent language','qualifying by intuition, promising terms, changing ownership, or contacting without permission','two partners claim the same lead while an opportunity is already open','routing accuracy, duplicates, consent holds, acceptance time, and attribution corrections'],
  ['training-completion-evidence','Training-completion evidence','Prove required training reached the right people without confusing attendance with competence.','operations, compliance, and enablement managers','a register linking module version, learner, completion, practical check, expiry, and exception owner','the role matrix, active course, attendance, assessment, and exception process','certifying competence from attendance, altering scores, or waiving mandatory training','a worker completed the prior module before a material procedure change','current coverage, overdue work, version mismatches, practical checks, and exceptions'],
  ['service-request-catalog','Service-request catalogs','Define request types, required evidence, and owner routes before adding volume.','shared-services managers','a catalog with entry criteria, fields, priority, permitted steps, target, stop condition, and owner','service policies, ticket samples, system capabilities, owner interviews, and exception history','creating policy, treating urgency as authority, granting access, or resolving outside the catalog','an urgent request fits no entry and asks for a restricted permission','misroutes, missing-field holds, attainment by class, reopens, and catalog gaps'],
  ['inventory-adjustment-preparation','Inventory-adjustment preparation','Reconcile inventory evidence before an authorized owner posts an adjustment.','ecommerce and warehouse leaders','a packet showing item, location, ledger and count values, movements, reason, and decision','the warehouse count, inventory ledger, receipts, shipments, returns, and adjustment policy','posting an adjustment, assigning blame, writing off stock, or changing finance records','an unposted return and in-transit transfer affect the same discrepant item','complete packets, repeats, corrections, aged holds, and prevented adjustments'],
  ['contract-obligation-calendar','Contract-obligation calendars','Track dates and evidence while keeping interpretation with authorized owners.','legal operations, procurement, and account managers','a calendar linked to the controlling document, clause, owner, notice window, and evidence','the executed agreement, amendment, owner interpretation, notice, and delivery evidence','interpreting clauses, giving legal advice, sending binding notice, or accepting terms','an amendment changes a renewal window but the old date remains in a spreadsheet','verified sources, upcoming reviews, missed evidence, superseded clauses, and holds'],
  ['quality-calibration-sessions','Quality-calibration sessions','Make reviewer disagreement visible and turn it into clearer scoring guidance.','quality assurance and delivery managers','a record with blinded samples, independent scores, disagreements, rulings, and effective dates','the active rubric, original work, case evidence, reviewer notes, and owner decision','changing production outcomes, manipulating samples, or treating one session as proof of bias','one reviewer uses an undocumented exception from an earlier project','agreement by criterion, ambiguity, correction direction, rubric changes, and held-out results'],
  ['offboarding-access-handoff','Offboarding access handoffs','Coordinate access removal and record transfer without relying on memory or shared credentials.','people operations, security, and delivery leaders','a checklist tied to identity, systems, removal owner, effective time, handoff, and verification','the departure notice, identity directory, access inventory, confirmations, and retention plan','deleting records, transferring personal accounts, changing departure terms, or assuming removal','a departing coordinator owns recurring events and automations under an individual account','removal by risk tier, orphaned ownership, late discoveries, failures, and exceptions'],
].map(([slug,label,excerpt,audience,output,evidence,boundary,edge,measure]) => ({ slug: `philippines-outsourcing-${slug}`, title: `${label} for Philippines outsourcing`, excerpt, audience, output, evidence, boundary, edge, measure })) as Topic[];

const sections = (t: Topic) => [
  { heading: 'Define a reviewable work product', body: [`For ${t.audience}, the useful output is ${t.output}. This gives a Philippines-based specialist something observable to prepare and the internal owner something consistent to review. It prevents a broad request to “handle it” from becoming an invisible transfer of judgment.`, `Start with recent ordinary, incomplete, conflicting, duplicate, and urgent cases. Write the entry rule and stopping point beside each. On August 31, 2026, approve the smallest live queue that can be traced from source to owner decision.`] },
  { heading: 'Anchor updates to evidence', body: [`The record should point to ${t.evidence}. Include source time and version. If two approved sources disagree, retain both values and route the conflict instead of choosing the convenient one.`, `Use named accounts and least privilege. Keep sensitive fields in approved systems and record corrections without erasing history. Exceptions are healthy evidence when they remain visible and owned.`] },
  { heading: 'Separate preparation from authority', body: [`The outsourced role may gather, compare, classify, draft, schedule, and route within the written procedure. It must stop before ${t.boundary}. Put that boundary in the live template, not only in training material.`, `The internal owner remains accountable for policy and consequential decisions. A useful handoff states what was observed, what is uncertain, and the exact decision requested.`] },
  { heading: 'Test the exception path', body: [`Test this scenario before expanding: ${t.edge}. The specialist should preserve evidence, select a neutral hold reason, and send one owner question. The procedure must identify a reachable backup or an honest holding response.`, `Review uncategorized cases weekly and turn recurring patterns into named reasons. Do not let an “other” label become a second unmanaged queue.`] },
  { heading: 'Measure the control, not activity', body: [`Track ${t.measure}. Show counts and denominators. Review corrections by cause: unclear rule, missing source, tool limitation, training gap, or action outside the boundary.`, `Pair speed with evidence quality. A short handling time can conceal premature closure, while a correct owner hold may take longer. Compare shifts only when case mix and coverage are visible.`] },
  { heading: 'Run a bounded first month', body: [`Week one documents and scores examples. Week two uses a small live batch with full owner review. Week three reduces review only for stable categories. Week four inspects corrections, access, and unresolved holds before expansion.`, `The result is a routine, not a promise that outsourcing removes management. Philippines outsourcing works when preparation authority is useful, consequential decisions stay internal, and both sides can reconstruct why a case moved.`] },
];

export const blogPosts2026_08_31 = topics.map((t, i) => ({ slug: t.slug, title: t.title, excerpt: t.excerpt, minutes: 10 + i % 3 }));
export const blogDetails2026_08_31 = Object.fromEntries(topics.map(t => [t.slug, { updated: '2026-08-31', marker: 'daily-blog-2026-08-31', takeaway: `${t.excerpt} Preserve evidence and keep consequential decisions with the named internal owner.`, comparison: [{ weak: 'Use your judgment and clear it.', strong: 'Follow the written evidence and stop rules; route anything outside them.' }, { weak: 'Escalate anything unusual.', strong: 'Attach the conflict, select a named reason, and ask one owner question.' }], sections: sections(t), script: ['Which source controls this case, and how will the specialist record its version?', `Where must the role stop before ${t.boundary}?`, 'Who owns the decision when evidence conflicts or the primary owner is unavailable?'], sources: [{ name: 'NIST Cybersecurity Framework 2.0', note: 'Governance and control context.', url: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, { name: 'Philippine National Privacy Commission: Data Privacy Act', note: 'Primary Philippine privacy-law resource.', url: 'https://privacy.gov.ph/data-privacy-act/' }], faqs: [{ question: 'Can the specialist approve exceptions?', answer: `No. The role stops before ${t.boundary} and routes the evidence.` }, { question: 'What should the first review inspect?', answer: `Inspect traceability, boundary compliance, corrections, and ${t.measure}.` }] }]));
