type Topic={slug:string;title:string;audience:string;artifact:string;boundary:string;exception:string};
const topics:Topic[]=[
['shared-inbox-ownership-map','Build a shared-inbox ownership map','customer operations managers','a queue map naming the owner, backup, response window, evidence source, and permitted disposition','send a consequential reply, promise a remedy, or change policy','a billing complaint also contains a credible account-security concern'],
['invoice-dispute-evidence-pack','Prepare invoice-dispute evidence packs','finance operations leaders','a packet linking the invoice, purchase order, receipt, contract version, correspondence, and decision owner','approve payment, accept liability, change an entry, or negotiate','the quantity matches but a surcharge is absent from the signed agreement'],
['product-catalog-change-preflight','Run a product-catalog change preflight','ecommerce teams','a preflight record covering field changes, source version, affected channels, checks, approval, and rollback owner','set price, invent claims, publish, or override channel policy','an approved title exceeds a marketplace limit and truncation changes its meaning'],
['payroll-input-readiness-check','Check payroll-input readiness','people operations managers','a register showing each input, covered period, source, approval state, discrepancy, and payroll owner','change pay, interpret law, approve an adjustment, or release payroll','approved leave and submitted time overlap for the same shift'],
['sales-lead-routing-control','Control sales-lead routing','revenue operations managers','a routing log with source, consent signal, account match, territory rule, duplicate check, and owner','change territory rules, merge records, infer consent, or reassign an opportunity','a lead matches a global account but names a newly acquired subsidiary'],
['vendor-document-expiry-calendar','Maintain a vendor-document expiry calendar','procurement leaders','a calendar linking each document to the vendor, requirement source, expiry, reminder sequence, and reviewer','declare compliance, waive a requirement, suspend a vendor, or accept evidence','a replacement certificate names a different contracting entity'],
['customer-refund-status-handoff','Create a customer-refund status handoff','customer experience managers','a handoff containing the request, order, payment reference, policy version, decision state, update, and owner','approve or issue money, promise a date, alter policy, or close a dispute','the case says approved while the payment platform has no transaction'],
['access-request-minimum-evidence','Collect minimum evidence for access requests','IT service managers','a packet naming requester, subject, system, role, reason, data owner, duration, and approvals','grant access, select an entitlement, approve a conflict, or bypass verification','a familiar role name maps to broader privileges in the target system'],
['meeting-decision-register','Turn recurring meetings into a decision register','project support teams','a register separating decisions, actions, questions, owners, dates, source notes, and corrections','attribute an unclear decision, commit an absent owner, or publish confidential discussion','attendees disagree about who approved a deadline change'],
['quality-review-calibration-pack','Prepare a quality-review calibration pack','quality managers','a pack with a frozen sample, rubric version, independent scores, disagreements, interpretation, and owner','change a score after seeing another review, revise policy, rank staff, or decide discipline','reviewers agree an answer is weak but cite different requirements'],
['subscription-renewal-notice-check','Check subscription-renewal notice evidence','subscription managers','a preflight linking the account, plan, renewal date, terms, template, eligibility, and release owner','interpret legal duties, change terms, override suppression, or release a notice','billing and service records contain different notification addresses'],
['incident-shift-handoff-record','Build an incident shift-handoff record','service operations leaders','a chronology of impact, evidence, actions, hypotheses, open risks, next checks, and commander','declare root cause, make an unapproved change, communicate externally, or close an incident','metrics recover while customer reports continue from one region'],
].map(([slug,title,audience,artifact,boundary,exception])=>({slug,title,audience,artifact,boundary,exception}));
const sections=(t:Topic)=>[
 {heading:'Define one reviewable output',body:[`For ${t.audience}, the deliverable is ${t.artifact}. Keep it narrow enough that an internal owner can verify it without rebuilding the case.`,`Walk through one ordinary example and one exception before live work. Mark required fields, acceptable blanks, due times, and the state that means ready for review.`]},
 {heading:'Anchor the work to evidence',body:['Use the approved live system, current procedure, case history, and owner directory. Record stable identifiers and a version or timestamp wherever possible.','A conflict is evidence. Preserve both values, identify their sources, and route one focused question instead of silently choosing the convenient answer.']},
 {heading:'Keep authority with the owner',body:[`A specialist may collect, compare, label, draft, and route within written rules. They must stop before they ${t.boundary}.`,'Place that stop rule beside the checklist. Name a backup owner and define the pending state; silence is a hold, not permission.']},
 {heading:'Rehearse the awkward case',body:[`Test this scenario: ${t.exception}. Preserve the record, choose a neutral hold reason, and request the smallest decision needed to continue.`,'Return the decision through the same case record. Side-channel answers create invisible rules and weaken later review.']},
 {heading:'Review the routine honestly',body:['Track completeness, source conflicts, owner returns, aged holds, corrections, and reopenings. Show both counts and the eligible population.','Read speed beside evidence quality and boundary compliance. A correctly held exception may take longer than a wrongly closed item.']},
 {heading:'Start small on September 4',body:['Score two practice records, then review a limited first live batch in full. Expand only when source, boundary, hold, and owner paths are understood.',`Published September 4, 2026, this OutsourcedCompany.com guide describes a controlled ${t.slug.replaceAll('-',' ')} routine for Philippines-based support.`]},
];
export const blogPosts2026_09_04=topics.map((t,i)=>({slug:`philippines-outsourcing-september-4-${t.slug}`,title:`September 4 operating guide: ${t.title}`,excerpt:`A practical Philippines outsourcing routine for ${t.title.toLowerCase()} with traceable evidence, stop rules, and owner review.`,minutes:10+(i%3)}));
export const blogDetails2026_09_04=Object.fromEntries(topics.map(t=>[`philippines-outsourcing-september-4-${t.slug}`,{updated:'2026-09-04',marker:`daily-blog-2026-09-04-${t.slug}`,takeaway:`Use ${t.artifact}. The outsourced role prepares evidence; internal owners retain consequential decisions.`,comparison:[{weak:'Use your best judgment and keep the queue moving.',strong:'Follow named sources, record conflicts, and hold work at the written boundary.'},{weak:'Escalate unusual cases.',strong:'Choose the documented hold reason, attach evidence, and ask one precise question.'}],sections:sections(t),script:['Which source controls when systems disagree?',`Where must the specialist stop before they ${t.boundary}?`,'Who is the backup owner, and how does a decision return?'],sources:[{name:'NIST Cybersecurity Framework 2.0',note:'Governance and control context.',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'},{name:'Philippine National Privacy Commission: Data Privacy Act',note:'Primary Philippine privacy resource.',url:'https://privacy.gov.ph/data-privacy-act/'}],faqs:[{question:'Can the specialist resolve an exception?',answer:`Only under an explicit approved rule; otherwise stop before they ${t.boundary}.`},{question:'What should the owner review first?',answer:'Check evidence traceability, completeness, the hold reason, and correction history.'}]}]));
