import type { ResearchPost } from './article-research-batch';

const image = '/images/operations-meeting.jpg';
const imageAlt = 'Operations team reviewing a work queue together';
const related = [
  { label: 'Research index', href: '/research' },
  { label: 'Back-office operations', href: '/services/back-office-operations' },
  { label: 'Customer experience support', href: '/services/customer-experience-support' },
];
const cta = 'Bring the queue, examples, source owners, and review boundaries to a staffing intake.';

type Topic = { slug: string; title: string; excerpt: string; subject: string; unit: string; risks: string; source: { label: string; href: string }; finding: string; test: string; limit: string };

const topics: Topic[] = [
  { slug: 'philippines-outsourcing-knowledge-base-drift', title: 'Knowledge-base drift in Philippines outsourcing', excerpt: 'Research on detecting stale operating guidance before a Philippines-based support role relies on it.', subject: 'knowledge-base changes', unit: 'articles reviewed in a fixed four-week period', risks: 'stale answers, conflicting versions, and undocumented owner changes', source: { label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, finding: 'a source can look complete while still failing to identify which rule controls a live case', test: 'a redacted set of current and retired articles', limit: 'source age alone does not prove that an answer is wrong', },
  { slug: 'philippines-outsourcing-refund-evidence', title: 'Refund-evidence queues in Philippines outsourcing', excerpt: 'How to separate refund intake from approval when an outsourced operations queue handles customer records.', subject: 'refund evidence and routing', unit: 'refund requests received during a named accounting period', risks: 'duplicate approvals, missing order evidence, and unsafe payment changes', source: { label: 'NIST SP 800-53 Rev. 5', href: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' }, finding: 'a clean intake record is not evidence that the underlying exception was approved', test: 'fictional requests with ordinary, duplicate, and ambiguous cases', limit: 'control design cannot establish whether a particular payment was lawful', },
  { slug: 'philippines-outsourcing-catalog-accuracy', title: 'Catalog-accuracy research for Philippines outsourcing', excerpt: 'An evidence-led way to scope product-data maintenance without giving an outsourced role uncontrolled publishing power.', subject: 'catalog attributes and change review', unit: 'SKUs or service records sampled across a stated catalog snapshot', risks: 'wrong units, stale availability, and edits that change customer promises', source: { label: 'NIST SP 800-161 Rev. 1', href: 'https://csrc.nist.gov/pubs/sp/800/161/r1/upd1/final' }, finding: 'field-level accuracy and commercial approval are separate questions', test: 'a versioned catalog packet containing intentional conflicts', limit: 'a sample from one catalog cannot predict seasonal or new-product error', },
  { slug: 'philippines-outsourcing-calendar-coordination', title: 'Calendar-coordination evidence in Philippines outsourcing', excerpt: 'Research on scheduling work, time zones, and ownership when an outsourced coordinator manages appointments.', subject: 'calendar coordination and handoffs', unit: 'appointments created, moved, or cancelled in a fixed service window', risks: 'wrong time zones, double booking, and promises without an owner', source: { label: 'IANA Time Zone Database', href: 'https://www.iana.org/time-zones' }, finding: 'timestamp precision is useful only when the business rule and responsible owner are also explicit', test: 'fictional appointments spanning daylight-saving changes', limit: 'time-zone evidence cannot resolve a policy dispute about priority', },
  { slug: 'philippines-outsourcing-survey-response-quality', title: 'Survey-response quality in Philippines outsourcing', excerpt: 'A bounded research model for outsourced survey intake, coding, and escalation without overstating what responses mean.', subject: 'survey response handling', unit: 'responses received through each named channel and period', risks: 'duplicate responses, changed meanings, and privacy exposure in free text', source: { label: 'AAPOR Transparency Initiative', href: 'https://aapor.org/standards-and-ethics/transparency-initiative/' }, finding: 'response volume is not a measure of representativeness or decision quality', test: 'a synthetic response set with duplicates and ambiguous comments', limit: 'descriptive coding does not establish causation or population opinion', },
  { slug: 'philippines-outsourcing-vendor-onboarding-records', title: 'Vendor-onboarding records in Philippines outsourcing', excerpt: 'What a research-backed vendor intake should prove before a supplier record reaches an approval queue.', subject: 'vendor onboarding and evidence', unit: 'supplier records opened during a defined onboarding cohort', risks: 'duplicate suppliers, unverified bank details, and missing beneficial-owner review', source: { label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' }, finding: 'identity evidence, operational readiness, and payment approval should not be collapsed into one checkbox', test: 'redacted supplier packets with conflicting fields', limit: 'public registry evidence may be incomplete or use different definitions', },
  { slug: 'philippines-outsourcing-analytics-definition-control', title: 'Metric-definition control in Philippines outsourcing', excerpt: 'How to keep an outsourced reporting role from turning changing definitions into misleading operational trends.', subject: 'metric definitions and reporting', unit: 'reported measures by source, period, and denominator', risks: 'definition drift, hidden exclusions, and false comparisons', source: { label: 'OECD Glossary of Statistical Terms', href: 'https://stats.oecd.org/glossary/' }, finding: 'a trend is only interpretable when its numerator, denominator, population, and period stay visible', test: 'two reports that use the same label for different populations', limit: 'a stable definition does not make an underlying data source complete', },
  { slug: 'philippines-outsourcing-accessibility-review', title: 'Accessibility-review queues in Philippines outsourcing', excerpt: 'Evidence-led scope for outsourced accessibility checks that keeps remediation decisions with the responsible product owner.', subject: 'accessibility review findings', unit: 'pages, flows, or documents sampled with the stated method', risks: 'false certainty from automated checks, missing user context, and unowned remediation', source: { label: 'W3C Web Content Accessibility Guidelines 2.2', href: 'https://www.w3.org/TR/WCAG22/' }, finding: 'an automated result is a signal for investigation, not a complete accessibility judgment', test: 'a bounded page set plus keyboard and text alternatives review', limit: 'a small sample cannot certify an entire product or user population', },
  { slug: 'philippines-outsourcing-document-version-control', title: 'Document-version control in Philippines outsourcing', excerpt: 'Research on preserving source authority when an outsourced team prepares, checks, or routes business documents.', subject: 'document versions and approvals', unit: 'documents created or revised during a controlled period', risks: 'parallel edits, unapproved copies, and missing effective dates', source: { label: 'NARA Records Management Guidance', href: 'https://www.archives.gov/records-mgmt' }, finding: 'a filename is a weak version control mechanism unless the owner and effective state are explicit', test: 'a fictional folder containing drafts, approvals, and superseded copies', limit: 'retention requirements depend on the record, jurisdiction, and business purpose', },
  { slug: 'philippines-outsourcing-incident-intake-evidence', title: 'Incident-intake evidence in Philippines outsourcing', excerpt: 'How to design a safe outsourced incident-intake role that records facts without asking it to investigate or decide.', subject: 'incident intake and escalation', unit: 'reports received by severity, channel, and response period', risks: 'lost timestamps, contaminated evidence, and delayed owner decisions', source: { label: 'NIST Computer Security Incident Handling Guide', href: 'https://csrc.nist.gov/pubs/sp/800/61/r2/final' }, finding: 'intake quality depends on preserving the reporter’s facts and the next owner’s decision point', test: 'fictional reports containing routine, urgent, and incomplete information', limit: 'an intake record does not establish root cause or legal reporting duty', },
];

function body(t: Topic): string[] {
  return [
    `This article examines ${t.subject} in a Philippines-based outsourced operations context. The question is narrower than whether outsourcing is good or bad: what evidence should a buyer collect before assigning a bounded queue, what decisions must remain with the internal owner, and what can a reviewer learn from a defined sample? The unit matters. Here, the proposed unit is ${t.unit}. A result without that population can sound precise while describing almost nothing.`,
    `Start by describing the work as it exists. Record the source system, the incoming event, the fields the role may read, the output it may prepare, and the condition that stops routine handling. For ${t.subject}, the principal risks include ${t.risks}. Put each risk beside a control owner and an observable artifact. A policy statement is not the same as evidence that a policy operated. The distinction is especially important when a provider’s broad description covers several clients or processes that do not share the same data, authority, or review path.`,
    `A baseline should name its period, inclusion rules, and exclusions. For ${t.unit}, retain the snapshot or query used to select the sample, the person who selected it, and the reason the unit represents the proposed queue. Separate ordinary items from exceptions instead of averaging them together. If demand, product, staffing, or source rules changed during the period, split the cohort. This makes later comparisons honest and prevents a favorable small week from being treated as a durable operating fact.`,
    `The source hierarchy needs to be visible at field level. A current approved record may control one value while a contract, system log, owner message, or external standard controls another. When two sources conflict, preserve the conflict and route it; do not quietly choose the easier answer. The cited ${t.source.label} can frame a control or research question, but it does not certify a particular company, provider, worker, or record. Its scope and publication context belong in the notes.`,
    `A sensible first work sample uses synthetic or appropriately redacted material. Test ${t.test}. Include at least one routine item, one missing-input item, one conflicting-source item, and one case that should stop. Score whether the person identifies the source, records the reason, protects unnecessary information, and names the owner. A polished output is weaker evidence than a careful escalation when the facts do not support a conclusion. Never turn a live customer, payment, candidate, or security record into an experiment.`,
    `Measure quality with a denominator and a cause. Count the items reviewed, the items complete on first pass, the items returned for missing evidence, the items escalated, and the items later corrected. Report the review period and sample method. If ${t.subject} produces a headline percentage, state whether the measure is field-level, record-level, or outcome-level. Then record why an item missed: unclear rule, stale source, transcription error, access problem, or owner delay. Different causes require different repairs.`,
    `Authority boundaries are part of the research finding. The outsourced role may classify, compare, prepare, schedule, or route according to an approved rule. The internal owner should retain policy changes, material approvals, legal interpretations, sensitive access changes, and decisions where the evidence is incomplete. Write a stop rule that says what the role records, where it sends the case, and the response window. Without a named owner, escalation is only a label and the queue will quietly accumulate unresolved judgment.`,
    `The control should be observable after the work is done. Keep the source reference, timestamp, version, reviewer, decision state, and exception reason in the record where appropriate. Minimize personal information and avoid broad exports when a masked identifier or controlled lookup answers the question. Review named access, shared folders, downloads, and integrations when the assignment changes. The evidence should help a later reviewer reconstruct one item without asking the original worker to remember what happened.`,
    `Interpretation must stay bounded. A lower error rate may reflect easier cases, fewer arrivals, a changed denominator, or an unmeasured shift in work. A higher escalation rate may indicate better detection rather than weaker performance. For this topic, the central finding is that ${t.finding}. That is useful for scoping and review; it is not a promise about every Philippines-based team or an inference about individual capability. State alternatives beside the conclusion rather than hiding them in a footnote.`,
    `Continuity changes the evidence requirement. If the regular worker is absent, another person should be able to identify the current source, open items, approval owner, and safe fallback. Test one interruption using a fictional case and record where the handoff fails. Avoid treating a backup person as permission to broaden access permanently. A small, documented queue is easier to recover than a large one whose rules depend on a single manager’s memory.`,
    `There are important limitations. ${t.limit}. Public standards, statistics, or guidance may use a different population, time period, definition, or legal setting from the buyer’s queue. A work sample also shows a moment under stated conditions; it does not establish long-run quality, employment suitability, or compliance. Recheck the design when the tool, source, volume, product, policy, data flow, or owner changes. Give qualified legal, privacy, security, accounting, or accessibility advisers the actual facts when their judgment is required.`,
    `The practical conclusion is modest: define the queue, preserve the evidence, sample the real failure modes, and keep decisions with the person authorized to make them. For ${t.subject}, publish or approve a scope only after the owner can answer what enters, what leaves, what stops, and how a reviewer will know. The next research action is to run the bounded sample, compare observed causes with the proposed controls, and document what remains unknown. That sequence supports a responsible staffing decision without pretending that a checklist replaces evidence.`,
  ];
}

export const researchPosts2026_08_14: ResearchPost[] = topics.map((t) => ({
  slug: t.slug, title: t.title, excerpt: t.excerpt, updated: '2026-08-14', datePublished: '2026-08-14', image, imageAlt,
  body: body(t),
  sources: [t.source, { label: 'NIST Privacy Framework', href: 'https://www.nist.gov/privacy-framework' }, { label: 'Philippines National Privacy Commission: Data Privacy Act', href: 'https://privacy.gov.ph/data-privacy-act/' }],
  related, cta,
}));
