import type { ResearchPost } from './article-research-batch';

const sources = [
  { label: 'NIST Cybersecurity Framework 2.0', href: 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20' },
  { label: 'NIST Privacy Framework', href: 'https://www.nist.gov/privacy-framework' },
  { label: 'NIST SP 800-53 Rev. 5', href: 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final' },
  { label: 'NIST SP 800-34 Contingency Planning Guide', href: 'https://csrc.nist.gov/pubs/sp/800/34/r1/final' },
  { label: 'FTC Data Breach Response Guide', href: 'https://www.ftc.gov/business-guidance/resources/data-breach-response-guide-business' },
  { label: 'Philippines National Privacy Commission Data Privacy Act', href: 'https://privacy.gov.ph/data-privacy-act/' },
  { label: 'U.S. EEOC selection procedures guidance', href: 'https://www.eeoc.gov/laws/guidance/employment-tests-and-selection-procedures' },
  { label: 'IANA Time Zone Database', href: 'https://www.iana.org/time-zones' },
];

const related = [
  { label: 'Philippines outsourcing market overview', href: '/research/philippines-outsourcing-market-overview' },
  { label: 'How to measure outsourced operations quality', href: '/research/philippines-outsourcing-quality-measurement' },
  { label: 'Outsourcing vendor due diligence checklist', href: '/research/philippines-outsourcing-vendor-due-diligence' },
];

const commonTail = [
  'The evidence does not establish that every provider or worker will produce the same result. Compare the published context with the actual queue, a bounded work sample, access limits, and a named internal reviewer.',
  'Keep policy, money, legal, safety, and customer-exception decisions with the appropriate owner. A delivery role needs a clear stop rule and a handoff record, not permission to improvise.',
  'Use a narrow first release: one queue, one source of truth, one review cadence, and an explicit repair path. Expand only when observed work supports the decision.',
];

const make = (post: Omit<ResearchPost, 'updated' | 'sources' | 'related' | 'cta'>): ResearchPost => ({
  ...post,
  updated: '2026-08-12',
  sources,
  related,
  cta: 'Have a recurring queue to scope? Bring the source, examples, access needs, and review owner to the staffing intake.',
});

export const researchPosts2026_08_11: ResearchPost[] = [
  make({ slug: 'philippines-outsourcing-permission-design', title: 'Permission design for Philippines outsourcing roles', excerpt: 'Translate a recurring outsourced role into the smallest useful set of accounts, actions, and approval boundaries.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['Permission design starts with the action a role must take, not the software package it happens to use. Separate reading a record, drafting a change, sending an update, exporting data, and changing access because each carries a different consequence.', 'NIST access-control guidance supports assigning access by need and reviewing it as circumstances change. For a Philippines-based role, record the system, account owner, allowed action, business purpose, and removal trigger before work begins.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-source-authority', title: 'Source authority in outsourced operations research', excerpt: 'Decide which source wins when a recurring outsourced task relies on competing records, policies, or reference pages.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['A research or operations task becomes fragile when two sources can both appear correct. Define the authoritative source by claim or field, record its effective date, and state what the worker should do when sources disagree.', 'NIST governance and data-quality principles point toward named ownership and documented context rather than a silent preference for the newest-looking page. A source log should preserve the URL, date checked, extracted fact, and unresolved limitation.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-exception-routing', title: 'Exception routing for Philippines outsourced work', excerpt: 'Design exception paths that preserve useful work while sending unusual decisions to the right internal owner.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['An exception route is more than an instruction to ask a manager. It should identify the trigger, evidence to retain, temporary state, decision owner, and response window. That makes a remote operator safe and keeps a queue from disappearing into chat.', 'NIST incident and governance guidance emphasizes preparation, roles, and communication. Apply that logic to ordinary customer or operations exceptions without giving the delivery role authority over policy or risk decisions.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-data-minimization', title: 'Data minimization for Philippines outsourced workflows', excerpt: 'Reduce the personal information exposed by a recurring outsourced task while keeping the work reviewable.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['Data minimization is a design choice made before access is granted. Ask which fields the task truly needs, whether a masked identifier will work, how long the record must remain available, and who can approve an exception.', 'The Philippines Data Privacy Act and NIST Privacy Framework both support purpose-aware handling and accountability. They do not answer every cross-border or sector-specific legal question, so regulated processing should be reviewed by qualified counsel.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-quality-signal', title: 'Choosing quality signals for outsourced operations', excerpt: 'Use measures that reveal accuracy and risk in a Philippines-based queue instead of rewarding volume alone.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['A count of completed items says little if the queue contains different levels of difficulty. Pair volume with accuracy, reopened work, missed escalation triggers, age, and the share of items blocked by a missing source or decision.', 'Measurement guidance is useful only after the result is defined. Set the unit, population, sample method, reviewer, and action for a miss, then separate coaching information from employment or contract decisions.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-holiday-coverage', title: 'Holiday coverage evidence for Philippines support teams', excerpt: 'Plan coverage around Philippine holidays, customer commitments, and backup ownership without assuming constant availability.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['Coverage planning joins calendars with obligations. Reconcile Philippine public holidays, the customer service window, time-zone overlap, planned leave, and the person who can make an exception decision.', 'The IANA database helps teams reason about time-zone rules, while continuity planning asks whether the fallback person has access, context, and a safe scope of work. A calendar entry alone is not a continuity plan.', ...commonTail] }),

  make({ slug: 'philippines-outsourcing-knowledge-decay', title: 'Knowledge decay in outsourced operations', excerpt: 'Detect when a written operating answer has become stale before it causes repeated errors in a remote queue.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['A knowledge article can remain polished while its source, policy, tool, or owner has changed. Give each answer a source, effective date, responsible owner, review trigger, and retirement state, then sample live use for signs of drift.', 'NIST configuration and governance practices support change awareness and accountable review. The important question is not whether every page has a calendar reminder; it is whether change in the underlying decision can reach the people using the answer.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-backlog-age', title: 'Backlog age as a research signal for outsourced queues', excerpt: 'Read queue age alongside arrival patterns, complexity, quality, and blocked work when assessing an outsourced operation.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['Backlog size can fall while old or difficult items remain hidden. Track age bands, arrival rate, item type, service window, reopen rate, and blocked reason so a manager can distinguish capacity pressure from unclear policy or poor routing.', 'This is a decision lens, not a staffing promise. A Philippines team may have strong output while a source system or approval owner creates the real constraint; the record should make that distinction visible.', ...commonTail] }),
  make({ slug: 'philippines-outsourcing-recovery-evidence', title: 'Recovery evidence for Philippines outsourced operations', excerpt: 'Test whether a remote queue can resume safely after a tool, source, person, or connection becomes unavailable.', image: '/images/operations-meeting.jpg', imageAlt: 'Operations team reviewing a work queue together', body: ['Continuity is demonstrated by a usable recovery path, not by a document that says backup exists. Identify the last trusted state, alternate access, decision owner, communication channel, and the work that must pause rather than be reconstructed from memory.', 'NIST contingency planning recommends business impact and recovery objectives tied to real systems and responsibilities. Test a small scenario, record elapsed steps and missing permissions, and repair the dependency before treating the path as dependable.', ...commonTail] }),
];
