type Topic = { slug: string; title: string; keyword: string; focus: string; steps: string[]; stop: string };

const topicRows: [string, string, string, string, string[], string][] = [
  ['outsourcing-accounts-receivable-philippines', 'Outsourcing accounts receivable to the Philippines: a controlled workflow', 'outsourcing accounts receivable Philippines', 'accounts receivable', ['prepare the aging report', 'match approved records', 'route exceptions'], 'Stop before changing a balance, promising collection terms, or contacting a disputed account.'],
  ['philippines-outsourcing-purchase-order-processing', 'Philippines outsourcing purchase order processing guide', 'Philippines outsourcing purchase order processing', 'purchase order processing', ['collect approved requests', 'check required fields', 'route for approval'], 'Stop before approving spend, changing a supplier, or bypassing an approval limit.'],
  ['philippines-outsourcing-inventory-reconciliation', 'Philippines outsourcing inventory reconciliation checklist', 'Philippines outsourcing inventory reconciliation', 'inventory reconciliation', ['export the approved count', 'compare the system record', 'log variances'], 'Stop when a variance needs a write-off, a count conflicts, or a stock decision is required.'],
  ['philippines-outsourcing-appointment-scheduling', 'Philippines outsourcing appointment scheduling: a safe handoff', 'Philippines outsourcing appointment scheduling', 'appointment scheduling', ['collect availability', 'offer approved slots', 'confirm the booking'], 'Stop when a clinical, legal, financial, or priority decision is hidden in the request.'],
  ['philippines-outsourcing-document-management', 'Philippines outsourcing document management plan', 'Philippines outsourcing document management', 'document management', ['name the source folder', 'apply allowed labels', 'record the handoff'], 'Stop when a document is confidential, retention-sensitive, or its owner cannot be identified.'],
  ['philippines-outsourcing-market-research-support', 'Philippines outsourcing market research support guide', 'Philippines outsourcing market research support', 'market research support', ['search named sources', 'capture dated evidence', 'summarize the findings'], 'Stop before presenting an unsupported conclusion, using private data, or making a market claim.'],
  ['philippines-outsourcing-content-operations', 'Philippines outsourcing content operations checklist', 'Philippines outsourcing content operations', 'content operations', ['prepare the editorial queue', 'check the approved brief', 'route the draft'], 'Stop before making a factual claim without a source, changing strategy, or publishing an unapproved promise.'],
  ['philippines-outsourcing-social-media-scheduling', 'Philippines outsourcing social media scheduling guide', 'Philippines outsourcing social media scheduling', 'social media scheduling', ['load approved posts', 'check dates and links', 'record the schedule'], 'Stop before changing copy, responding to a complaint, or publishing a sensitive claim.'],
  ['philippines-outsourcing-bookkeeping-preparation', 'Philippines outsourcing bookkeeping preparation: owner controls', 'Philippines outsourcing bookkeeping preparation', 'bookkeeping preparation', ['collect source records', 'match transactions', 'prepare exceptions'], 'Stop before posting a journal, changing a rule, approving a payment, or signing off accounts.'],
  ['philippines-outsourcing-payroll-administration', 'Philippines outsourcing payroll administration checklist', 'Philippines outsourcing payroll administration', 'payroll administration', ['collect approved changes', 'check the payroll fields', 'route the final file'], 'Stop before changing pay, classifying a worker, releasing payroll, or handling a disputed record.'],
  ['philippines-outsourcing-customer-onboarding', 'Philippines outsourcing customer onboarding workflow', 'Philippines outsourcing customer onboarding', 'customer onboarding', ['collect the intake form', 'check required setup fields', 'route open questions'], 'Stop when identity is uncertain, a contract term changes, or a customer promise needs judgment.'],
  ['philippines-outsourcing-renewal-administration', 'Philippines outsourcing renewal administration guide', 'Philippines outsourcing renewal administration', 'renewal administration', ['review the renewal queue', 'check dates and owners', 'prepare approved notices'], 'Stop before changing terms, offering a concession, or deciding whether a customer should renew.'],
  ['philippines-outsourcing-compliance-records', 'Philippines outsourcing compliance records checklist', 'Philippines outsourcing compliance records', 'compliance records', ['collect named evidence', 'check dates and fields', 'flag missing records'], 'Stop before interpreting a rule, certifying compliance, or deleting a retained record.'],
  ['philippines-outsourcing-website-content-updates', 'Philippines outsourcing website content updates: a release checklist', 'Philippines outsourcing website content updates', 'website content updates', ['use the approved change', 'check links and layout', 'record the release'], 'Stop before changing legal copy, pricing, tracking, access, or an unapproved customer claim.'],
  ['philippines-outsourcing-email-campaign-operations', 'Philippines outsourcing email campaign operations guide', 'Philippines outsourcing email campaign operations', 'email campaign operations', ['prepare the approved audience', 'check links and fields', 'route the preview'], 'Stop before changing consent rules, audience criteria, claims, or send approval.'],
  ['philippines-outsourcing-logistics-coordination', 'Philippines outsourcing logistics coordination checklist', 'Philippines outsourcing logistics coordination', 'logistics coordination', ['read the shipment record', 'update allowed status fields', 'route delays'], 'Stop before changing delivery promises, customs information, costs, or a customer remedy.'],
  ['philippines-outsourcing-technical-support-triage', 'Philippines outsourcing technical support triage plan', 'Philippines outsourcing technical support triage', 'technical support triage', ['identify the incident', 'apply the approved first check', 'route the severity'], 'Stop on security indicators, data loss, production changes, or an incident outside the runbook.'],
  ['philippines-outsourcing-feedback-analysis', 'Philippines outsourcing customer feedback analysis guide', 'Philippines outsourcing customer feedback analysis', 'feedback analysis', ['collect the approved sample', 'tag the stated themes', 'report evidence and gaps'], 'Stop before inferring protected traits, naming individuals, or recommending a policy change.'],
  ['philippines-outsourcing-contract-administration', 'Philippines outsourcing contract administration checklist', 'Philippines outsourcing contract administration', 'contract administration', ['maintain the contract register', 'check dates and documents', 'prepare owner reminders'], 'Stop before interpreting obligations, changing terms, or sending a legal notice.'],
  ['philippines-outsourcing-training-coordination', 'Philippines outsourcing training coordination workflow', 'Philippines outsourcing training coordination', 'training coordination', ['maintain the attendee list', 'send approved materials', 'record completion'], 'Stop before changing required training, evaluating employment performance, or sharing restricted records.'],
];
const topics: Topic[] = topicRows.map(([slug, title, keyword, focus, steps, stop]) => ({ slug, title, keyword, focus, steps, stop }));

const makeDetails = (topic: Topic, index: number) => ({
  updated: '2026-08-10', keyword: topic.keyword, marker: `daily-blog-batch-2026-08-10-${String(index + 1).padStart(2, '0')}`,
  takeaway: `A reliable ${topic.focus} handoff starts with one queue, a visible done check, and a named owner for anything outside the written rule. Filipino staff can complete routine work when the source, access, schedule, and escalation path are clear.`,
  comparison: [
    { weak: `We need help with ${topic.focus}.`, strong: `We need a Filipino specialist to complete the written ${topic.focus} queue, record each result, and stop on the listed exceptions.` },
    { weak: 'Quality matters to us.', strong: 'The internal owner will review the first ten items against the same written fields and record each miss by cause.' },
    { weak: 'Use the tools as needed.', strong: 'Start with a named account and only the permissions required for this queue; approval, export, and deletion stay with the owner.' },
  ],
  sections: [
    { heading: `Define the ${topic.focus} queue`, body: [`Name the records or requests that enter the queue, how they arrive, what a finished item looks like, and where the result is recorded. Use completed examples so the role describes work rather than a personality.`, `Keep the first queue narrow. A small repeatable lane gives the worker practice, gives the manager a fair sample, and exposes missing rules before more responsibility is added.`] },
    { heading: 'Write the normal path', body: [`A useful first path is: ${topic.steps[0]}, then ${topic.steps[1]}, then ${topic.steps[2]}. Put the source of truth beside each step, including the exact field or screen the worker should use.`, 'Use a short handoff note for open questions. Include the record, the action already taken, the reason it stopped, and the person who owns the next answer.'] },
    { heading: 'Keep decisions with the right owner', body: [`The worker should not guess when routine work becomes a company decision. ${topic.stop}`, 'Name the internal owner, response window, and evidence to collect. A stop rule that only says ask a manager creates delay and makes the manager reconstruct the case.'] },
    { heading: 'Limit tools and data', body: ['Start with a named account and the lowest permission needed for this queue. Separate reading, drafting, sending, approving, exporting, deleting, and administration.', 'Use the approved system or masked examples for review. Do not copy live personal data into an informal worksheet.'] },
    { heading: 'Review the first batch', body: ['Check every early item against the same fields: correct source, correct record, complete action, accurate note, and proper escalation. Record the cause of a miss instead of only marking it wrong.', 'If the same question appears more than once, repair the guide or source. Process repair helps the whole queue.'] },
    { heading: 'Launch in 30 days', body: ['Days 1–3: write the queue and collect examples. Days 4–8: run a work sample and confirm schedule and tools. Days 9–14: practice with test or old records. Days 15–21: open one small live lane. Days 22–30: review quality, access, and manager load.', 'Add a second task only when the first lane has a stable source, a repeatable review, and no unresolved ownership gap.'] },
  ],
  workflow: [{ step: 'Days 1–3', title: 'Map the queue', body: `Write the source, examples, finish rule, access needs, schedule, and stop rules for ${topic.focus}.` }, { step: 'Days 4–8', title: 'Test the work', body: 'Use the same normal, incomplete, and escalation cases for every candidate or trainee.' }, { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or old work with personal details removed. Review every item before live access.' }, { step: 'Days 15–21', title: 'Open one lane', body: 'Keep the first live volume small and make the owner available for blocked cases.' }, { step: 'Days 22–30', title: 'Repair the process', body: 'Group misses by cause, update the guide, and add responsibility only when the queue is steady.' }],
  script: [`Which exact ${topic.focus} cases will this role handle first?`, 'Show us how a normal case, a missing-information case, and an escalation move through the queue.', 'Which named accounts and permissions are needed on day one, and who approves changes?', 'Who reviews the first batch, what fields do they check, and how are recurring misses repaired?'],
  sourcesNumbered: true, sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Authoritative guidance for identifying, protecting, detecting, responding to, and recovering from cybersecurity risk.' }],
  faqs: [{ question: `What should be outsourced first in ${topic.focus}?`, answer: 'Start with recurring work that has examples, a clear finish, limited access, and a named reviewer. Keep judgment, approvals, and sensitive exceptions with the appropriate owner.' }, { question: 'How do I protect access?', answer: 'Use named accounts, least privilege, multi-factor login where available, an access record, and a removal step. Do not share passwords or broad admin rights.' }, { question: 'When should the worker stop?', answer: topic.stop }],
  relatedLinks: [{ label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' }, { label: 'Use the Philippines quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' }, { label: 'See back-office operations support', href: '/services/back-office-operations' }],
});

export const blogBatch2026_08_10Posts = topics.map(({ slug, title }) => ({ slug, title, excerpt: `Set up ${title.toLowerCase().replace(/^.*?: /, '')} with a written queue, limited access, and a clear owner for exceptions.`, minutes: 9 }));
export const blogBatch2026_08_10Details = Object.fromEntries(topics.map((topic, index) => [topic.slug, makeDetails(topic, index)]));
