import type { ResearchPost } from './article-research-batch';

type Study = { slug: string; title: string; excerpt: string; image: string; question: string; thesis: string; method: string; scope: string; cases: string; clocks: string; facts: string; measures: string; boundary: string; operations: string; validation: string; limitations: string; interpretation: string; conclusion: string; sources: Array<[string, string]> };
const updated = '2026-09-03';
const related = [{ label: 'Research index', href: '/research' }, { label: 'Back-office operations', href: '/services/back-office-operations' }, { label: 'Quality assurance support', href: '/services/quality-assurance-support' }];
const studies: Study[] = [
  {
    slug: 'refund-evidence-latency-study', title: 'When does refund evidence arrive too late for an outsourced queue?', excerpt: 'A research design for measuring evidence latency before a Philippines-based support role prepares a refund case for an authorized owner.', image: '/images/daily-research-2026-09-03/refund-evidence-latency.png',
    question: 'When does missing or delayed evidence make a refund-preparation queue unsafe to expand to a Philippines-based outsourced team?',
    thesis: 'The issue is narrower than refund speed. A specialist may assemble the case, confirm source records, and route it while an internal owner retains authority over money movement. Readiness depends on whether decision evidence reaches the queue before its usefulness decays, not whether every request closes quickly.',
    method: 'Follow a defined cohort from first request through owner disposition. Record when each required source becomes available, when the specialist checks it, when contradictions appear, and when the packet reaches its owner. Define required fields before sampling. Retain approved, declined, abandoned, duplicate, and still-open requests so completed cases do not hide long waits.',
    scope: 'Review the original request, order identifier, payment reference, fulfillment state, return record where applicable, prior promises, policy version, specialist note, owner decision, and timestamps with time zones. Use only the customer data needed for the study. Do not copy full payment credentials, unrelated messages, or identity documents simply because a source system exposes them.',
    cases: 'Sample complete tracking, a split shipment, a duplicate request, a late carrier scan, a claim that conflicts with the commerce record, and a case received outside owner coverage. Some correct results are documented holds. A study that scores only completed refunds rewards unsupported action precisely when waiting would be safer.',
    clocks: 'Use separate clocks for request-to-source availability, availability-to-first review, and escalation-to-owner decision. Combining them can make an upstream carrier delay look like staffing delay or make an unavailable owner look like poor packet quality. Each interval needs a named start event, stop event, and accountable role.',
    facts: 'Facts are timestamps, field values, source links, packet contents, and decisions. A claim that delay came from workload, system design, or an unclear rule is analysis. A late packet does not prove slow work when the required record did not exist. A fast packet is weak evidence if it omits the conflict governing the decision.',
    measures: 'Measure first-review evidence completeness, source-availability delay, escalation delay after evidence appears, owner returns for missing fields, unsupported recommendations, and reopen rate. Report counts with percentages. Keep consequential cases separate because many simple cancellations can conceal a few high-risk disputes.',
    boundary: 'The outsourced role may gather permitted evidence, prepare the packet, flag conflicts, and apply a documented hold. Internal owners decide eligibility, payment action, suspected misuse, legal questions, exceptions, and customer remedies. A prior owner exception must not become an unwritten permission for the queue.',
    operations: 'Shift overlap affects whether a carrier update or owner answer arrives during coverage. Preserve local and shared timestamps, holidays, the next handoff, and the owner response window. Geography is not a cause of delay by itself. Event history, access, and coverage rules are stronger evidence than assumptions about a country or workforce.',
    validation: 'Give a blinded subset to a second authorized reviewer with the same rubric and source access. Compare required-field findings, stop decisions, and clock assignments. Resolve rule ambiguity before comparing workers, then test the revised rubric on unseen cases rather than rescoring only familiar examples.',
    limitations: 'Logs may be incomplete, carrier data arrives asynchronously, policy can change during the cohort, and owners may decide in side channels. Completed cases may differ from abandoned requests. The study cannot establish a universal refund timeline or prove that a staffing model caused an outcome.',
    interpretation: 'Interpret latency by failure mode before choosing an intervention. If the source is unavailable, improve the upstream event or define a safe waiting state. If the packet sits after all evidence arrives, inspect pickup and shift ownership. If owners repeatedly return complete packets, clarify their decision standard rather than adding fields without a demonstrated need. Compare the oldest cases with a random sample because averages can make rare but consequential disputes invisible. Review whether reminders produce a decision or merely create duplicate messages. A manager can use the result to change the readiness event, owner coverage, packet fields, or permission boundary. The result should not be converted into a promise that every refund will close within a fixed period. A request may need investigation or information outside the measured systems. Record what remained unknown at disposition and whether the customer-facing message stayed within approved language. Re-run the cohort after a policy, carrier, commerce platform, service window, or ownership change. A stable measure requires the same event definitions across periods; otherwise an apparent improvement may only reflect a new clock. The practical decision is whether the queue can prepare evidence predictably while stopping safely, not whether it can make consequential decisions faster than its authority allows.',
    conclusion: 'Refund evidence arrives too late when a required source appears after the documented action point or cannot be connected to the request before a promise is made. Expansion is supported by traceable sources, appropriate holds, few owner returns, and a reachable authorization path. Repair the evidence path before widening authority.',
    sources: [['NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'], ['FTC consumer advice on refunds', 'https://consumer.ftc.gov/articles/what-do-if-youre-billed-things-you-never-got-or-you-get-unordered-products'], ['UK Government Service Manual: measuring success', 'https://www.gov.uk/service-manual/measuring-success']]
  },
  {
    slug: 'crm-field-provenance-study', title: 'Can a CRM field show where an outsourced update came from?', excerpt: 'Research on whether Philippines-based sales administration updates remain traceable to an approved source and decision owner.', image: '/images/daily-research-2026-09-03/crm-field-provenance.png',
    question: 'Can a manager reconstruct where a changed CRM field came from after a Philippines-based sales administration specialist updates it?',
    thesis: 'This is a provenance question, not a data-entry speed test. A field is trustworthy when an authorized reviewer can identify its source, effective time, updater, applicable rule, and correction history without relying on private memory. Whole-record labels hide the fact that different fields may have different authorities.',
    method: 'Inventory fields that drive distinct actions, including lifecycle stage, owner, next-contact date, consent status, company name, and lead source. Draw a stratified sample across shifts, imports, ordinary updates, and exceptions. Trace each value backward to submitted evidence and forward to automation or human action. Include unchanged eligible fields to detect omissions.',
    scope: 'Retain record identifier, field name, old and new values, event time, named account, source reference, procedure version, validation outcome, and correction history. Mask personal data unnecessary to the analysis. A provenance review should reduce uncertainty, not create a secondary export of the sales database.',
    cases: 'Use challenge cases where an import conflicts with a recent message, automation changes ownership, a company name differs across tools, or a consent event is missing. Score conflict detection and routing. An unsupported guess is not a success merely because the owner later selects the same value.',
    clocks: 'Record source effective time, ingestion time, human review, field update, automation response, and downstream use. This sequence distinguishes stale input from late review and shows when a consequential action launched before validation. Preserve time zones around shift transfer.',
    facts: 'An event log can show that a field changed under a named account. It cannot alone establish why it changed or whether the account holder personally acted. Source links and procedure records support that explanation. Label causal judgments separately when integrations or shared service identities remain in use.',
    measures: 'Calculate source-reference coverage, correct authority by field, conflict detection, unsupported changes, correction direction, and downstream actions before validation. Show denominators for every field. A high overall score can hide weak provenance in a low-volume consent or assignment field.',
    boundary: 'The outsourced role may apply a documented update, attach the source reference, detect disagreement, and route an exception. Internal owners define fields, approve bulk changes, resolve consent or legal questions, change territory rules, and accept data risk. Inconsistency does not authorize a specialist to redefine a field.',
    operations: 'Treat automation as an actor in the chain. If a workflow overwrites a correction, provenance must show both events. For a shared integration identity, retain the job and approved input. Otherwise manual workers can appear responsible for changes they did not make while the actual control remains broken.',
    validation: 'Ask another authorized reviewer to reconstruct a blinded subset using only retained records. Compare source, rule, allowed action, and downstream consequence. Resolve source-hierarchy ambiguity, revise the rule, and test new cases. Agreement on examples already discussed is not strong evidence of repeatability.',
    limitations: 'Audit logs may be incomplete, imports may overwrite history, shared accounts can blur attribution, and upstream statements may themselves be wrong. A sample can miss rare bulk edits. Provenance confirms the recorded chain, not the truth of every claim in that chain.',
    interpretation: 'Use disagreement patterns to locate weak field governance. If reviewers consistently find different sources for the same field, the source hierarchy needs repair. If they agree on the source but differ on the permitted update, the procedure or authority boundary is unclear. If automation reverses correct work, changing individual coaching will not solve the defect. Examine consequential fields before high-volume cosmetic ones, and retain the direction of every correction. A corrected value is useful evidence only when the record shows why the replacement is better supported. Managers can respond by narrowing edit permissions, requiring a source token, sequencing automations differently, or moving a field to owner-only control. They should not treat provenance completeness as proof that a lead, account, or consent state is substantively correct. The underlying source can still contain error. Repeat the analysis after migrations, import redesigns, territory changes, or new integrations. Compare the live work surface with the written source map because a document may point to a field the specialist cannot access. The operational question is whether another authorized person can reconstruct and defend the update without consulting the original worker, then identify the owner when the sources disagree.',
    conclusion: 'A CRM field supports an outsourced update when its chain connects the approved source, applicable rule, named event, and downstream effect. Expand scope only when challenge cases and blinded reconstruction keep conflicts visible and prevent consequential fields from moving on unsupported assumptions.',
    sources: [['NIST SP 800-53 Rev. 5', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'], ['GAO Assessing Data Reliability', 'https://www.gao.gov/products/gao-20-283g'], ['NIST Privacy Framework', 'https://www.nist.gov/privacy-framework']]
  },
  {
    slug: 'vendor-bank-change-verification-study', title: 'What evidence should stop an outsourced vendor bank-change request?', excerpt: 'A study of verification signals, safe stops, and owner authorization for vendor administration support in the Philippines.', image: '/images/daily-research-2026-09-03/vendor-bank-change-verification.png',
    question: 'What observable evidence should stop a Philippines-based vendor administration specialist from processing a bank-detail change?',
    thesis: 'The research concerns detection and handoff quality. It does not delegate payment approval, fraud investigation, or bank-account verification. A useful control lets the specialist recognize a request outside the approved path and deliver it to an authorized owner without spreading sensitive banking data.',
    method: 'Assemble de-identified historical or simulated requests with routine, incomplete, conflicting, and suspicious conditions. Predefine the approved channel, current vendor record, callback rule, separation of duties, and recipients. Present cases without final outcomes and compare the recorded action with the rule and owner review.',
    scope: 'Capture request channel, sender identifier, vendor reference, changed fields, prior authorized contact, callback event where policy permits, account permissions, attachment handling, stop reason, and owner disposition. Use tokens or masked values. The research file should never become a collection of full account numbers.',
    cases: 'Vary one meaningful condition at a time: a familiar sender on a new domain, urgency that bypasses the portal, an unrelated invoice attachment, a callback number supplied in the request, and a genuine change with incomplete support. Reward a correct stop even when the request later proves legitimate.',
    clocks: 'Measure request receipt, first check, hold placement, escalation delivery, owner acknowledgment, verification, and final disposition. Separate after-hours owner delay from specialist detection. Keep duplicates as one event history rather than treating several messages as several successful cases.',
    facts: 'Sender domain, message route, masked comparison, callback source, timestamp, and access event are facts. A judgment that a pattern suggests impersonation or evasion is analysis. The specialist can document mismatch without declaring fraud; the owner can investigate without treating the first label as a finding.',
    measures: 'Report correct stops, missed stops, false stops, routine routing, evidence completeness, prohibited data copied, unauthorized actions attempted, owner acknowledgment time, and reversals. A method that stops every request may detect every challenge but still be unusable, so both safety and operational impact matter.',
    boundary: 'The specialist may compare permitted records, preserve the request, use a known verification route, and apply a hold. Finance or security owners decide identity, payment-detail changes, pending-payment actions, and legal or incident procedures. A training result must not silently expand these authorities.',
    operations: 'Test the communication and permission design. A correct escalation fails if it reaches an unmonitored mailbox. A preparation account should not automatically approve or release payments. Where tools cannot separate duties, document the owner check and consider narrowing the queue until a stronger control exists.',
    validation: 'Use independent blinded scoring by an authorized finance or security reviewer. Reconcile disagreements about the rule, then introduce unseen cases combining normal business pressure with one stop condition. This tests whether the control survives realistic context rather than only obvious warning examples.',
    limitations: 'Synthetic cases may be easier than live deception, headers may be incomplete, policies drift, and side-channel owner decisions disappear from the queue. A nonrepresentative challenge set cannot estimate fraud prevalence or promise that losses will be prevented.',
    interpretation: 'Review missed stops more closely than aggregate accuracy, but do not hide false stops. A high false-stop rate can drive teams toward informal bypasses that weaken the control. For each result, ask whether the specialist had the approved source, whether the verification route was independent, and whether an owner was reachable. If the rule depends on information visible only to finance, the workflow should route earlier rather than expecting the preparation role to infer it. Compare simulated cases with ordinary live requests to see whether the exercise creates unnatural cues. Preserve the wording and presentation order so future reviewers can understand what the participant actually saw. A manager may improve the portal, lock sensitive fields, separate permissions, add a backup owner, or clarify the callback source. Coaching is appropriate only where the rule and work surface were usable. Repeat the challenge after tool, vendor-master, payment, or ownership changes. Treat urgent requests as a test of the same boundary, not a reason to suspend it. The useful outcome is a reliable stop and attributable decision, not a specialist accusation or a claim that the workflow eliminates fraud.',
    conclusion: 'A vendor bank-change request should stop when channel, source identity, supporting record, verification route, permissions, or ownership falls outside the approved rule. Expansion requires traceable holds, minimal sensitive-data exposure, good challenge-case results, and a functioning owner path.',
    sources: [['CISA phishing guidance', 'https://www.cisa.gov/secure-our-world/recognize-and-report-phishing'], ['NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'], ['NIST SP 800-53 Rev. 5', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final']]
  },
  {
    slug: 'candidate-scheduling-handoff-study', title: 'Where does candidate scheduling context disappear between shifts?', excerpt: 'Research on continuity, minimum necessary data, and owner boundaries in Philippines-based recruitment coordination.', image: '/images/daily-research-2026-09-03/candidate-scheduling-handoff.png',
    question: 'Where does decision-relevant context disappear when candidate scheduling passes between Philippines-based coordinators and internal hiring owners?',
    thesis: 'The study concerns scheduling continuity, not candidate merit. It asks whether a receiving coordinator can recover the active stage, agreed time basis, last source event, open exception, and next owner. Hiring decisions and judgments about candidates remain outside the coordination role.',
    method: 'Follow a cohort through invitation, response, reschedule, interviewer change, accommodation routing, completion, or closure. Define handoff fields before reading outcomes. Compare each transfer record with what the receiver could see and what happened next. Include stopped cases and work outside the normal calendar path.',
    scope: 'Review candidate and requisition identifiers, permitted channel, interview stage, original time-zone expression, availability window, panel, status, last message, open question, owner, and timestamps. Route accommodation details under the approved privacy process and exclude them from general notes when not needed to schedule.',
    cases: 'Include differing time zones, a panelist replacement, a late response near shift end, duplicate invitations, an inaccessible meeting link, an accommodation route, and a requisition status change. Some correct outcomes are pauses. A scheduling status must never substitute for a hiring decision.',
    clocks: 'Track invitation, response, record update, handoff, owner answer, and calendar confirmation. Preserve the original timezone and a shared reference. This distinguishes a true delay from an overnight gap outside agreed coverage and reveals which shift owns the next check.',
    facts: 'Availability, timezone, calendar event, message, role assignment, and next action are facts. A claim that context loss caused confusion is analysis. An unanswered invitation has many possible causes and should not become evidence of candidate interest without an owner-approved rule.',
    measures: 'Measure required-field presence, receiver reconstruction, duplicate invitations, timezone corrections, unresolved owner questions, rework, and time from a material change to acknowledgment. Counts by case type matter because a short median booking time can coexist with repeatedly disrupted interviews.',
    boundary: 'Coordinators may send approved scheduling messages, maintain calendars, record availability, repair routine link issues, and escalate. Hiring owners retain selection, stage changes, interviewer requirements, accommodations, policy interpretation, and judgments about candidacy.',
    operations: 'Inspect the applicant system, calendar, email, and messaging surfaces separately. A calendar event can survive a closed requisition; an email can propose an unaccepted time. Name the governing source for stage and for event time. Avoid flattening those states into a misleading label such as scheduled.',
    validation: 'Give the durable handoff, without private chats, to a blinded authorized coordinator. Ask for current state, next allowed action, open decision, and owner. Repair field definitions or source rules when reviewers disagree, then repeat on an unseen transition case.',
    limitations: 'Side-channel messages may be absent, calendars can rewrite timestamps, withdrawn cases may be incomplete, and one hiring period may not represent another. Scheduling alone cannot explain candidate experience, and the study does not compare locations or individual capability.',
    interpretation: 'Interpret missing context according to the surface where it disappeared. If availability remains in email but not the applicant system, repair the capture rule. If the stage is wrong in the applicant system, the hiring owner must correct the governing record. If a calendar change lacks a message, add confirmation evidence rather than expecting the next coordinator to infer intent. Review repeat reschedules separately because each transfer creates another opportunity for timezone and ownership loss. A manager can simplify required fields, improve calendar templates, name backup coverage, or restrict sensitive notes. The research should not score a coordinator on response events controlled by candidates or interviewers. It should score the accuracy and completeness of the actions inside the role. Repeat the study after a new scheduling tool, recruiting process, regional coverage model, or accommodation route. Preserve withdrawn and cancelled cases with their final known state so they do not disappear from denominators. The decision supported by this evidence is whether scheduling continuity survives a real handoff while privacy and hiring judgment remain with authorized owners. It is not a ranking of candidates, coordinators, staffing providers, or countries.',
    conclusion: 'Context disappears when the record omits stage, time basis, last source event, exception, or owner. Expansion is supported when another coordinator can reconstruct those elements, act within the written boundary, and route sensitive or selection decisions without copying unnecessary information.',
    sources: [['EEOC Uniform Guidelines on Employee Selection Procedures', 'https://www.eeoc.gov/laws/guidance/uniform-guidelines-employee-selection-procedures'], ['NIST Privacy Framework', 'https://www.nist.gov/privacy-framework'], ['W3C Web Content Accessibility Guidelines 2.2', 'https://www.w3.org/TR/WCAG22/']]
  },
  {
    slug: 'catalog-rollback-readiness-study', title: 'Can an outsourced catalog team reverse a bad publication safely?', excerpt: 'A study of rollback evidence, authority, and recovery testing for Philippines-based ecommerce administration.', image: '/images/daily-research-2026-09-03/catalog-rollback-readiness.png',
    question: 'Can a Philippines-based ecommerce administration team contain and reverse an incorrect catalog publication without losing the prior approved state?',
    thesis: 'Rollback readiness is more than changing a visible field back. The team must identify the approved state, contain affected scope, preserve history, reconcile every channel, and keep price, safety, legal, and customer-remedy decisions with internal owners.',
    method: 'Trace bounded catalog changes from approved input through staging, validation, publication, detection, hold, rollback, and review. Use controlled exercises where possible. For live history, preserve chronology without replaying harmful changes. Define qualifying attributes and restored state before examining results.',
    scope: 'Retain product identifier, channel, attributes, old and proposed values, approved source, batch identifier, publishing account, validation, detection signal, rollback action, owner decision, and cache or feed status. Exclude unrelated customer, supplier, and commercial data.',
    cases: 'Test a single-field error, a mixed bulk import, correct source mapped to the wrong field, one-channel publication, an expired cache, and a prior value that was already wrong. The final case proves why rollback to "before" is not always restoration to "approved."',
    clocks: 'Track source approval, job start, publication, detection, hold, rollback, channel verification, and the next scheduled synchronization. A correction overwritten at the next sync is temporary containment, not recovery. Keep the case open until the normal path sustains the approved state.',
    facts: 'Field values, versions, events, channel responses, timestamps, and accounts are facts. Claims about mapping, review, permissions, or monitoring as causes are analysis. A visible error does not prove who introduced it when integrations transform inputs or marketplaces alter display.',
    measures: 'Report detection time, safe-hold time, approved-state recovery, channels reconciled, fields changed outside scope, owner response, repeat publication, and evidence completeness. Define the denominator as affected products or eligible attributes. A fast storefront rollback can hide a stale feed.',
    boundary: 'The outsourced role may detect mismatch, stop a permitted job, capture identifiers, apply an approved reversible action, and escalate. Owners decide withdrawal, commercial terms, claims, customer notice, regulatory response, and acceptance of residual inconsistency. Emergency language does not erase authority limits.',
    operations: 'Review whether one account can prepare, approve, publish, and delete history. If so, document exposure and add an owner check or narrower role. Test alerts across shifts and confirm that the recipient can access decision evidence. Location informs coverage design, not assumptions about responsiveness.',
    validation: 'A second authorized reviewer should reconstruct the approved state and compare the source, platform, and public output for every channel. Recheck after the next scheduled sync. An administration screen that looks correct is insufficient if a cache or marketplace still serves the bad value.',
    limitations: 'Platforms differ in history, caches delay observation, tests differ from production, third-party logs may be incomplete, and consequential incidents are rare. A drill proves a path under tested conditions, not that every catalog error will be found or reversed.',
    interpretation: 'Interpret containment and recovery separately. A disabled feed may stop new exposure without correcting pages already cached, while a manual field edit may repair one page without fixing the governing import. Record which layer each action affects. Compare the recovered value with the approved source, not merely with the previous platform value. Examine partial failures by channel because a marketplace may accept, reject, or transform the same update differently. A manager can add staging checks, narrower batch sizes, reversible versioning, channel-specific verification, or an owner-only rule for consequential attributes. The study should not encourage broader delete or publish rights simply to improve rollback time. Repeat the exercise after platform migrations, feed mapping changes, new marketplaces, or changes to product-claim ownership. Preserve failed attempts and the next synchronization outcome. If recovery requires private knowledge held by one operator, the procedure is not ready even when the final display is correct. The supported decision is whether the queue can bound the error, restore a defensible state, and prove that state through the normal publishing path while internal owners retain commercial and policy authority.',
    conclusion: 'Safe rollback requires an identifiable approved state, bounded containment, reversible permission, preserved history, cross-channel proof, and survival of the next sync. Expand the queue only when recovery tests work without transferring commercial, safety, or policy authority.',
    sources: [['NIST Cybersecurity Framework 2.0', 'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'], ['NIST SP 800-53 Rev. 5', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'], ['OWASP Logging Cheat Sheet', 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html']]
  }
];

const body = (s: Study) => [
  `Research question: ${s.question} ${s.thesis}`,
  `Methodology: ${s.method}`,
  `Evidence scope: ${s.scope}`,
  `Case design: ${s.cases}`,
  `Time and sequence: ${s.clocks}`,
  `Facts and analysis: ${s.facts}`,
  `Measures: ${s.measures}`,
  `Role boundary: ${s.boundary}`,
  `Operating context: ${s.operations}`,
  'The Philippines context belongs in shift overlap, holidays, source access, language needs, and handoff design. It does not establish diligence, accuracy, integrity, or fit. Evaluate the observed queue, written rules, named permissions, and owner response path. Country-level claims cannot replace evidence about the measured process or an individual worker.',
  'Keep denominators and excluded cases visible. Preserve corrections, duplicates, unresolved items, and valid stops under stated rules. A dashboard can improve while risk worsens if difficult records disappear from the sample. Report small consequential categories separately and avoid converting a bounded observation into a universal benchmark or provider claim.',
  'Access should be named, minimal, and removable. Research records should contain only the information needed to reproduce the finding. The internal owner remains responsible for policy, legal, financial, privacy, security, employment, and customer-remedy decisions. Research on a queue is not permission to widen an outsourced role.',
  `Validation: ${s.validation}`,
  `Limitations: ${s.limitations}`,
  `Interpretation and management use: ${s.interpretation}`,
  'Before acting on a result, review the sampling frame, missing records, reviewer disagreements, and any changes made during observation. State which findings are direct measurements and which are management analysis. Keep the original evidence available to authorized reviewers under the applicable retention rule. A future review should be able to reproduce the denominator, locate the governing source, and explain why the conclusion stayed within the role and period studied.',
  `Evidence-led conclusion: ${s.conclusion}`
];

export const researchPosts2026_09_03: ResearchPost[] = studies.map(s => ({ slug: `philippines-outsourcing-september-3-${s.slug}`, title: s.title, excerpt: s.excerpt, updated, datePublished: updated, displayDate: 'September 3, 2026', image: s.image, imageAlt: s.title, body: body(s), sources: s.sources.map(([label, href]) => ({ label, href })), related, cta: 'Bring one recurring queue, its source records, decision boundaries, and review evidence to the staffing intake.' }));
