type T={slug:string;title:string;audience:string;artifact:string;boundary:string;exception:string};
const topics:T[]=[
['customer-complaint-triage-ledger','A complaint triage ledger that keeps promises with the owner','customer support leads','a ledger recording the complaint, evidence, severity rule, deadline, owner, and permitted next step','promise compensation, admit fault, or close a dispute','a safety concern appears inside a routine delivery complaint'],
['accounts-payable-duplicate-check','A practical duplicate-invoice check before payment review','finance operations managers','a packet matching vendor, amount, currency, invoice number, purchase order, receipt, and payment history','approve, reject, or release a payment','two invoice numbers describe the same shipment and amount'],
['crm-merge-review-queue','Build a safer CRM merge-review queue','revenue operations teams','a queue showing both records, stable IDs, match evidence, field conflicts, activity, and approver','merge records, overwrite a disputed field, or infer consent','two contacts share a domain but represent different legal entities'],
['order-address-change-hold','Handle late order-address changes without guesswork','ecommerce operations leads','a hold linking identity checks, order state, carrier cutoff, requested address, policy, and owner','change an address, bypass verification, or promise delivery','a request comes from a new email after label creation'],
['recruiting-interview-schedule-control','Keep interview scheduling fast without making hiring decisions','recruiting coordinators','a record of availability, interviewer constraints, approved stage, timezone, accommodations route, and owner','evaluate a candidate, change a stage, or disclose private feedback','a candidate requests an accommodation outside the standard script'],
['vendor-onboarding-missing-evidence','Route missing vendor-onboarding evidence cleanly','procurement managers','a checklist linking requirements to sources, artifacts, validation, expiry, discrepancies, and reviewer','waive a requirement, certify compliance, or activate a vendor','a current certificate names an affiliate instead of the contracting company'],
['weekly-kpi-denominator-check','Check KPI denominators before the weekly report goes out','operations analysts','a reconciliation of metric definition, eligible population, exclusions, query, refresh time, and sign-off','change a definition, hide missing data, or publish','the dashboard excludes reopened tickets that the written definition includes'],
['subscription-cancellation-handoff','Design a cancellation handoff customers can actually follow','subscription operations teams','a record of request channel, verified account, policy, effective date, balance, status, and owner','cancel service, waive fees, interpret law, or claim completion','immediate cancellation is requested despite an apparent notice period'],
['knowledge-base-expiry-review','Run a knowledge-base expiry review that preserves context','support enablement managers','a register of article owner, policy source, last validation, queue, broken evidence, disposition, and approval','publish, archive, or reconstruct policy from memory','a popular article conflicts with a newer policy of unclear effective date'],
['purchase-order-receipt-exception','Prepare purchase-order receipt exceptions for one clear decision','purchasing teams','a packet connecting the order, receipt, quantity, price, tolerance rule, correspondence, and buyer','amend an order, accept goods, approve an exception, or make a vendor commitment','quantity is within tolerance but unit price differs from the signed order'],
['service-outage-update-draft','Draft service-outage updates with an evidence checkpoint','incident communications leads','a timestamped draft based on confirmed impact, services, workaround, next update, and approver','declare cause, estimate recovery, or send externally','monitoring recovers while customer reports continue in one geography'],
['shared-mailbox-coverage-handoff','Make shared-mailbox coverage visible at shift change','back-office team leads','a handoff listing queue age, priority threads, completed actions, pending decisions, deadlines, and evidence','send a consequential reply, reclassify risk, or treat silence as approval','an unverified urgent message requests a banking-detail change'],
].map(([slug,title,audience,artifact,boundary,exception])=>({slug,title,audience,artifact,boundary,exception}));
const sections=(t:T)=>[
 {heading:'Define one reviewable handoff',body:[`For ${t.audience}, the useful output is ${t.artifact}. Each field should point to a source another person can reopen.`,`Train with one accepted and one rejected example. Agree what ready for review means before adding speed targets.`]},
 {heading:'Separate preparation from authority',body:[`A specialist may collect, compare, label, draft, and route under written rules. They must stop before they ${t.boundary}.`,'Put that boundary in the checklist and queue state. Name a primary and backup owner so a correct hold has a return path.']},
 {heading:'Preserve disagreements',body:['When sources conflict, retain both values with timestamps and identifiers. Ask one narrow question instead of silently selecting a convenient answer.',`Rehearse this exception: ${t.exception}. Preserve the evidence, apply the approved hold reason, and route it without inventing a rule.`]},
 {heading:'Review the eligible queue',body:['Track missing evidence, conflicts, owner returns, correction direction, aged holds, and reopenings. Report counts with denominators.','A correctly paused case can take longer than an unsafe closure. Read turnaround time beside evidence quality and boundary compliance.']},
 {heading:'Release a small first batch',body:['Practice on historical cases, then review every item in a limited live batch. Expand only when sources, permissions, escalation, and return paths work.',`Published September 7, 2026, this OutsourcedCompany.com guide is an operating pattern, not legal, financial, security, or employment advice.`]},
];
export const blogPosts2026_09_07=topics.map((t,i)=>({slug:`philippines-outsourcing-${t.slug}`,title:t.title,excerpt:`A Philippines outsourcing routine for ${t.title.toLowerCase()}, with traceable evidence, explicit limits, and owner review.`,minutes:9+(i%4)}));
export const blogDetails2026_09_07=Object.fromEntries(topics.map(t=>[`philippines-outsourcing-${t.slug}`,{updated:'2026-09-07',marker:`daily-blog-2026-09-07-${t.slug}`,takeaway:`Prepare ${t.artifact}. Keep consequential judgment with a named internal owner.`,comparison:[{weak:'Use judgment and finish the case quickly.',strong:'Follow the named source, preserve conflicts, and stop at the written boundary.'},{weak:'Ask a manager if anything seems unusual.',strong:'Apply a documented hold reason and route one specific question with evidence.'}],sections:sections(t),script:['Which source controls, and how can its version be verified?',`Where must the specialist stop before they ${t.boundary}?`,'Who is the backup owner, and where is the returned decision recorded?'],sources:[{name:'NIST Cybersecurity Framework 2.0',note:'Primary governance and control framework.',url:'https://www.nist.gov/publications/nist-cybersecurity-framework-csf-20'},{name:'Philippine National Privacy Commission: Data Privacy Act',note:'Primary Philippine privacy resource.',url:'https://privacy.gov.ph/data-privacy-act/'}],faqs:[{question:'Can the specialist resolve the exception?',answer:`Only under an explicit approved rule; otherwise stop before they ${t.boundary}.`},{question:'What should the owner inspect first?',answer:'Check source traceability, missing fields, the hold reason, and visible corrections.'}]}]));
