import { body, sources, type Study } from './article-research-batch-2026-09-24';

const published = '2026-09-28';
const displayDate = 'September 28, 2026';
const image = '/images/operations-meeting.jpg';

const studies: Study[] = [
  {
    slug: 'support-macro-change-control-study',
    title: 'Can a customer-support macro change be traced from request to approved release?',
    excerpt: 'A version-linked study of macro requests, approval, release, use, rollback, and customer-impact evidence.',
    service: 'customer experience support',
    question: 'For support macro changes released during a defined window, what proportion can be traced from a documented service problem to an approved version, controlled release, observed use, and any required rollback?',
    decision: 'whether macro drafting and release preparation can be delegated without delegating policy, legal, remedy, brand, or customer-communication decisions',
    population: 'every new or materially changed support macro first released during twelve consecutive weeks, including urgent corrections, translations, retired versions, rejected drafts, and rollbacks',
    unit: 'one approved macro version for one defined use case and channel, with edits and translations retained as linked versions rather than counted as independent improvements',
    fields: 'change ID, requesting owner, cited tickets, use case, channel, language, prior version, proposed wording, policy references, approvers, approval time, release event, eligible uses, overrides, complaints, rollback decision, retirement event, and terminal state',
    classes: 'approved and released, evidence incomplete, policy conflict, approval missing, wrong version used, translation pending, limited pilot, rolled back, superseded, retired, customer-impact review open, and unresolved',
    primary: 'the original change request, attributable ticket evidence, controlling policy, approved text, platform version history, and authorized rollback record; a copied reply or private draft is not a controlling macro',
    secondary: 'change counts, evidence coverage, approval coverage, release delay, wrong-version uses, override frequency, complaint links, rollback frequency, translation lag, and unresolved age',
    validation: 'A second reviewer reconstructs every rollback, policy conflict, and wrong-version use plus a random sample of ordinary releases without seeing the first classification.',
    scenario: 'A refund macro is edited after a product exception, but the draft broadens eligibility beyond the approved policy. Preserve the proposed text and route the conflict; the coordinator cannot infer a new remedy rule from several similar tickets.',
    boundary: 'Policy interpretation, legal claims, customer remedies, admissions, refund authority, brand standards, translation approval, risk acceptance, and final customer-facing wording remain with authorized owners.',
    risks: 'Agents may type variations, platforms can overwrite history, several macros can answer one issue, ticket outcomes may reflect product changes, and a complaint after release does not prove the macro caused it.',
    conclusion: 'Delegate support-macro administration only when the service evidence, controlling policy, approved version, release event, observed use, and rollback authority stay connected.',
    related: [{ label: 'Customer experience support', href: '/services/customer-experience-support' }, { label: 'Research index', href: '/research' }, { label: 'Request an operations brief', href: '/contact-us' }],
  },
  {
    slug: 'purchase-order-match-exception-study',
    title: 'Which purchase-order match exceptions are ready for an owner decision?',
    excerpt: 'A matched-record study of purchase orders, receipts, invoices, tolerances, decisions, corrections, and posting evidence.',
    service: 'finance operations support',
    question: 'Among invoice lines that fail an approved purchase-order match, which exception packets contain enough evidence for an authorized owner to approve, reject, correct, or investigate them?',
    decision: 'whether purchase-order exception preparation can be delegated without delegating accounting, payment, procurement, tax, fraud, or supplier-dispute decisions',
    population: 'all invoice lines first entering an exception state during three consecutive monthly closes, including partial receipts, price variances, duplicate candidates, credits, foreign-currency items, and reopened cases',
    unit: 'one invoice line matched to one purchase-order line and receipt set, retained under a stable exception identifier through corrections and resubmissions',
    fields: 'exception ID, supplier and invoice identifiers, purchase-order and line versions, receipt events, quantity, price, currency, tax flag, tolerance rule, variance calculation, duplicate candidates, supporting documents, required owner, decision, correction, posting reference, and terminal state',
    classes: 'packet ready, receipt missing, price variance, quantity variance, currency conflict, tax review needed, duplicate candidate, owner pending, approved exception, rejected, corrected, posted, reopened, and unresolved',
    primary: 'the approved purchase order, attributable receipt, supplier invoice, controlling tolerance rule, owner decision, and accounting-system event; an emailed explanation or spreadsheet match does not authorize posting or payment',
    secondary: 'exception lines and value bands, source coverage, variance distribution, duplicate prevalence, owner wait, correction frequency, approval outcomes, posting evidence, reopenings, and unresolved age',
    validation: 'Two reviewers independently reconstruct every duplicate candidate, tax flag, and reopened exception plus a random sample of posted lines against the frozen matching rule.',
    scenario: 'An invoice quantity exceeds the latest receipt, while a warehouse note describes goods still under inspection. Link the note without treating it as a receipt and route the variance; the coordinator cannot approve payment based on expected acceptance.',
    boundary: 'Accounting treatment, procurement commitments, tax, fraud conclusions, supplier disputes, tolerance policy, payment release, credits, write-offs, and final approval remain with accountable owners.',
    risks: 'Receipts can post late, purchase orders can be revised, units of measure can differ, taxes and currencies can distort simple comparisons, and duplicate detection can produce false matches.',
    conclusion: 'Outsource purchase-order exception preparation only when the order version, receipt, invoice, tolerance, owner decision, correction, and posting event remain reviewable.',
    related: [{ label: 'Finance operations support', href: '/services/finance-operations-support' }, { label: 'Research index', href: '/research' }, { label: 'Request an operations brief', href: '/contact-us' }],
  },
  {
    slug: 'candidate-interview-reschedule-study',
    title: 'Do candidate interview changes preserve a fair and usable scheduling record?',
    excerpt: 'An event-sequence study of interview invitations, availability, accommodations, changes, notices, attendance, and closure.',
    service: 'recruitment coordination',
    question: 'For interviews changed after the first confirmed invitation, how often can reviewers reconstruct the reason, authorized schedule, required notices, accommodation handling, and final attendance state?',
    decision: 'whether interview rescheduling can be delegated without delegating candidate evaluation, accommodation decisions, hiring priorities, employment terms, or exceptions to recruiting policy',
    population: 'every interview first confirmed and then changed during sixteen consecutive recruiting weeks, including candidate requests, interviewer conflicts, no-shows, cancellations, panel changes, and reopened requisitions',
    unit: 'one candidate-stage interview under a stable scheduling identifier, with each proposed and confirmed time preserved as an event rather than counted as a separate interview',
    fields: 'schedule ID, candidate and requisition pseudonyms, stage, invited panel, timezone, proposed times, confirmed time, change requester, reason class, accommodation flag, authorized decision route, notices, acknowledgements, attendance, disposition event, deletion rule, and terminal state',
    classes: 'changed and acknowledged, candidate confirmation missing, interviewer confirmation missing, timezone conflict, accommodation route active, panel changed, late cancellation, no-show disputed, rescheduled again, requisition paused, closed, and unresolved',
    primary: 'the approved interview plan, attributable availability responses, confirmed calendar event, accommodation route, authorized change record, and attendance evidence; a recruiter summary cannot replace the candidate communication',
    secondary: 'changed-interview counts, requester distribution, notice coverage, acknowledgement coverage, time to reconfirm, timezone conflicts, repeated changes, attendance states, withdrawals, and unresolved age',
    validation: 'A second reviewer reconstructs every accommodation-flagged, disputed no-show, and repeatedly changed interview plus a random sample of acknowledged changes.',
    scenario: 'A candidate accepts a time shown in one timezone, but a later calendar update shifts the displayed hour. Preserve both invitations and route the conflict promptly; the coordinator cannot label the candidate a no-show from the later event alone.',
    boundary: 'Candidate assessment, hiring priority, accommodation eligibility, employment-law interpretation, rejection, requisition changes, panel authority, offer timing, and exceptions remain with authorized owners.',
    risks: 'Calendar systems normalize timezones differently, candidate replies may arrive off-platform, interviewers can change without notice, privacy limits the accommodation record, and attendance does not prove a fair process.',
    conclusion: 'Staff interview rescheduling only when availability, timezone, authorized changes, accommodation routing, notices, acknowledgements, and attendance can be reconstructed without judging the candidate.',
    related: [{ label: 'Recruitment coordination', href: '/services/recruitment-coordination' }, { label: 'Research index', href: '/research' }, { label: 'Request an operations brief', href: '/contact-us' }],
  },
  {
    slug: 'marketing-suppression-request-study',
    title: 'Do marketing suppression requests reach every approved sending system?',
    excerpt: 'A propagation study of opt-out requests, identity matching, system scope, suppression events, exceptions, and later sends.',
    service: 'marketing operations support',
    question: 'For marketing opt-out requests received through approved channels, what proportion can be traced to the correct identities, required sending systems, suppression events, and any later-send investigation?',
    decision: 'whether suppression administration can be delegated without delegating consent, legal interpretation, identity exceptions, campaign purpose, or remediation decisions',
    population: 'all marketing opt-out requests first received during twelve consecutive weeks, including one-click events, replies, preference-center changes, duplicate identities, bounced addresses, and disputed later sends',
    unit: 'one suppression request for one reachable address or registered identity and stated scope, linked across systems under a stable request identifier',
    fields: 'request ID, source channel and time, address or pseudonymous identity, requested scope, identity matches, exception flag, system inventory version, required destinations, suppression events, propagation checks, later sends, investigation owner, correction, notice, and terminal state',
    classes: 'fully propagated, identity ambiguous, scope ambiguous, destination missing, suppression pending, exception review required, later send observed, test message excluded, corrected, notice pending, duplicate request, and unresolved',
    primary: 'the attributable request, approved identity-matching rule, current sending-system inventory, platform suppression events, and authorized exception decision; a spreadsheet flag does not prove that every sender stopped',
    secondary: 'request counts, identity-match coverage, destination coverage, propagation time, ambiguous scope, exception reviews, later-send frequency, correction time, notices, and unresolved age',
    validation: 'Two reviewers independently trace every later-send and exception-review case plus a random sample classified as fully propagated against the frozen system inventory.',
    scenario: 'A contact opts out by reply while the CRM and webinar platform hold different addresses for the same person. Apply only the approved matching rule, suppress the confirmed address, and route the possible link; the coordinator cannot merge identities by intuition.',
    boundary: 'Consent validity, statutory interpretation, identity resolution exceptions, transactional-message classification, campaign purpose, remediation, legal notice, and risk acceptance remain with authorized owners.',
    risks: 'Sending tools can sync slowly, aliases may hide identity links, transactional and marketing messages can share infrastructure, system inventories can be incomplete, and delivery logs may lag.',
    conclusion: 'Delegate suppression operations only when the request, identity rule, system scope, platform events, later-send checks, and exception authority remain connected.',
    related: [{ label: 'Marketing operations support', href: '/services/marketing-operations-support' }, { label: 'Research index', href: '/research' }, { label: 'Request an operations brief', href: '/contact-us' }],
  },
  {
    slug: 'knowledge-article-retirement-study',
    title: 'Which internal knowledge articles are ready to retire?',
    excerpt: 'A use-and-lineage study of knowledge ownership, source validity, dependencies, replacement guidance, approvals, and retirement.',
    service: 'back-office operations',
    question: 'Among internal knowledge articles flagged as stale or unused, which have sufficient evidence for an authorized owner to update, replace, archive, or retire them?',
    decision: 'whether knowledge-base lifecycle preparation can be delegated without delegating policy interpretation, process ownership, legal guidance, access decisions, or retirement approval',
    population: 'all internal knowledge articles flagged by an approved age, ownership, source-change, broken-link, or usage rule during two consecutive quarterly review cycles',
    unit: 'one published knowledge-article version under a stable identifier, linked to translations, embedded fragments, dependent workflows, replacements, and retirement events',
    fields: 'article ID and version, owner, audience, access class, source references, last verified date, usage definition and count, linked procedures, translations, search aliases, stale trigger, proposed action, replacement ID, approvers, redirect or archive event, and terminal state',
    classes: 'verified current, update packet ready, owner missing, source invalid, dependency unresolved, translation diverged, replacement approved, archived, retired with redirect, access review needed, reopened, and unresolved',
    primary: 'the versioned article, attributable controlling sources, approved ownership map, dependency inventory, authorized decision, and repository event; low page views or old age alone does not authorize retirement',
    secondary: 'flagged-article counts, owner coverage, source validity, dependency coverage, use under the frozen definition, translation divergence, decision wait, redirects, archive evidence, and unresolved age',
    validation: 'A second reviewer reconstructs every proposed retirement, access conflict, and missing-owner case plus a random sample verified as current using the same dependency rules.',
    scenario: 'An old troubleshooting article has few views but is linked from an incident runbook used only during outages. Preserve that dependency and route the decision; the coordinator cannot retire it from ordinary traffic alone.',
    boundary: 'Policy and process meaning, legal or safety guidance, access classification, authoritative-source selection, replacement adequacy, retention, archive scope, and final retirement remain with accountable owners.',
    risks: 'Usage logs can miss copied content, links can be embedded outside the knowledge platform, article owners may have changed roles, translations can lag, and rare-use guidance may still be critical.',
    conclusion: 'Outsource knowledge lifecycle preparation only when sources, owners, dependencies, usage definitions, replacements, approvals, and repository events can be inspected together.',
    related: [{ label: 'Back-office operations', href: '/services/back-office-operations' }, { label: 'Research index', href: '/research' }, { label: 'Request an operations brief', href: '/contact-us' }],
  },
];

const supplements: Record<string, string[]> = {
  'support-macro-change-control-study': [
    'Macro-specific exposure model. Build an eligible-use table from the routing categories and channels where each version was available. Count an exposure only when the case state met the registered use rule and the macro was actually inserted or its stable identifier was recorded. Separate insertion from sending, because an agent may edit or discard a draft. For each sent response, retain the version identifier, language, material edits, policy state, and downstream reopening or complaint link. This denominator lets the buyer distinguish adoption, unauthorized variation, and customer outcome without treating every ticket handled during the release window as exposed.',
    'Release analysis. Compare the proposed wording line by line with the prior approved version and classify changes as factual instruction, eligibility statement, required disclosure, tone, personalization token, link, or escalation language. The approver matrix should state which classes need policy, legal, brand, or service-owner review. Measure release lag from final approval rather than initial request, and verify that cached, localized, mobile, and fallback versions changed together. A partial platform update is a deployment exception even when the primary agent view looks correct. Preserve screenshots only when permitted; prefer version exports and platform events that can be searched and reproduced.',
    'Rollback decision. Register signals that trigger review, such as a wrong eligibility statement, missing safety route, broken link, sustained override pattern, or attributable complaint cluster. A trigger opens review; it does not prove harm or require automatic withdrawal. The authorized owner decides whether to disable, narrow, correct, or continue the macro. During review, show how many eligible cases received each version, how many were materially edited, and whether later outcomes differed in observable ways. This turns a vague concern about canned replies into a reversible operating decision with an explicit blast radius.',
  ],
  'purchase-order-match-exception-study': [
    'Match-specific reconstruction. Normalize quantities only with an approved unit-of-measure table and preserve both original and normalized values. Join invoice, order, and receipt lines using stable identifiers before using supplier name, description, price, or date as secondary evidence. Split an invoice line only when the accounting system retains the relationship. For services, replace warehouse receipt with the buyer-approved acceptance event; do not invent a receipt from a project update. The exception file should show the exact order version and tolerance effective when the invoice entered review, not whichever rule exists when the analysis is exported.',
    'Variance analysis. Report price, quantity, tax, currency, freight, duplicate, and missing-reference exceptions separately because each needs different evidence and owners. For price variance, display ordered and invoiced unit prices, currency, conversion source if applicable, absolute difference, and registered tolerance calculation. For quantity variance, display ordered, accepted, previously invoiced, and currently invoiced quantities. Duplicate screening should expose the fields that generated a candidate and the reason a reviewer kept or rejected the link. Never combine candidates with confirmed duplicates in a savings total; the study observes review evidence, not recovered money.',
    'Close control. An owner approval is not the same event as a corrected invoice, accounting post, or payment release. Trace each separately and retain reversals. Sample exceptions that disappeared from the queue to learn whether they were resolved, deleted, rekeyed, or moved to another system. Compare owner waiting time only among packets meeting the frozen readiness rule, otherwise missing evidence can masquerade as slow approval. The staffing decision should consider whether specialists can assemble reliable packets and whether internal owners have capacity to decide them, rather than claiming that faster preparation guarantees a faster close.',
  ],
  'candidate-interview-reschedule-study': [
    'Schedule-specific event model. Store proposed, accepted, changed, cancelled, and attended events with the original timestamp, timezone label, UTC equivalent, sender, recipient set, and calendar identifier. Do not overwrite the first confirmation when a later invitation arrives. Define acknowledgement as an attributable candidate response or approved system event, not email delivery. Record interviewer acknowledgement independently. When a panel member changes, retain the role in the panel and the authority for the substitution without exposing unnecessary personal notes. These rules make it possible to distinguish a valid reschedule from a calendar mutation that only one party saw.',
    'Fairness review. Group operational results by registered change requester, stage, notice band, timezone relationship, and accommodation-route presence, while suppressing small cells. Do not compare selection or hiring outcomes as evidence that scheduling caused them. Instead examine repeated changes, acknowledgement gaps, disputed no-shows, and withdrawals recorded after a change. An accommodation flag should reveal only that the protected route was used and whether required scheduling actions occurred; the analysis file should not contain diagnosis or confidential rationale. Any disparity is a review signal for the authorized recruiting owner, not a judgment about candidates or interviewers.',
    'Service rule. Set a response clock for ordinary changes and a separate urgent path for changes near the interview start. The clock pauses only under named states, such as waiting for candidate availability or an authorized accommodation decision. Test communications across daylight-saving transitions and calendar clients before relying on automatic timezone rendering. A coordinator can offer times within an approved availability envelope, but must return conflicts involving required panel composition, candidate hardship, accommodation, requisition pause, or policy exception. The buyer should staff this queue only if those boundaries and a backup owner make timely, respectful recovery possible.',
  ],
  'marketing-suppression-request-study': [
    'Suppression-specific system map. Freeze the inventory of campaign platforms, CRM automations, webinar tools, uploaded audience destinations, agency senders, and manual lists that can originate marketing messages. For each destination record the identity key, scope semantics, normal propagation method, expected latency, evidence event, and accountable owner. Test the map with synthetic identities where policy permits. A platform appearing in the inventory is not evidence of successful suppression; the study needs an attributable destination event or a documented exception. Likewise, a global CRM flag is insufficient when a downstream tool can continue sending from an older audience export.',
    'Identity and scope analysis. Treat exact-address matches, approved alias links, customer-record links, and inferred household or company relationships as different classes. Apply broader suppression only when the buyer has approved that rule. Preserve the request wording so reviewers can distinguish one newsletter, a brand, a channel, or all marketing. Record transactional-message exceptions without deciding them, and test whether the platform represents those scopes accurately. Report ambiguous identities and scopes in the denominator instead of silently choosing the broadest or narrowest interpretation. This protects both the requester and the integrity of the measurement.',
    'Later-send investigation. Join post-request delivery events using message purpose, campaign, sender, destination, queued time, send time, and suppression-check time. A message queued before the request, a permitted transactional notice, a test, and a marketing send after confirmed propagation are materially different events. Preserve the classification rule and owner decision for each candidate. Measure time from receipt to each required destination and show the slowest unresolved destination rather than only an average. The staffing question is whether a specialist can maintain this evidence and surface failures quickly; legal conclusions, remediation, and contact decisions stay outside the delegated queue.',
  ],
  'knowledge-article-retirement-study': [
    'Knowledge-specific dependency map. Enumerate direct links, embedded fragments, search aliases, chatbot retrieval sources, onboarding checklists, incident runbooks, translations, exports, and API consumers for each flagged version. Record when and how each dependency was checked. Traffic analytics should distinguish human views, automated retrieval, author previews, and unavailable measurement. A zero in an incomplete log is unknown, not unused. Rare operational or safety guidance may be important precisely because its triggering event is uncommon, so usage can inform an owner decision but cannot replace source validity and dependency evidence.',
    'Source validity review. Break the article into decision-bearing claims, procedures, contact routes, screenshots, forms, and links. For each element identify the controlling source, owner, last verified event, and whether the source still supports it. Classify an article as partially stale when current and invalid elements coexist; avoid a single stale label that hides what readers may still rely on. Compare translations with the approved source version by material instruction rather than publication date alone. Where ownership is missing, route the article through the approved function map instead of assigning ownership to the most recent editor.',
    'Retirement design. A retirement packet should name the replacement, redirect behavior, search treatment, archive location, access rules, dependent updates, communication audience, effective time, and rollback plan. Test old bookmarks, internal links, embedded fragments, and search terms after a staged change. Archive evidence should demonstrate preservation under the buyer rule without leaving obsolete guidance discoverable as current. Review help requests or failed searches during the observation window, but do not assume every later question was caused by retirement. Delegation is appropriate when specialists can make dependencies visible and execute an approved plan; adequacy and risk acceptance remain owner decisions.',
  ],
};

export const researchPosts2026_09_28 = studies.map((study) => ({
  slug: `philippines-outsourcing-${study.slug}`,
  title: study.title,
  excerpt: study.excerpt,
  updated: published,
  datePublished: published,
  displayDate,
  image,
  imageAlt: 'Operations colleagues reviewing a documented workflow at a meeting table',
  body: [...body(study).map((paragraph) => paragraph.replaceAll('September 24, 2026', 'September 28, 2026')), ...supplements[study.slug]],
  sources: sources.map((source) => ({ ...source, label: source.label.replaceAll('September 24, 2026', 'September 28, 2026') })),
  related: study.related,
  cta: `Bring one ${study.service} queue, its source records, and its owner boundaries to the staffing intake.`,
}));
