type Row = {
  slug: string;
  title: string;
  subject: string;
  audience: string;
  steps: [string, string, string];
  stop: string;
  angle: string;
  date: string;
};

const rawRows: [string, string, string, string, [string, string, string], string, string][] = [
  ['outsourcing-cash-application-philippines', 'Outsourcing cash application to the Philippines', 'cash application', 'finance operations managers', ['open the approved remittance file', 'match receipts to the correct account', 'list unapplied cash for review'], 'Stop before moving a receipt between accounts, clearing a disputed item, or changing a bank record.', 'The safest first lane is matching and exception listing, not deciding what an ambiguous payment means.'],
  ['philippines-outsourcing-client-onboarding-admin', 'Philippines outsourcing client onboarding administration', 'client onboarding administration', 'professional services leaders', ['check the signed handoff', 'create the approved client record', 'list missing onboarding items'], 'Stop before accepting terms, certifying compliance, or deciding whether a client is ready to begin.', 'Good onboarding administration keeps promises visible by separating record preparation from approval.'],
  ['outsourcing-subscription-administration-philippines', 'Outsourcing subscription administration to the Philippines', 'subscription administration', 'customer operations teams', ['review the approved change request', 'update allowed subscription fields', 'record the confirmation and exception'], 'Stop before changing a plan, granting a credit, cancelling service, or overriding a billing rule.', 'A narrow subscription queue can remove repetitive record work while keeping customer and revenue decisions with the owner.'],
  ['philippines-outsourcing-field-service-dispatch', 'Philippines outsourcing field service dispatch support', 'field service dispatch', 'service operations managers', ['read the approved work order', 'offer an allowed appointment window', 'route access or safety constraints'], 'Stop when a technician, safety condition, emergency, or customer promise requires an operational judgment.', 'Dispatch support works when availability is visible and the specialist has a clear route for constraints.'],
  ['outsourcing-compliance-document-collection-philippines', 'Outsourcing compliance document collection to the Philippines', 'compliance document collection', 'operations and compliance teams', ['request the named document', 'check the required fields and date', 'route gaps to the responsible owner'], 'Stop before interpreting a regulation, approving evidence, or declaring a person or vendor compliant.', 'Collection is repeatable; compliance judgment is not. The brief should make that boundary explicit.'],
  ['philippines-outsourcing-customer-feedback-coding', 'Philippines outsourcing customer feedback coding', 'customer feedback coding', 'customer experience leaders', ['apply the approved feedback categories', 'capture the supporting comment', 'group repeated themes for review'], 'Stop when a message signals safety, discrimination, a legal claim, or a category the current guide does not cover.', 'Consistent coding helps leaders see patterns without pretending that a label is the same as a decision.'],
  ['outsourcing-appointment-intake-philippines', 'Outsourcing appointment intake to the Philippines', 'appointment intake', 'service business owners', ['capture the requested service', 'check the approved intake fields', 'route exceptions before booking'], 'Stop before diagnosing a need, promising an unavailable service, or selecting a priority outside the written rule.', 'Intake should make the next human decision easier, not quietly make it on the customer’s behalf.'],
  ['philippines-outsourcing-expense-receipt-preparation', 'Philippines outsourcing expense receipt preparation', 'expense receipt preparation', 'small business finance teams', ['collect the approved receipt set', 'match each receipt to its source transaction', 'list missing or uncertain details'], 'Stop before approving a reimbursement, choosing an uncertain accounting treatment, or releasing payment.', 'Preparation support is useful when every unresolved item stays visible to the finance owner.'],
  ['outsourcing-inventory-receiving-philippines', 'Outsourcing inventory receiving administration to the Philippines', 'inventory receiving administration', 'warehouse and ecommerce operators', ['compare the delivery to the purchase record', 'record allowed receiving fields', 'route shortages and damage'], 'Stop before changing inventory availability, accepting a disputed quantity, or approving a supplier claim.', 'A receiving queue needs a source record, a physical discrepancy path, and a person who owns adjustments.'],
  ['philippines-outsourcing-vendor-certificate-tracking', 'Philippines outsourcing vendor certificate tracking', 'vendor certificate tracking', 'procurement and operations teams', ['open the vendor register', 'check certificate type and expiry', 'route missing or expired documents'], 'Stop before deciding whether a document satisfies a legal or insurance requirement.', 'Tracking dates and document presence is different from deciding whether risk is acceptable.'],
  ['outsourcing-sales-quote-administration-philippines', 'Outsourcing sales quote administration to the Philippines', 'sales quote administration', 'sales operations leaders', ['prepare the approved quote fields', 'check product and customer records', 'route terms for seller approval'], 'Stop before changing price, discount, scope, terms, or a customer commitment.', 'Administrative help should shorten quote preparation while leaving commercial judgment with the seller.'],
  ['philippines-outsourcing-renewal-coordination', 'Philippines outsourcing renewal coordination', 'renewal coordination', 'customer success and sales teams', ['list upcoming renewal records', 'check the approved contact and dates', 'prepare the owner’s follow-up queue'], 'Stop before making a renewal promise, changing terms, or deciding whether an account should be retained.', 'The useful output is a clean, timely queue for the person who owns the relationship.'],
  ['outsourcing-shipping-exception-administration-philippines', 'Outsourcing shipping exception administration to the Philippines', 'shipping exception administration', 'ecommerce operations teams', ['compare the carrier update with the order', 'classify the exception using the guide', 'route the customer-impacting case'], 'Stop before promising delivery, changing an address, issuing a remedy, or disputing a carrier charge.', 'A bounded exception queue gives operators context without turning an administrator into the decision maker.'],
  ['philippines-outsourcing-membership-administration', 'Philippines outsourcing membership administration', 'membership administration', 'associations and subscription businesses', ['verify the approved member request', 'update allowed profile fields', 'record the status and next step'], 'Stop before changing eligibility, granting an exception, or exposing another member’s information.', 'Membership records need careful identity checks and a clear distinction between updates and eligibility decisions.'],
  ['outsourcing-property-listing-administration-philippines', 'Outsourcing property listing administration to the Philippines', 'property listing administration', 'property management and real estate teams', ['load approved listing changes', 'check required fields and media status', 'route claims or pricing changes'], 'Stop before changing rent, making a property claim, or publishing information without owner approval.', 'Listing support is a good candidate for structured administration when every public claim has an accountable owner.'],
  ['philippines-outsourcing-return-intake', 'Philippines outsourcing ecommerce return intake', 'ecommerce return intake', 'online retail operations teams', ['capture the order and return reason', 'check the published eligibility rule', 'route exceptions with evidence'], 'Stop before approving a policy exception, issuing a refund, or deciding the condition of returned goods.', 'Intake can make returns faster while approvals and customer remedies remain controlled.'],
  ['outsourcing-payroll-input-preparation-philippines', 'Outsourcing payroll input preparation to the Philippines', 'payroll input preparation', 'people operations and finance teams', ['collect approved attendance changes', 'compare inputs with the source record', 'list unresolved items for payroll review'], 'Stop before calculating final pay, changing employee status, or submitting a payroll run.', 'Preparation reduces rework only when sensitive decisions and final submission stay with the authorized payroll owner.'],
  ['philippines-outsourcing-marketplace-seller-support', 'Philippines outsourcing marketplace seller support', 'marketplace seller support', 'ecommerce marketplace operators', ['classify the seller request', 'use the approved help source', 'route account or policy exceptions'], 'Stop before changing seller status, releasing funds, or deciding a policy dispute.', 'A clear support queue can improve response consistency without giving the role authority over seller outcomes.'],
  ['outsourcing-technical-support-ticket-triage-philippines', 'Outsourcing technical support ticket triage to the Philippines', 'technical support ticket triage', 'software and service operations teams', ['identify the product and symptom', 'apply the approved severity rule', 'route the ticket with useful context'], 'Stop before diagnosing beyond the guide, changing production systems, or promising a fix date.', 'Triage is valuable when it improves context and routing rather than creating unsupported technical promises.'],
  ['philippines-outsourcing-event-registration-admin', 'Philippines outsourcing event registration administration', 'event registration administration', 'events and community teams', ['check the approved registration record', 'send the correct event instruction', 'route accessibility or payment questions'], 'Stop before changing eligibility, waiving a requirement, or handling a payment exception.', 'Registration support should make attendance records reliable while preserving the organizer’s decisions.'],
  ['outsourcing-contract-repository-administration-philippines', 'Outsourcing contract repository administration to the Philippines', 'contract repository administration', 'legal operations and procurement teams', ['index the approved agreement', 'check the metadata against the source', 'route missing signatures or dates'], 'Stop before interpreting terms, approving a contract, or deciding whether an obligation has been met.', 'A well-indexed repository helps owners find commitments without asking an administrator to interpret them.'],
  ['philippines-outsourcing-travel-booking-administration', 'Philippines outsourcing business travel booking administration', 'business travel booking administration', 'executive and operations teams', ['collect the approved itinerary request', 'check traveler and policy fields', 'route exceptions for approval'], 'Stop before choosing an out-of-policy option, changing a traveler record, or promising reimbursement.', 'Travel administration is about accurate options and records; policy exceptions belong to the named approver.'],
];

const rows: Row[] = rawRows.map(([slug, title, subject, audience, steps, stop, angle]) => ({ slug, title, subject, audience, steps, stop, angle, date: '2026-08-13' }));

const details = (row: Row, index: number) => ({
  updated: row.date,
  keyword: row.title.toLowerCase(),
  marker: `daily-blog-batch-2026-08-13-${String(index + 1).padStart(2, '0')}`,
  takeaway: `${row.angle} Filipino specialists can handle the repeatable checks when the source, finish rule, access, and escalation owner are written down before the queue opens.`,
  comparison: [
    { weak: `We need help with ${row.subject}.`, strong: `Complete the approved ${row.subject} queue, record each result, and stop at the written exception boundary.` },
    { weak: 'Quality means keeping up with the queue.', strong: 'Review the source, record, action, note, and escalation for the same sample of early work.' },
    { weak: 'Give the role access to the system.', strong: 'Use a named account with only the permissions needed for this lane; approval and administration stay with the owner.' },
  ],
  sections: [
    { heading: `Choose the right ${row.subject} lane`, body: [`Start by naming which records enter the queue, where they arrive, how often they arrive, and what a complete item looks like. Add one normal example and one incomplete example to the brief.`, `Keep neighboring responsibilities out of the first assignment. A narrow lane lets ${row.audience} review accuracy without confusing activity with a correct result.`] },
    { heading: 'Write the normal handoff', body: [`A practical path is: ${row.steps[0]}, then ${row.steps[1]}, then ${row.steps[2]}. Put the source of truth beside each step and name the field or record that proves completion.`, 'For blocked work, record the identifier, action already taken, missing information, and person who owns the next answer.'] },
    { heading: 'Separate administration from judgment', body: [`The specialist needs a clear stop rule. ${row.stop}`, 'A stop rule works only when the internal owner and expected response window are named. Otherwise normal work becomes a queue of unanswered questions.'] },
    { heading: 'Protect the record and the customer', body: ['Use named accounts, the lowest practical permission, and the approved system of record. Separate reading, drafting, sending, approving, exporting, deleting, and administration.', 'Use masked examples or a test space for training. Do not copy live personal information into an informal worksheet just to make review easier.'] },
    { heading: 'Review before expanding the role', body: ['Check the first batch against the same fields: correct source, correct record, complete action, accurate note, and proper escalation. Record the cause of a miss so the remedy fits the problem.', `Add another responsibility only when the ${row.subject} lane has a stable source, a repeatable review, and no unresolved ownership gap.`] },
  ],
  workflow: [
    { step: 'Days 1–3', title: 'Map the source', body: `Document examples, access, schedule, finish rule, and stop rules for ${row.subject}.` },
    { step: 'Days 4–8', title: 'Test three cases', body: 'Use a normal case, an incomplete case, and an exception case with the same review fields.' },
    { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or masked historical work and review every result before live access.' },
    { step: 'Days 15–21', title: 'Open one lane', body: 'Keep live volume small and make the named owner available for blocked cases.' },
    { step: 'Days 22–30', title: 'Repair the guide', body: 'Group misses by cause, update the instructions, and confirm the change with a new sample.' },
  ],
  script: [`Which exact ${row.subject} cases belong in the first queue?`, 'What evidence proves a normal item is complete?', `Which decisions stay with ${row.audience}, and who answers an exception?`, 'Which named accounts are needed, and when will access be removed?'],
  sourcesNumbered: true,
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Reference for organizing access, risk, response, and recovery practices around business work.' }],
  faqs: [
    { question: `What should be outsourced first in ${row.subject}?`, answer: 'Start with recurring work that has examples, a visible finish, limited access, and a named reviewer. Keep judgment and approvals with the appropriate owner.' },
    { question: 'How should the first batch be reviewed?', answer: 'Use the same source, field, action, note, and escalation checks for every item, then record the cause of each miss.' },
    { question: 'When should the specialist stop?', answer: row.stop },
  ],
  relatedLinks: [{ label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' }, { label: 'Use the quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' }, { label: 'See back-office operations support', href: '/services/back-office-operations' }],
});

export const blogBatch2026_08_13Posts = rows.map((row) => ({ slug: row.slug, title: row.title, excerpt: `A practical ${row.subject} guide for setting a clear queue, limited access, and an owner for exceptions.`, minutes: 10 }));
export const blogBatch2026_08_13Details = Object.fromEntries(rows.map((row, index) => [row.slug, details(row, index)]));
