export type ResearchPost = { slug:string; title:string; excerpt:string; updated:string; image:string; imageAlt:string; body:string[]; sources:Array<{label:string;href:string}>; related:Array<{label:string;href:string}>; cta:string };
const topics = [
 ['philippines-outsourcing-market-overview','Philippines outsourcing market overview','A sourced starting point for understanding the Philippines service workforce, without treating broad labor data as a promise about one provider.'],
 ['philippines-outsourcing-service-workforce','What service-workforce data can tell an outsourcing buyer','Use labor statistics as context, then test the actual queue, schedule, communication, and review system before choosing a partner.'],
 ['philippines-data-privacy-outsourcing','Data privacy questions for Philippines outsourcing','A practical research note on access, processor responsibilities, and the questions to take to qualified privacy counsel.'],
 ['philippines-outsourcing-time-zone-planning','Time-zone planning for a Philippines support team','Plan overlap, handoffs, holidays, and response windows with UTC+8 in mind.'],
 ['philippines-outsourcing-quality-measurement','How to measure outsourced operations quality','A research-backed way to define a reviewable result, sample early work, and repair the process behind recurring misses.'],
 ['philippines-outsourcing-business-continuity-research','Business continuity research for outsourced queues','Keep a small operations lane moving when a person, tool, source, or connection is unavailable.'],
 ['philippines-outsourcing-cybersecurity-basics','Cybersecurity basics for a Philippines outsourcing handoff','Use least privilege, named accounts, and recovery planning before granting access to a recurring queue.'],
 ['philippines-outsourcing-customer-support-benchmarks','Customer-support benchmarks: what to define first','Benchmarks only help after channel, case type, service window, quality, and escalation definitions are written.'],
 ['philippines-outsourcing-hiring-work-sample-research','Why work samples matter in outsourcing hiring','A bounded work sample tests the written queue more fairly than vague claims about being organized or hardworking.'],
 ['philippines-outsourcing-vendor-due-diligence','Outsourcing vendor due diligence checklist','Questions for comparing staffing and managed-service partners on the system behind the sales promise.'],
] as const;
export const researchPosts: ResearchPost[] = topics.map(([slug,title,excerpt], index) => ({slug,title,excerpt,updated:'2026-08-07',image:'/images/operations-meeting.jpg',imageAlt:'Operations team reviewing a work queue together',body:[`${title} starts with context, not a generic promise. Name the queue, source of truth, due time, allowed action, evidence to save, and internal owner before asking another team to perform it.`,`The useful evidence here is directional rather than a guarantee about any individual worker or provider. Compare the published source with your own work sample, access review, manager capacity, and first-batch results. Keep policy, money, legal, safety, and customer-exception decisions with the appropriate owner.`,`For a safe first release, use named accounts and the lowest permissions needed. Review every item in the first small batch, record whether a miss came from the source, rule, training, tool, or action, and repair the cause before expanding the queue.`,`Write five normal cases, one incomplete case, and one escalation case. Ask the partner or candidate to show the source used, result, handoff note, and exact point where they would stop.`],sources:[{label:'NIST Cybersecurity Framework 2.0',href:'https://www.nist.gov/cyberframework'},{label:'World Bank Philippines data',href:'https://data.worldbank.org/country/philippines'},...(index===2?[{label:'Philippines National Privacy Commission',href:'https://privacy.gov.ph/data-privacy-act/'}]:[])],related:[{label:'Read the outsourcing buyer guide',href:'/blog/outsource-to-the-philippines-guide'},{label:'Review the quality checklist',href:'/blog/philippines-outsourcing-quality-assurance-checklist'},{label:'Start a conversation',href:'/contact'}],cta:'Have a recurring queue to scope? Bring the source, examples, access needs, and review owner to the staffing intake.'}));
