type Topic = {
  slug: string;
  title: string;
  keyword: string;
  excerpt: string;
  focus: string;
  steps: string[];
  stop: string;
};

type TopicRow = [string, string, string, string, string, string[], string];

const topics: Topic[] = ([
  ['outsource-back-office-operations-philippines', 'Outsource back-office operations to the Philippines: a practical plan', 'outsource back-office operations Philippines', 'Move repeatable back-office work with a written queue, limited access, and an owner who checks the first batch.', 'back-office operations', ['invoice and order records', 'shared inbox sorting', 'weekly status reports'], 'Stop when a source record is missing, a payment detail changes, or a policy choice is required.'],
  ['philippines-outsourcing-invoice-processing-checklist', 'Philippines outsourcing invoice processing checklist', 'Philippines outsourcing invoice processing', 'Set up invoice processing with source checks, approval limits, and a clear route for exceptions.', 'invoice processing', ['collect invoices', 'check required fields', 'route approved records'], 'Stop before changing vendor bank details, approving an exception, or releasing a payment.'],
  ['philippines-outsourcing-crm-cleanup-guide', 'Philippines outsourcing CRM cleanup: a safe first queue', 'Philippines outsourcing CRM cleanup', 'Give a Filipino operations specialist a CRM cleanup queue that is easy to review and hard to misuse.', 'CRM cleanup', ['find duplicate records', 'standardize allowed fields', 'log uncertain matches'], 'Stop when two records may represent different people, an owner is unclear, or a consent field is involved.'],
  ['philippines-outsourcing-email-management-plan', 'Philippines outsourcing email management plan', 'Philippines outsourcing email management', 'Turn an overloaded inbox into a triage role with response rules, escalation labels, and a daily handoff.', 'email management', ['sort by written categories', 'draft approved replies', 'route sensitive messages'], 'Stop on legal threats, safety reports, angry escalations, or any reply that creates a new company promise.'],
  ['philippines-outsourcing-calendar-management-checklist', 'Philippines outsourcing calendar management checklist', 'Philippines outsourcing calendar management', 'Hand off calendar coordination without giving away judgment about priorities, confidential meetings, or commitments.', 'calendar management', ['collect availability', 'offer approved windows', 'confirm the final meeting'], 'Stop when attendees conflict, a confidential event is exposed, or the meeting changes a priority.'],
  ['philippines-outsourcing-data-entry-quality-checklist', 'Philippines outsourcing data entry quality checklist', 'Philippines outsourcing data entry', 'Design a data-entry queue around examples, field-level checks, and a correction log your team can act on.', 'data entry', ['prepare the source set', 'enter only allowed fields', 'sample and correct records'], 'Stop when the source conflicts, a required field is ambiguous, or a record contains sensitive information outside scope.'],
  ['philippines-outsourcing-order-management-guide', 'Philippines outsourcing order management guide', 'Philippines outsourcing order management', 'Scope order updates around an approved system of record, customer-safe replies, and fulfillment escalation rules.', 'order management', ['read the order record', 'update allowed status fields', 'send the approved next step'], 'Stop before changing prices, promising an unapproved date, cancelling an order, or issuing a refund.'],
  ['philippines-outsourcing-customer-support-handoff', 'Philippines outsourcing customer support handoff', 'Philippines outsourcing customer support handoff', 'Create a customer support handoff that protects the customer promise and makes manager review visible.', 'customer support', ['identify the case', 'use the approved answer', 'close or escalate with context'], 'Stop for threats, fraud indicators, safety issues, policy exceptions, and complaints that need an owner.'],
  ['philippines-outsourcing-lead-research-process', 'Philippines outsourcing lead research process', 'Philippines outsourcing lead research', 'Build a research queue with source requirements, fit fields, and a rule against guessing personal or company data.', 'lead research', ['search approved sources', 'record evidence and date', 'flag uncertain matches'], 'Stop when identity is uncertain, a source conflicts, or a contact decision would require a legal or compliance judgment.'],
  ['philippines-outsourcing-sales-administration-plan', 'Philippines outsourcing sales administration plan', 'Philippines outsourcing sales administration', 'Separate sales administration from sales judgment with clear CRM updates, meeting notes, and approval boundaries.', 'sales administration', ['prepare records', 'update agreed stages', 'send approved follow-ups'], 'Stop before changing deal terms, making a promise, qualifying a sensitive case, or deciding whether a lead is legally usable.'],
  ['philippines-outsourcing-recruitment-coordination-checklist', 'Philippines outsourcing recruitment coordination checklist', 'Philippines outsourcing recruitment coordination', 'Use Filipino coordination support for scheduling and records while keeping hiring decisions with the responsible manager.', 'recruitment coordination', ['schedule approved interviews', 'maintain candidate records', 'send approved instructions'], 'Stop before ranking candidates, changing selection criteria, sharing protected information, or making an employment decision.'],
  ['philippines-outsourcing-project-coordination-guide', 'Philippines outsourcing project coordination guide', 'Philippines outsourcing project coordination', 'Give a project coordinator a visible task board, a meeting rhythm, and a route for decisions they cannot make.', 'project coordination', ['maintain the task board', 'prepare the weekly status', 'surface blocked work'], 'Stop when scope, budget, deadline, or priority must change. Name the project owner in the handoff.'],
  ['philippines-outsourcing-quality-review-process', 'Philippines outsourcing quality review process', 'Philippines outsourcing quality review', 'Make outsourced quality review fair by defining the sample, the fields, the error causes, and the repair owner.', 'quality review', ['select a stated sample', 'record field-level misses', 'separate coaching from process repair'], 'Stop when the review standard is unclear, evidence is incomplete, or a finding could affect employment without proper management review.'],
  ['philippines-outsourcing-knowledge-base-maintenance', 'Philippines outsourcing knowledge-base maintenance plan', 'Philippines outsourcing knowledge base', 'Keep support guidance current with source ownership, change review, and a rule that prevents stale instructions reaching customers.', 'knowledge-base maintenance', ['collect change requests', 'compare the approved source', 'route edits for review'], 'Stop before publishing a policy change, legal guidance, pricing statement, or customer promise without its owner’s approval.'],
  ['philippines-outsourcing-ecommerce-catalog-checklist', 'Philippines outsourcing ecommerce catalog checklist', 'Philippines outsourcing ecommerce catalog', 'Manage catalog updates with a source file, preview checks, and a separate approval for prices, claims, and availability.', 'ecommerce catalog work', ['prepare approved product fields', 'check the preview', 'log the release'], 'Stop before changing price, product claims, tax treatment, inventory rules, or an image that may be licensed.'],
  ['philippines-outsourcing-vendor-management-guide', 'Philippines outsourcing vendor management guide', 'Philippines outsourcing vendor management', 'Coordinate vendor records and follow-ups while retaining approval of contracts, payments, and risk decisions.', 'vendor management', ['maintain the vendor register', 'request missing documents', 'prepare an owner review'], 'Stop when banking details, contract terms, insurance, legal risk, or a new vendor decision is involved.'],
  ['philippines-outsourcing-reporting-dashboard-plan', 'Philippines outsourcing reporting dashboard plan', 'Philippines outsourcing reporting dashboard', 'Build repeatable reporting support around named metrics, source definitions, and a review note for every unusual result.', 'reporting dashboards', ['refresh the approved source', 'check the definitions', 'explain changes without guessing'], 'Stop when a metric definition changes, a source is incomplete, or the result will drive a financial or personnel decision.'],
  ['philippines-outsourcing-social-media-moderation-guide', 'Philippines outsourcing social media moderation guide', 'Philippines outsourcing social media moderation', 'Scope moderation with a written policy, evidence handling, and an escalation route for threats and sensitive complaints.', 'social moderation', ['classify by policy', 'hide or respond only as approved', 'record and route exceptions'], 'Stop on threats, self-harm, discrimination, legal notices, doxxing, or any case the policy does not cover.'],
  ['philippines-outsourcing-research-assistant-first-tasks', 'Research assistant in the Philippines: first tasks to outsource', 'research assistant Philippines first tasks', 'Start a research assistant with bounded source collection, dated notes, and a clear line between evidence and recommendation.', 'research assistance', ['search named sources', 'capture links and dates', 'summarize without inventing conclusions'], 'Stop when the request requires professional advice, private data, paid access, or a conclusion not supported by the sources.'],
  ['philippines-outsourcing-month-end-close-support', 'Philippines outsourcing month-end close support', 'Philippines outsourcing month-end close support', 'Use operations support for preparation and reconciliation while keeping accounting judgments and final sign-off with your finance owner.', 'month-end close support', ['collect the close checklist', 'match records to approved sources', 'prepare exceptions for review'], 'Stop before posting a journal, changing a reconciliation rule, approving a payment, or signing off financial statements.'],
] as TopicRow[]).map(([slug, title, keyword, excerpt, focus, steps, stop]) => ({ slug, title, keyword, excerpt, focus, steps, stop }));

const makeDetails = (topic: Topic, index: number) => ({
  updated: '2026-08-07',
  keyword: topic.keyword,
  marker: `daily-blog-batch-2026-${String(index + 1).padStart(2, '0')}`,
  takeaway: `A reliable ${topic.focus} handoff starts with one queue, a visible done check, and a named owner for anything outside the written rule. Filipino staff can complete the routine work when the source, access, schedule, and escalation path are clear.`,
  sections: [
    { heading: `Define the ${topic.focus} queue`, body: [`Name the exact records or requests that enter the queue, how they arrive, what a finished item looks like, and where the result is recorded. Use a few completed examples before interviews so the role describes work rather than a personality.`, `Keep the first queue narrow. A small repeatable lane gives the worker practice, gives the manager a fair sample, and shows which rules are missing before more responsibility is added.`] },
    { heading: 'Write the normal path', body: [`A useful first path is: ${topic.steps[0]}, then ${topic.steps[1]}, then ${topic.steps[2]}. Put the source of truth beside each step, including the exact field or screen the worker should use.`, `Use a short handoff note for open questions. The note should include the record, the action already taken, the reason it stopped, and the person who owns the next answer.`] },
    { heading: 'Keep decisions with the right owner', body: [`The worker should not have to guess when a routine request becomes a company decision. ${topic.stop}`, `Name the internal owner, response window, and evidence to collect. A stop rule that only says ask a manager creates delay and makes the manager reconstruct the case.`] },
    { heading: 'Limit tools and customer data', body: [`Start with a named account and the lowest permission needed for this queue. Separate reading, drafting, sending, approving, exporting, deleting, and administration. Remove access when the assignment changes or ends.`, `Do not copy live personal data into an informal worksheet to make review easier. Use the approved system, masked examples, or a test space, and get qualified advice when the work is regulated or cross-border.`] },
    { heading: 'Review the first batch', body: [`Check every early item against the same fields: correct source, correct record, complete action, accurate note, and proper escalation. Record the cause of a miss instead of only marking it wrong.`, `If the same question appears more than once, repair the guide or source. Coaching helps one person; a process repair helps the whole queue.`] },
    { heading: 'Launch in 30 days', body: [`Days 1–3: write the queue and collect examples. Days 4–8: run a work sample and confirm schedule and tools. Days 9–14: practice with test or old records. Days 15–21: open one small live lane. Days 22–30: review quality, access, and manager load.`, `Add a second task only when the first lane has a stable source, a repeatable review, and no unresolved ownership gap.`] },
  ],
  comparison: [
    { weak: `We need help with ${topic.focus}.`, strong: `We need a Filipino specialist to complete the written ${topic.focus} queue, record each result, and stop on the listed exceptions.` },
    { weak: 'Quality matters to us.', strong: 'The internal owner will review the first ten items against the same written fields and record each miss by cause.' },
    { weak: 'Use the tools as needed.', strong: 'Start with a named account and only the permissions required for this queue; approval, export, and deletion stay with the owner.' },
  ],
  workflow: [
    { step: 'Days 1–3', title: 'Map the queue', body: `Write the source, examples, finish rule, access needs, schedule, and stop rules for ${topic.focus}.` },
    { step: 'Days 4–8', title: 'Test the work', body: 'Use the same normal, incomplete, and escalation cases for every candidate or trainee.' },
    { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or old work with personal details removed. Review every item before live access.' },
    { step: 'Days 15–21', title: 'Open one lane', body: 'Keep the first live volume small and make the owner available for blocked cases.' },
    { step: 'Days 22–30', title: 'Repair the process', body: 'Group misses by cause, update the guide, and add responsibility only when the queue is steady.' },
  ],
  script: [
    `Which exact ${topic.focus} cases will this role handle first?`,
    'Show us how a normal case, a missing-information case, and an escalation move through the queue.',
    'Which named accounts and permissions are needed on day one, and who approves changes?',
    'Who reviews the first batch, what fields do they check, and how are recurring misses repaired?',
  ],
  sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Authoritative guidance for identifying, protecting, detecting, responding to, and recovering from cybersecurity risk.' }],
  sourcesNumbered: true,
  faqs: [
    { question: `What should be outsourced first in ${topic.focus}?`, answer: 'Start with recurring work that has examples, a clear finish, limited access, and a named reviewer. Keep judgment, approvals, and sensitive exceptions with the appropriate owner.' },
    { question: 'How do I protect access?', answer: 'Use named accounts, least privilege, multi-factor login where available, an access record, and a removal step. Do not share passwords or broad admin rights.' },
    { question: 'When should the worker stop?', answer: topic.stop },
  ],
  relatedLinks: [
    { label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' },
    { label: 'Use the Philippines quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' },
    { label: 'See back-office operations support', href: '/services/back-office-operations' },
  ],
});

export const batchBlogPosts = topics.map(({ slug, title, excerpt }) => ({ slug, title, excerpt, minutes: 9 }));
export const batchBlogDetails = Object.fromEntries(topics.map((topic, index) => [topic.slug, makeDetails(topic, index)]));
