type Topic = { slug: string; title: string; keyword: string; focus: string; steps: string[]; stop: string };

const topicRows: [string, string, string, string, string[], string][] = [
  ['outsourcing-invoice-data-entry-philippines', 'Outsourcing invoice data entry to the Philippines', 'outsourcing invoice data entry Philippines', 'invoice data entry', ['collect approved invoices', 'match required fields', 'route exceptions'], 'Stop before approving an invoice, changing a vendor record, or releasing a payment.'],
  ['philippines-outsourcing-crm-cleanup', 'Philippines outsourcing CRM cleanup checklist', 'Philippines outsourcing CRM cleanup', 'CRM cleanup', ['export the approved view', 'apply field rules', 'log uncertain records'], 'Stop when records conflict, an ownership decision is needed, or a deletion is requested.'],
  ['philippines-outsourcing-lead-qualification', 'Philippines outsourcing lead qualification workflow', 'Philippines outsourcing lead qualification', 'lead qualification', ['read the approved criteria', 'check the lead record', 'route qualified leads'], 'Stop before changing qualification rules, making a sales promise, or contacting a restricted lead.'],
  ['outsourcing-order-entry-philippines', 'Outsourcing order entry to the Philippines: a control checklist', 'outsourcing order entry Philippines', 'order entry', ['read the approved order', 'check customer fields', 'route the order'], 'Stop before changing price, product availability, delivery terms, or payment status.'],
  ['philippines-outsourcing-data-validation', 'Philippines outsourcing data validation guide', 'Philippines outsourcing data validation', 'data validation', ['load the source file', 'test required fields', 'record validation results'], 'Stop when the source is incomplete, a rule is ambiguous, or a correction changes a business decision.'],
  ['philippines-outsourcing-calendar-management', 'Philippines outsourcing calendar management workflow', 'Philippines outsourcing calendar management', 'calendar management', ['review the approved request', 'check availability', 'send the draft invite'], 'Stop before accepting a conflict, changing a priority, or sharing confidential meeting details.'],
  ['philippines-outsourcing-recruiting-coordination', 'Philippines outsourcing recruiting coordination checklist', 'Philippines outsourcing recruiting coordination', 'recruiting coordination', ['maintain the candidate queue', 'check interview fields', 'route scheduling gaps'], 'Stop before evaluating a candidate, changing criteria, or sharing restricted applicant information.'],
  ['outsourcing-expense-review-philippines', 'Outsourcing expense review to the Philippines', 'outsourcing expense review Philippines', 'expense review', ['collect submitted expenses', 'check policy fields', 'route exceptions'], 'Stop before approving reimbursement, interpreting policy, or changing a category.'],
  ['philippines-outsourcing-help-desk-triage', 'Philippines outsourcing help desk triage plan', 'Philippines outsourcing help desk triage', 'help desk triage', ['identify the request', 'apply the runbook', 'route the severity'], 'Stop on security indicators, privileged access, data loss, or an incident outside the runbook.'],
  ['philippines-outsourcing-product-catalog-management', 'Philippines outsourcing product catalog management guide', 'Philippines outsourcing product catalog management', 'product catalog management', ['collect approved changes', 'check catalog fields', 'route the release'], 'Stop before changing price, claims, availability, or a regulated product attribute.'],
  ['outsourcing-research-assistant-philippines', 'Outsourcing research assistance to the Philippines', 'outsourcing research assistant Philippines', 'research assistance', ['define the question', 'search named sources', 'cite the findings'], 'Stop before presenting an unsupported conclusion, using private data, or advising on a regulated decision.'],
  ['philippines-outsourcing-reporting-support', 'Philippines outsourcing reporting support workflow', 'Philippines outsourcing reporting support', 'reporting support', ['collect approved metrics', 'check the reporting period', 'flag anomalies'], 'Stop before changing a metric definition, explaining an anomaly as fact, or publishing a report.'],
  ['philippines-outsourcing-customer-record-updates', 'Philippines outsourcing customer record updates', 'Philippines outsourcing customer record updates', 'customer record updates', ['read the approved request', 'check identity fields', 'record the change'], 'Stop when identity is uncertain, a sensitive field changes, or consent is unclear.'],
  ['outsourcing-returns-administration-philippines', 'Outsourcing returns administration to the Philippines', 'outsourcing returns administration Philippines', 'returns administration', ['review the return request', 'check the approved rule', 'route the exception'], 'Stop before issuing a refund, changing a policy outcome, or promising a replacement.'],
  ['philippines-outsourcing-subscription-administration', 'Philippines outsourcing subscription administration checklist', 'Philippines outsourcing subscription administration', 'subscription administration', ['review the account request', 'check the approved status', 'route the change'], 'Stop before changing terms, granting a concession, or cancelling an account with an unresolved dispute.'],
  ['philippines-outsourcing-document-review', 'Philippines outsourcing document review workflow', 'Philippines outsourcing document review', 'document review', ['load the approved document set', 'check named fields', 'log missing evidence'], 'Stop before interpreting legal language, certifying accuracy, or deleting a source record.'],
  ['outsourcing-project-admin-philippines', 'Outsourcing project administration to the Philippines', 'outsourcing project administration Philippines', 'project administration', ['update the approved tracker', 'check due dates', 'route blocked work'], 'Stop before reprioritizing scope, committing resources, or changing a project decision.'],
  ['philippines-outsourcing-survey-administration', 'Philippines outsourcing survey administration guide', 'Philippines outsourcing survey administration', 'survey administration', ['load the approved audience', 'check survey fields', 'record response status'], 'Stop before changing consent, altering questions, or interpreting the results.'],
  ['philippines-outsourcing-knowledge-base-content-maintenance', 'Philippines outsourcing knowledge base content maintenance', 'Philippines outsourcing knowledge base content maintenance', 'knowledge base content maintenance', ['review approved edits', 'check links and labels', 'route factual gaps'], 'Stop before changing policy, adding an unsourced claim, or publishing an unapproved instruction.'],
  ['outsourcing-vendor-data-management-philippines', 'Outsourcing vendor data management to the Philippines', 'outsourcing vendor data management Philippines', 'vendor data management', ['collect approved vendor changes', 'check required fields', 'route verification gaps'], 'Stop before approving a supplier, changing payment details, or overriding verification.'],
  ['philippines-outsourcing-shipping-status-updates', 'Philippines outsourcing shipping status updates', 'Philippines outsourcing shipping status updates', 'shipping status updates', ['read the carrier record', 'update allowed fields', 'route delayed shipments'], 'Stop before changing a delivery promise, customs detail, cost, or customer remedy.'],
  ['philippines-outsourcing-email-inbox-management', 'Philippines outsourcing email inbox management workflow', 'Philippines outsourcing email inbox management', 'email inbox management', ['sort the approved inbox', 'apply response labels', 'route open questions'], 'Stop before sending a commitment, handling sensitive data, or responding to a complaint.'],
  ['outsourcing-website-qa-philippines', 'Outsourcing website QA to the Philippines', 'outsourcing website QA Philippines', 'website QA', ['run the approved checklist', 'capture reproducible issues', 'route release blockers'], 'Stop before changing production code, altering analytics, or deciding whether a legal issue is acceptable.'],
  ['philippines-outsourcing-podcast-production', 'Philippines outsourcing podcast production checklist', 'Philippines outsourcing podcast production', 'podcast production', ['organize approved recordings', 'check the edit notes', 'route the preview'], 'Stop before changing the speaker meaning, clearing rights, or publishing an unapproved claim.'],
  ['philippines-outsourcing-localization-coordination', 'Philippines outsourcing localization coordination guide', 'Philippines outsourcing localization coordination', 'localization coordination', ['collect approved source copy', 'check language fields', 'route unclear meaning'], 'Stop before changing product meaning, translating a legal term, or approving final copy.'],
];
const topics: Topic[] = topicRows.map(([slug, title, keyword, focus, steps, stop]) => ({ slug, title, keyword, focus, steps, stop }));

// Keep the verified repair explicit for the one record whose source binding was missing.
const blogBatch2026_08_10Run2SourceDates: Record<string, string> = {
  'outsourcing-invoice-data-entry-philippines': '2026-08-10',
  'philippines-outsourcing-crm-cleanup': '2026-08-10',
  'philippines-outsourcing-lead-qualification': '2026-08-10',
};

const makeDetails = (topic: Topic, index: number) => ({
  updated: blogBatch2026_08_10Run2SourceDates[topic.slug] ?? '2026-08-10', keyword: topic.keyword, marker: `daily-blog-batch-2026-08-10-run-2-${String(index + 1).padStart(2, '0')}`,
  takeaway: `A reliable ${topic.focus} handoff starts with one queue, a visible done check, and a named owner for anything outside the written rule. Filipino staff can complete routine work when the source, access, schedule, and escalation path are clear.`,
  comparison: [
    { weak: `We need help with ${topic.focus}.`, strong: `We need a Filipino specialist to complete the written ${topic.focus} queue, record each result, and stop on the listed exceptions.` },
    { weak: 'Quality matters to us.', strong: 'The internal owner will review the first ten items against the same written fields and record each miss by cause.' },
    { weak: 'Use the tools as needed.', strong: 'Start with a named account and only the permissions required for this queue; approval, export, and deletion stay with the owner.' },
  ],
  sections: [
    { heading: `Define the ${topic.focus} queue`, body: [`Name the records or requests that enter the queue, how they arrive, what a finished item looks like, and where the result is recorded. Use completed examples so the role describes work rather than a personality.`, `Keep the first queue narrow. A small repeatable lane gives the worker practice, gives the manager a fair sample, and exposes missing rules before more responsibility is added.`] },
    { heading: 'Write the normal path', body: [`A useful first path is: ${topic.steps[0]}, then ${topic.steps[1]}, then ${topic.steps[2]}. Put the source of truth beside each step, including the exact field or screen the worker should use.`, 'Use a short handoff note for open questions. Include the record, the action already taken, the reason it stopped, and the person who owns the next answer.'] },
    { heading: 'Keep decisions with the right owner', body: [`The worker should not guess when routine work becomes a company decision. ${topic.stop}`, 'Name the internal owner, response window, and evidence to collect. A stop rule that only says ask a manager creates delay and makes the manager reconstruct the case.'] },
    { heading: 'Limit tools and data', body: ['Start with a named account and the lowest permission needed for this queue. Separate reading, drafting, sending, approving, exporting, deleting, and administration.', 'Use the approved system or masked examples for review. Do not copy live personal data into an informal worksheet.'] },
    { heading: 'Review the first batch', body: ['Check every early item against the same fields: correct source, correct record, complete action, accurate note, and proper escalation. Record the cause of a miss instead of only marking it wrong.', 'If the same question appears more than once, repair the guide or source. Process repair helps the whole queue.'] },
    { heading: 'Launch in 30 days', body: ['Days 1–3: write the queue and collect examples. Days 4–8: run a work sample and confirm schedule and tools. Days 9–14: practice with test or old records. Days 15–21: open one small live lane. Days 22–30: review quality, access, and manager load.', 'Add a second task only when the first lane has a stable source, a repeatable review, and no unresolved ownership gap.'] },
  ],
  workflow: [{ step: 'Days 1–3', title: 'Map the queue', body: `Write the source, examples, finish rule, access needs, schedule, and stop rules for ${topic.focus}.` }, { step: 'Days 4–8', title: 'Test the work', body: 'Use the same normal, incomplete, and escalation cases for every candidate or trainee.' }, { step: 'Days 9–14', title: 'Practice safely', body: 'Use test records or old work with personal details removed. Review every item before live access.' }, { step: 'Days 15–21', title: 'Open one lane', body: 'Keep the first live volume small and make the owner available for blocked cases.' }, { step: 'Days 22–30', title: 'Repair the process', body: 'Group misses by cause, update the guide, and add responsibility only when the queue is steady.' }],
  script: [`Which exact ${topic.focus} cases will this role handle first?`, 'Show us how a normal case, a missing-information case, and an escalation move through the queue.', 'Which named accounts and permissions are needed on day one, and who approves changes?', 'Who reviews the first batch, what fields do they check, and how are recurring misses repaired?'],
  sourcesNumbered: true, sources: [{ name: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework', note: 'Authoritative guidance for identifying, protecting, detecting, responding to, and recovering from cybersecurity risk.' }],
  faqs: [{ question: `What should be outsourced first in ${topic.focus}?`, answer: 'Start with recurring work that has examples, a clear finish, limited access, and a named reviewer. Keep judgment, approvals, and sensitive exceptions with the appropriate owner.' }, { question: 'How do I protect access?', answer: 'Use named accounts, least privilege, multi-factor login where available, an access record, and a removal step. Do not share passwords or broad admin rights.' }, { question: 'When should the worker stop?', answer: topic.stop }],
  relatedLinks: [{ label: 'Read the Philippines outsourcing buyer guide', href: '/blog/outsource-to-the-philippines-guide' }, { label: 'Use the Philippines quality assurance checklist', href: '/blog/philippines-outsourcing-quality-assurance-checklist' }, { label: 'See back-office operations support', href: '/services/back-office-operations' }],
});

export const blogBatch2026_08_10Run2Posts = topics.map(({ slug, title }) => ({ slug, title, excerpt: `Set up ${title.toLowerCase().replace(/^.*?: /, '')} with a written queue, limited access, and a clear owner for exceptions.`, minutes: 9 }));
export const blogBatch2026_08_10Run2Details = Object.fromEntries(topics.map((topic, index) => [topic.slug, makeDetails(topic, index)]));
